'use client'

import type { RoastCategory, RoastResult } from '@/app/api/mini-apps/website-roast/route'
import '../page-styles.css'

export type WebsiteRoastInput = { url: string }
export type WebsiteRoastOutput = RoastResult

type Props = {
  input: WebsiteRoastInput
  output: WebsiteRoastOutput
  /**
   * When true, render only the inner result body without surrounding panel
   * wrappers or the result-footer. The inline mini-app page provides those
   * itself and keeps its own export buttons. The standalone
   * `/results/[id]` route uses the default (full) render.
   */
  bare?: boolean
  /**
   * Override the timestamp label rendered in the result footer. The inline
   * page passes a formatted timestamp like `ROAST · 2026-06-10 · 14:32 UTC`.
   */
  tsLabel?: string
  /**
   * Token counts shown in the result footer. Inline page passes the live
   * counts; standalone results page omits this.
   */
  tokens?: { in: number; out: number } | null
}

export function overallGradeClass(grade: string): string {
  if (grade === 'A' || grade === 'B') return 'good'
  if (grade === 'C') return 'mid'
  return 'bad'
}

export function scoreBadgeClass(score: number): string {
  if (score >= 7) return 'high'
  if (score >= 4) return 'mid'
  return 'low'
}

export function buildWebsiteRoastPlainText(r: RoastResult): string {
  const lh = (label: string, v: number | null) => `${label}: ${v !== null ? `${v}/100` : '—'}`

  return [
    `Website Roast — ${r.site_name}`,
    r.url,
    '='.repeat(60),
    '',
    r.one_liner,
    '',
    `Overall: ${r.overall_score}/100 (Grade ${r.overall_grade})`,
    '',
    lh('Performance', r.lighthouse.performance),
    lh('SEO', r.lighthouse.seo),
    lh('Accessibility', r.lighthouse.accessibility),
    lh('Best Practices', r.lighthouse.best_practices),
    '',
    '// CATEGORIES',
    ...r.categories.map(
      (c) => `\n[${c.name}] ${c.score}/10 (${c.grade})\n${c.roast}\nFix: ${c.quick_fix}`
    ),
    '',
    '// TOP 3 FIXES',
    ...r.top_3_fixes.map((f, i) => `  ${i + 1}. ${f}`),
    '',
    `Tokens: ${(r.tokens_in + r.tokens_out).toLocaleString()} (${r.tokens_in.toLocaleString()} in / ${r.tokens_out.toLocaleString()} out)`,
    'Generated by S7 Labs Website Roast Bot',
  ].join('\n')
}

function CategoryCard({ cat }: { cat: RoastCategory }) {
  return (
    <div className="category-card">
      <div className="category-card-header">
        <span className="category-name">{cat.name}</span>
        <span className={`score-badge ${scoreBadgeClass(cat.score)}`}>
          {cat.score}/10 · {cat.grade}
        </span>
      </div>
      <p className="category-roast">{cat.roast}</p>
      <div className="category-fix">
        <span className="fix-label">Fix</span>
        <span className="fix-text">{cat.quick_fix}</span>
      </div>
    </div>
  )
}

function LighthouseMini({ label, value }: { label: string; value: number | null }) {
  return (
    <div className="lh-mini">
      <span className="lh-label">{label}</span>
      <span className={`lh-value${value === null ? 'null' : ''}`}>
        {value !== null ? value : '—'}
      </span>
    </div>
  )
}

function ResultBody({ output }: { output: WebsiteRoastOutput }) {
  return (
    <>
      <div className="one-liner-block">
        <p className="one-liner-text">&ldquo;{output.one_liner}&rdquo;</p>
        <div className="one-liner-meta">
          <span className="site-name">{output.site_name}</span>
          <span className="url-pill">{output.url}</span>
        </div>
      </div>

      <div className="score-row">
        <div className={`score-card ${overallGradeClass(output.overall_grade)}`}>
          <div className="sc-label">Overall score</div>
          <div className="sc-value">
            <span className="sc-big">{output.overall_score}</span>
            <span className="sc-small">/100</span>
          </div>
          <div className="sc-delta">Grade {output.overall_grade}</div>
        </div>
        <div className="score-card lighthouse-card">
          <div className="sc-label">Lighthouse (mobile)</div>
          <div className="lighthouse-grid">
            <LighthouseMini label="Performance" value={output.lighthouse.performance} />
            <LighthouseMini label="SEO" value={output.lighthouse.seo} />
            <LighthouseMini label="Accessibility" value={output.lighthouse.accessibility} />
            <LighthouseMini label="Best Practices" value={output.lighthouse.best_practices} />
          </div>
        </div>
      </div>

      <div className="section-header">
        <span>{'// Category breakdown'}</span>
        <span>6 categories</span>
      </div>
      <div className="category-grid">
        {output.categories.map((cat) => (
          <CategoryCard key={cat.name} cat={cat} />
        ))}
      </div>

      <div className="fixes-block">
        <div className="fixes-eyebrow">{'// 3 things to fix first'}</div>
        <ol className="fixes-list">
          {output.top_3_fixes.map((fix, i) => (
            <li key={i} className="fix-row">
              <span className="fix-number">{String(i + 1).padStart(2, '0')}</span>
              <span className="fix-text-main">{fix}</span>
            </li>
          ))}
        </ol>
      </div>
    </>
  )
}

export function WebsiteRoastResult({ input, output, bare = false, tsLabel, tokens }: Props) {
  void input
  if (bare) {
    return <ResultBody output={output} />
  }
  return (
    <div className="website-roast">
      <div className="panel-wrap">
        <div className="panel">
          <div className="panel-body">
            <section className="wr-state active">
              <ResultBody output={output} />

              <div className="result-footer">
                <span className="token-pill">
                  {tokens
                    ? `${(tokens.in + tokens.out).toLocaleString()} tokens · ${tokens.in.toLocaleString()} in / ${tokens.out.toLocaleString()} out`
                    : `${(output.tokens_in + output.tokens_out).toLocaleString()} tokens · ${output.tokens_in.toLocaleString()} in / ${output.tokens_out.toLocaleString()} out`}
                </span>
                {tsLabel && <span className="result-ts hide-sm">{tsLabel}</span>}
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>
  )
}
