'use client'

import { clsx } from 'clsx'
import type { Ref } from 'react'
import type { StackChoice, StackResult } from '@/app/api/mini-apps/tech-stack-recommender/route'
import '../page-styles.css'

export type TechStackRecommenderInput = { brief?: string; description?: string }
export type TechStackRecommenderOutput = StackResult

type Props = {
  input: TechStackRecommenderInput
  output: TechStackRecommenderOutput
  /**
   * When true, render only the inner result body (head + one-liner + stats
   * + diagram + layers + services + considerations) without the
   * surrounding `.tech-stack-recommender / .panel-wrap / .panel /
   * .panel-body / .tsr-state` wrappers or the `.result-footer`. The inline
   * mini-app page provides those itself and keeps its own export buttons.
   * The standalone `/results/[id]` route uses the default (full) render.
   */
  bare?: boolean
  /**
   * Forwarded ref attached to the `<StackDiagram>` wrapper so the inline
   * page can capture only the diagram for PNG/PDF export.
   */
  diagramRef?: Ref<HTMLDivElement>
}

const LAYER_ACCENTS: Record<string, string> = {
  Frontend: 'layer-frontend',
  Backend: 'layer-backend',
  Database: 'layer-database',
  Hosting: 'layer-hosting',
  Auth: 'layer-auth',
  Payments: 'layer-payments',
}

export function complexityClass(c: string): string {
  if (c === 'Simple') return 'is-simple'
  if (c === 'Moderate') return 'is-moderate'
  if (c === 'Ambitious') return 'is-ambitious'
  return 'is-complex'
}

export function buildTechStackRecommenderPlainText(r: StackResult): string {
  return [
    `Tech Stack — ${r.project_name}`,
    r.project_type,
    '='.repeat(60),
    '',
    r.one_liner,
    '',
    `Complexity: ${r.complexity} (${r.complexity_score}/10)`,
    `Build (est.): ${r.build_estimate}`,
    `Monthly cost (est.): ${r.monthly_cost_estimate}`,
    '',
    '// STACK',
    ...r.layers.map(
      (l) =>
        `${l.layer}: ${l.pick} (${l.monthly_cost})\n  ${l.why}\n  Alt: ${l.alternatives.join(', ')}`
    ),
    '',
    '// KEY SERVICES',
    ...r.key_services.map((s) => `  ${s.name} — ${s.purpose}`),
    '',
    '// CONSIDERATIONS',
    ...r.considerations.map((c, i) => `  ${i + 1}. ${c}`),
    '',
    'Generated by S7 Labs Tech Stack Recommender',
  ].join('\n')
}

function StatMini({
  label,
  value,
  valueClass,
}: {
  label: string
  value: string
  valueClass?: string
}) {
  return (
    <div className="stat-mini">
      <span className="stat-label">{label}</span>
      <span className={clsx('stat-value', valueClass)}>{value}</span>
    </div>
  )
}

function StackDiagram({ layers }: { layers: StackChoice[] }) {
  return (
    <div className="stack-diagram" aria-label="Recommended architecture layers">
      <div className="stack-diagram-header">
        <span>{'// architecture'}</span>
        <span className="stack-diagram-hint">Screenshot-ready</span>
      </div>
      <div className="stack-diagram-body">
        {layers.map((layer, i) => (
          <div key={layer.layer} className="stack-diagram-row">
            {i > 0 && <div className="stack-connector" aria-hidden />}
            <div className={clsx('stack-layer', LAYER_ACCENTS[layer.layer])}>
              <span className="stack-layer-label">{layer.layer}</span>
              <span className="stack-layer-pick">{layer.pick}</span>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

function LayerCard({ layer }: { layer: StackChoice }) {
  return (
    <div className="layer-card">
      <div className="layer-card-header">
        <span className="layer-name">{layer.layer}</span>
        <span className="pick-badge">{layer.pick}</span>
        <span className="cost-tag">{layer.monthly_cost}</span>
      </div>
      <p className="layer-why">{layer.why}</p>
      {layer.alternatives.length > 0 && (
        <p className="layer-alts">or: {layer.alternatives.join(', ')}</p>
      )}
    </div>
  )
}

function ResultBody({
  output,
  diagramRef,
}: {
  output: TechStackRecommenderOutput
  diagramRef?: Ref<HTMLDivElement>
}) {
  return (
    <>
      <div className="result-head">
        <span className="title">Recommended stack</span>
        <span className="ts-label">{output.project_name}</span>
      </div>

      <div className="one-liner-block">
        <p className="one-liner-text">&ldquo;{output.one_liner}&rdquo;</p>
        <div className="one-liner-meta">
          <span className="project-name">{output.project_name}</span>
          <span className="type-pill">{output.project_type}</span>
        </div>
        <p className="estimate-note">
          Cost, complexity, and build time are estimates at MVP scale.
        </p>
      </div>

      <div className="stats-row">
        <div className="score-card cost-card">
          <div className="sc-label">Monthly cost (est.)</div>
          <div className="sc-value">
            <span className="sc-big">{output.monthly_cost_estimate}</span>
          </div>
          <div className="sc-delta">Build: {output.build_estimate}</div>
        </div>
        <div className="score-card glance-card">
          <div className="sc-label">At a glance</div>
          <div className="stat-grid">
            <StatMini
              label="Complexity"
              value={output.complexity}
              valueClass={`complexity-badge ${complexityClass(output.complexity)}`}
            />
            <StatMini label="Layers" value="6" />
            <StatMini label="Build time" value={output.build_estimate} />
            <StatMini label="Services" value={String(output.key_services.length)} />
          </div>
        </div>
      </div>

      <div ref={diagramRef}>
        <StackDiagram layers={output.layers} />
      </div>

      <div className="section-header">
        <span>{'// Layer breakdown'}</span>
        <span>6 layers</span>
      </div>
      <div className="layer-grid">
        {output.layers.map((layer) => (
          <LayerCard key={layer.layer} layer={layer} />
        ))}
      </div>

      {output.key_services.length > 0 && (
        <>
          <div className="section-header">
            <span>{'// third-party services'}</span>
          </div>
          <div className="services-row">
            {output.key_services.map((svc) => (
              <div key={svc.name} className="service-pill">
                <span className="service-name">{svc.name}</span>
                <span className="service-purpose">{svc.purpose}</span>
              </div>
            ))}
          </div>
        </>
      )}

      <div className="considerations-block">
        <div className="considerations-eyebrow">{'// before you build'}</div>
        <ol className="considerations-list">
          {output.considerations.map((item, i) => (
            <li key={i} className="consideration-row">
              <span className="consideration-number">{String(i + 1).padStart(2, '0')}</span>
              <span className="consideration-text">{item}</span>
            </li>
          ))}
        </ol>
      </div>
    </>
  )
}

export function TechStackRecommenderResult({ input, output, bare = false, diagramRef }: Props) {
  void input
  if (bare) {
    return <ResultBody output={output} diagramRef={diagramRef} />
  }
  return (
    <div className="tech-stack-recommender">
      <div className="panel-wrap panel-wrap-wide">
        <div className="panel">
          <span className="corner tl" />
          <span className="corner tr" />
          <span className="corner bl" />
          <span className="corner br" />
          <div className="panel-body">
            <section className="tsr-state active">
              <ResultBody output={output} diagramRef={diagramRef} />
            </section>
          </div>
        </div>
      </div>
    </div>
  )
}
