'use client'

import type { Phase, ProposalResult, TechItem } from '@/app/api/mini-apps/proposal-engine/route'
import '../page-styles.css'

export type ProposalEngineInput = { brief_text?: string; brief?: string; tone?: string }
export type ProposalEngineOutput = ProposalResult

type Tone = 'formal' | 'conversational' | 'technical'

type Props = {
  input: ProposalEngineInput
  output: ProposalEngineOutput
  /**
   * When true, render only the inner proposal body (head + doc) without
   * the surrounding `.proposal-engine / .panel-wrap / .panel / .panel-body
   * / .pe-state` wrappers or the `.result-footer`. The inline mini-app
   * page provides those itself and keeps its own export buttons. The
   * standalone `/results/[id]` route uses the default (full) render.
   */
  bare?: boolean
  /**
   * Override the timestamp label in the result head. Inline page passes a
   * formatted timestamp like `PROPOSAL · 2026-06-10 · 14:32 UTC`. When
   * omitted, no timestamp is rendered.
   */
  tsLabel?: string
}

export const TECH_CATEGORY_ORDER: TechItem['category'][] = [
  'frontend',
  'backend',
  'infrastructure',
  'ai',
  'integrations',
  'other',
]

export const TECH_CATEGORY_LABEL: Record<TechItem['category'], string> = {
  frontend: 'Frontend',
  backend: 'Backend',
  infrastructure: 'Infrastructure',
  ai: 'AI',
  integrations: 'Integrations',
  other: 'Other',
}

export const TONE_LABEL: Record<Tone, string> = {
  formal: 'Formal',
  conversational: 'Conversational',
  technical: 'Technical',
}

export function groupTechStack(items: TechItem[]): Map<TechItem['category'], TechItem[]> {
  const map = new Map<TechItem['category'], TechItem[]>()
  for (const item of items) {
    const list = map.get(item.category) ?? []
    list.push(item)
    map.set(item.category, list)
  }
  return map
}

export function buildProposalEnginePlainText(r: ProposalResult): string {
  const lines: string[] = [
    'Proposal Draft — S7 Labs',
    '='.repeat(60),
    '',
    r.client_summary,
    '',
    `Tone: ${TONE_LABEL[r.tone as Tone] ?? r.tone}`,
    '',
    `// ${r.scope.title.toUpperCase()}`,
    r.scope.content,
  ]
  if (r.scope.bullets?.length) {
    lines.push('', ...r.scope.bullets.map((b) => `  · ${b}`))
  }
  lines.push('', '// PHASES')
  for (const phase of r.phases) {
    lines.push(
      '',
      `Phase ${phase.number}: ${phase.name} (${phase.duration})`,
      ...phase.deliverables.map((d) => `  · ${d}`)
    )
  }
  lines.push('', '// TECH STACK')
  for (const cat of TECH_CATEGORY_ORDER) {
    const items = r.tech_stack.filter((t) => t.category === cat)
    if (!items.length) continue
    lines.push('', TECH_CATEGORY_LABEL[cat])
    for (const t of items) {
      lines.push(`  ${t.name} — ${t.reason}`)
    }
  }
  lines.push(
    '',
    '// TIMELINE',
    `${r.timeline_weeks} weeks`,
    r.timeline_note,
    '',
    `// ${r.why_s7.title.toUpperCase()}`,
    r.why_s7.content
  )
  if (r.why_s7.bullets?.length) {
    lines.push('', ...r.why_s7.bullets.map((b) => `  · ${b}`))
  }
  lines.push(
    '',
    `Tokens: ${(r.tokens_in + r.tokens_out).toLocaleString()} (${r.tokens_in.toLocaleString()} in / ${r.tokens_out.toLocaleString()} out)`,
    'Generated by S7 Labs Proposal Draft Engine'
  )
  return lines.join('\n')
}

function PhaseCard({ phase }: { phase: Phase }) {
  return (
    <div className="phase-card">
      <div className="phase-card-header">
        <span className="phase-num">{String(phase.number).padStart(2, '0')}</span>
        <span className="phase-name">{phase.name}</span>
        <span className="phase-duration">{phase.duration}</span>
      </div>
      <ul className="phase-deliverables">
        {phase.deliverables.map((d) => (
          <li key={d}>{d}</li>
        ))}
      </ul>
    </div>
  )
}

function ResultBody({ output, tsLabel }: { output: ProposalEngineOutput; tsLabel?: string }) {
  const techGroups = groupTechStack(output.tech_stack)
  return (
    <>
      {tsLabel && (
        <div className="result-head">
          <span className="title">Proposal draft</span>
          <span className="ts-label">{tsLabel}</span>
        </div>
      )}
      <div className="proposal-doc">
        <div className="doc-header">
          <p className="doc-summary">{output.client_summary}</p>
          <div className="doc-badges">
            <span className="badge dept">{TONE_LABEL[output.tone as Tone] ?? output.tone}</span>
          </div>
        </div>

        <div className="proposal-section">
          <div className="section-eyebrow">{`// ${output.scope.title}`}</div>
          <p className="section-content">{output.scope.content}</p>
          {output.scope.bullets && output.scope.bullets.length > 0 && (
            <ul className="section-bullets">
              {output.scope.bullets.map((b) => (
                <li key={b}>{b}</li>
              ))}
            </ul>
          )}
        </div>

        <div className="proposal-section">
          <div className="section-eyebrow">{'// Project phases'}</div>
          <div className="phases-grid">
            {output.phases.map((phase) => (
              <PhaseCard key={phase.number} phase={phase} />
            ))}
          </div>
        </div>

        {output.tech_stack.length > 0 && (
          <div className="proposal-section">
            <div className="section-eyebrow">{'// Tech stack'}</div>
            <div className="tech-groups">
              {TECH_CATEGORY_ORDER.map((cat) => {
                const items = techGroups.get(cat)
                if (!items?.length) return null
                return (
                  <div key={cat}>
                    <div className="tech-group-label">{TECH_CATEGORY_LABEL[cat]}</div>
                    {items.map((t) => (
                      <div key={`${cat}-${t.name}`} className="tech-item">
                        <span className="tech-name">{t.name}</span>
                        <span className="tech-reason">{t.reason}</span>
                      </div>
                    ))}
                  </div>
                )
              })}
            </div>
          </div>
        )}

        <div className="proposal-section">
          <div className="section-eyebrow">{'// Timeline'}</div>
          <div className="timeline-display">
            <div className="timeline-weeks">{output.timeline_weeks}</div>
            <div className="timeline-weeks-label">estimated weeks</div>
            <p className="timeline-note">{output.timeline_note}</p>
          </div>
        </div>

        <div className="why-s7-block">
          <div className="why-s7-eyebrow">{`// ${output.why_s7.title}`}</div>
          <p className="why-s7-content">{output.why_s7.content}</p>
          {output.why_s7.bullets && output.why_s7.bullets.length > 0 && (
            <ul className="why-s7-bullets">
              {output.why_s7.bullets.map((b) => (
                <li key={b}>{b}</li>
              ))}
            </ul>
          )}
        </div>
      </div>
    </>
  )
}

export function ProposalEngineResult({ input, output, bare = false, tsLabel }: Props) {
  void input
  if (bare) {
    return <ResultBody output={output} tsLabel={tsLabel} />
  }
  return (
    <div className="proposal-engine">
      <div className="panel-wrap">
        <div className="panel">
          <span className="corner tl" />
          <span className="corner tr" />
          <span className="corner bl" />
          <span className="corner br" />
          <div className="panel-body">
            <section className="pe-state active">
              <ResultBody output={output} tsLabel={tsLabel} />
            </section>
          </div>
        </div>
      </div>
    </div>
  )
}
