'use client'

import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent } from 'react'
import './page-styles.css'
import { Footer } from '@/components/Footer'
import { Header } from '@/components/Header'
import { AuroraBackground } from '@/components/mini-apps/AuroraBackground'
import { EmailGate } from '@/components/mini-apps/EmailGate'
import { HowItWorks, type HowItWorksStep } from '@/components/mini-apps/HowItWorks'
import { SubmitOnce } from '@/components/mini-apps/SubmitOnce'
import type {
  ApiResponse,
  CampaignIdea,
  CampaignIdeationResult,
} from '@/app/api/mini-apps/campaign-ideation/route'
import { PageScripts } from './PageScripts'

type AppState = 'idle' | 'loading' | 'result' | 'error'
type MotionChip = 'Outbound' | 'Inbound' | 'Content' | 'Paid' | 'None yet'

const MOTION_CHIPS: MotionChip[] = ['Outbound', 'Inbound', 'Content', 'Paid', 'None yet']

const HIW_STEPS: HowItWorksStep[] = [
  {
    title: 'Describe your offer and audience',
    description: 'Add what you sell, who it is for, and optional motion + goals.',
    icon: (
      <svg
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.6"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <rect x="3" y="4" width="18" height="16" rx="2" />
        <path d="M7 8h10M7 12h10M7 16h6" />
      </svg>
    ),
  },
  {
    title: 'We map your positioning',
    description: 'The app identifies the sharpest message angle for this exact context.',
    icon: (
      <svg
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.6"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M3 12l9-9 9 9-9 9-9-9z" />
        <path d="M12 7v10M8 12h8" />
      </svg>
    ),
  },
  {
    title: 'Get 7 campaign concepts',
    description: 'Each idea includes channels, format, first step, effort, and expected outcome.',
    icon: (
      <svg
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.6"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <circle cx="12" cy="12" r="9" />
        <path d="M12 7v5l3 3" />
      </svg>
    ),
  },
  {
    title: 'Ship the strongest one today',
    description: 'Copy one card or the full plan, print it, and brief your team immediately.',
    icon: (
      <svg
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.6"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M9 11l3 3 8-8" />
        <path d="M20 12v6a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h9" />
      </svg>
    ),
  },
]

const STAGES = [
  'Framing campaign brief',
  'Matching channels to audience',
  'Drafting ideas and hooks',
  'Finalizing execution steps',
]

const SAMPLE_INPUT = {
  product:
    'We help SaaS teams automatically enrich and route inbound leads with intent scoring and CRM sync.',
  audience:
    'VP Sales and RevOps leaders at B2B SaaS companies (50-500 employees) struggling with slow lead follow-up and poor MQL quality.',
  currentMotion: 'Outbound + inbound mix with light content',
  goal: 'Book 20 qualified demos in the next 45 days without increasing SDR headcount.',
}

function formatReportTs(d: Date) {
  const pad = (n: number) => String(n).padStart(2, '0')
  return `REPORT · ${d.getUTCFullYear()}-${pad(d.getUTCMonth() + 1)}-${pad(d.getUTCDate())} · ${pad(d.getUTCHours())}:${pad(d.getUTCMinutes())} UTC`
}

function ideaToText(idea: CampaignIdea, index: number) {
  return [
    `${index + 1}. ${idea.name}`,
    `Hook: ${idea.hook}`,
    `Channels: ${idea.channels.join(', ')}`,
    `Format: ${idea.format}`,
    `First step: ${idea.firstStep}`,
    `Expected outcome: ${idea.expectedOutcome}`,
    `Effort: ${idea.effort.toUpperCase()}`,
  ].join('\n')
}

function buildPlainText(result: CampaignIdeationResult) {
  return [
    'Campaign Ideation Plan',
    '='.repeat(60),
    '',
    '// POSITIONING',
    result.summary.positioning,
    '',
    '// IDEAS',
    ...result.ideas.map((idea, index) => ideaToText(idea, index)),
    '',
    `Tokens: ${(result.tokens_in + result.tokens_out).toLocaleString()} (${result.tokens_in.toLocaleString()} in / ${result.tokens_out.toLocaleString()} out)`,
    'Generated by S7 Labs Campaign Ideation',
  ].join('\n\n')
}

function Field({
  label,
  value,
  placeholder,
  onChange,
  disabled,
  minChars,
  error,
  rows = 4,
}: {
  label: string
  value: string
  placeholder: string
  onChange: (next: string) => void
  disabled: boolean
  minChars?: number
  error?: string | null
  rows?: number
}) {
  return (
    <label className="ci-field">
      <span className="ci-field-label">{label}</span>
      <textarea
        value={value}
        rows={rows}
        disabled={disabled}
        placeholder={placeholder}
        onChange={(e) => onChange(e.target.value)}
      />
      <span className={`ci-meta${error ? 'error' : ''}`}>
        {error ?? `${value.length} chars${minChars ? ` (min ${minChars})` : ''}`}
      </span>
    </label>
  )
}

function IdeaCard({ idea, index }: { idea: CampaignIdea; index: number }) {
  const [copied, setCopied] = useState(false)

  const handleCopy = useCallback(async () => {
    const text = ideaToText(idea, index)
    try {
      await navigator.clipboard.writeText(text)
    } catch {
      const ta = document.createElement('textarea')
      ta.value = text
      ta.style.cssText = 'position:fixed;opacity:0'
      document.body.appendChild(ta)
      ta.select()
      document.execCommand('copy')
      document.body.removeChild(ta)
    }
    setCopied(true)
    setTimeout(() => setCopied(false), 1600)
  }, [idea, index])

  return (
    <article className="ci-idea-card">
      <div className="ci-idea-head">
        <span className="ci-idea-num">{String(index + 1).padStart(2, '0')}</span>
        <span className={`ci-effort ${idea.effort}`}>{idea.effort}</span>
      </div>
      <h3>{idea.name}</h3>
      <p>{idea.hook}</p>
      <div className="ci-row">
        <span className="ci-key">Channels</span>
        <span className="ci-val">{idea.channels.join(' · ')}</span>
      </div>
      <div className="ci-row">
        <span className="ci-key">Format</span>
        <span className="ci-val">{idea.format}</span>
      </div>
      <div className="ci-row">
        <span className="ci-key">First step</span>
        <span className="ci-val">{idea.firstStep}</span>
      </div>
      <div className="ci-row">
        <span className="ci-key">Expected outcome</span>
        <span className="ci-val">{idea.expectedOutcome}</span>
      </div>
      <button className="ci-copy-btn" type="button" onClick={handleCopy}>
        {copied ? 'Copied' : 'Copy card'}
      </button>
    </article>
  )
}

export default function CampaignIdeationPage() {
  const [appState, setAppState] = useState<AppState>('idle')
  const [product, setProduct] = useState('')
  const [audience, setAudience] = useState('')
  const [currentMotion, setCurrentMotion] = useState('')
  const [goal, setGoal] = useState('')
  const [selectedMotion, setSelectedMotion] = useState<MotionChip | null>(null)
  const [errorMsg, setErrorMsg] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const [result, setResult] = useState<CampaignIdeationResult | null>(null)
  const [resultTs, setResultTs] = useState('')
  const [activeStage, setActiveStage] = useState(0)
  const [clock, setClock] = useState('—')
  const [progress, setProgress] = useState(0)
  const [copyState, setCopyState] = useState<'idle' | 'copied'>('idle')
  const [prodError, setProdError] = useState<string | null>(null)
  const [audError, setAudError] = useState<string | null>(null)

  const stageTimerRef = useRef<ReturnType<typeof setInterval> | null>(null)
  const progressTimerRef = useRef<ReturnType<typeof setInterval> | null>(null)

  useEffect(() => {
    const tick = () => {
      const d = new Date()
      const pad = (n: number) => String(n).padStart(2, '0')
      setClock(`${pad(d.getUTCHours())}:${pad(d.getUTCMinutes())}:${pad(d.getUTCSeconds())}Z`)
    }
    tick()
    const t = setInterval(tick, 1000)
    return () => clearInterval(t)
  }, [])

  const clearLoadTimers = useCallback(() => {
    if (stageTimerRef.current) clearInterval(stageTimerRef.current)
    if (progressTimerRef.current) clearInterval(progressTimerRef.current)
    stageTimerRef.current = null
    progressTimerRef.current = null
  }, [])

  useEffect(() => () => clearLoadTimers(), [clearLoadTimers])

  const startLoading = useCallback(() => {
    clearLoadTimers()
    setActiveStage(0)
    setProgress(4)
    stageTimerRef.current = setInterval(() => {
      setActiveStage((prev) => Math.min(prev + 1, STAGES.length - 1))
    }, 1700)
    progressTimerRef.current = setInterval(() => {
      setProgress((prev) => (prev >= 94 ? prev : prev + 3))
    }, 220)
  }, [clearLoadTimers])

  const leadInput = useMemo(
    () => ({
      product: product.trim(),
      audience: audience.trim(),
      currentMotion: currentMotion.trim() || undefined,
      goal: goal.trim() || undefined,
    }),
    [product, audience, currentMotion, goal]
  )

  const handleTrySample = useCallback(() => {
    setProduct(SAMPLE_INPUT.product)
    setAudience(SAMPLE_INPUT.audience)
    setCurrentMotion(SAMPLE_INPUT.currentMotion)
    setGoal(SAMPLE_INPUT.goal)
    setSelectedMotion(null)
    setProdError(null)
    setAudError(null)
  }, [])

  const handleSubmit = useCallback(
    async (e: FormEvent) => {
      e.preventDefault()
      if (submitting) return

      const p = product.trim()
      const a = audience.trim()

      let invalid = false
      if (p.length < 20 || p.length > 1500) {
        setProdError('Product must be 20-1500 chars.')
        invalid = true
      } else {
        setProdError(null)
      }
      if (a.length < 20 || a.length > 1500) {
        setAudError('Audience must be 20-1500 chars.')
        invalid = true
      } else {
        setAudError(null)
      }
      if (invalid) return

      setSubmitting(true)
      setErrorMsg('')
      setAppState('loading')
      setResult(null)
      startLoading()

      let data: ApiResponse
      try {
        const res = await fetch('/api/mini-apps/campaign-ideation', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            product: p,
            audience: a,
            currentMotion: currentMotion.trim() || undefined,
            goal: goal.trim() || undefined,
          }),
        })
        data = (await res.json()) as ApiResponse
      } catch {
        clearLoadTimers()
        setErrorMsg('Network error. Please check your connection and try again.')
        setAppState('error')
        setSubmitting(false)
        return
      }

      clearLoadTimers()
      setProgress(100)
      if (data.ok) {
        setResult(data.data)
        setResultTs(formatReportTs(new Date()))
        setAppState('result')
      } else {
        setErrorMsg(data.message)
        setAppState('error')
      }
      setSubmitting(false)
    },
    [audience, clearLoadTimers, currentMotion, goal, product, startLoading, submitting]
  )

  const handleCopyAll = useCallback(async () => {
    if (!result) return
    try {
      await navigator.clipboard.writeText(buildPlainText(result))
    } catch {
      const ta = document.createElement('textarea')
      ta.value = buildPlainText(result)
      ta.style.cssText = 'position:fixed;opacity:0'
      document.body.appendChild(ta)
      ta.select()
      document.execCommand('copy')
      document.body.removeChild(ta)
    }
    setCopyState('copied')
    setTimeout(() => setCopyState('idle'), 1700)
  }, [result])

  const handleReset = useCallback(() => {
    clearLoadTimers()
    setAppState('idle')
    setSubmitting(false)
    setErrorMsg('')
    setResult(null)
    setProgress(0)
  }, [clearLoadTimers])

  return (
    <div className="campaign-ideation">
      <AuroraBackground />
      <Header />

      <main className="shell">
        <section className="hero">
          <span className="eyebrow">Campaign Ideation</span>
          <h1>
            Turn product context into <span className="accent">7 campaign concepts</span>.
          </h1>
          <p>
            Share your offer, audience, and goal. We return ready-to-execute ideas across channels
            with clear first steps.
          </p>
        </section>

        <section className="panel">
          <div className="panel-topline">
            <span>campaign ideation engine</span>
            <span>{clock}</span>
          </div>

          {appState === 'idle' && (
            <form className="ci-form" onSubmit={handleSubmit} noValidate>
              <Field
                label="Product / Offer *"
                value={product}
                placeholder="What you sell, for whom, and why it matters."
                onChange={setProduct}
                disabled={submitting}
                minChars={20}
                error={prodError}
                rows={4}
              />
              <Field
                label="Audience *"
                value={audience}
                placeholder="ICP, role, company stage, and pain points."
                onChange={setAudience}
                disabled={submitting}
                minChars={20}
                error={audError}
                rows={4}
              />
              <Field
                label="Current Motion (optional)"
                value={currentMotion}
                placeholder="How you currently go to market."
                onChange={setCurrentMotion}
                disabled={submitting}
                rows={3}
              />
              <div className="ci-chip-row">
                {MOTION_CHIPS.map((chip) => (
                  <button
                    key={chip}
                    type="button"
                    className={`ci-chip${selectedMotion === chip ? 'active' : ''}`}
                    onClick={() => {
                      setSelectedMotion(chip)
                      setCurrentMotion(chip)
                    }}
                  >
                    {chip}
                  </button>
                ))}
              </div>
              <Field
                label="Primary Goal (optional)"
                value={goal}
                placeholder="What outcome matters most in this cycle."
                onChange={setGoal}
                disabled={submitting}
                rows={3}
              />

              <div className="ci-actions">
                <button className="ci-submit" type="submit" disabled={submitting}>
                  Generate ideas
                </button>
                <button className="ci-ghost" type="button" onClick={handleTrySample}>
                  Try a sample
                </button>
              </div>
            </form>
          )}

          {appState === 'loading' && (
            <section className="ci-loading">
              <div className="ci-progress-track">
                <div className="ci-progress-bar" style={{ width: `${progress}%` }} />
              </div>
              <div className="ci-progress-label">{Math.floor(progress)}%</div>
              <div className="ci-stage-list">
                {STAGES.map((stage, idx) => (
                  <div key={stage} className={`ci-stage${idx <= activeStage ? 'on' : ''}`}>
                    <span>{String(idx + 1).padStart(2, '0')}</span>
                    <strong>{stage}</strong>
                  </div>
                ))}
              </div>
            </section>
          )}

          {appState === 'result' && result && (
            <section className="ci-result-wrap">
              <EmailGate miniAppSlug="campaign-ideation" pattern="upfront" initialInput={leadInput}>
                {({ submitToApi }) => (
                  <>
                    <SubmitOnce submit={submitToApi} input={leadInput} output={result} />
                    <div className="ci-report-head">
                      <span className="ci-report-title">Campaign ideas ready</span>
                      <span className="ci-report-ts">{resultTs}</span>
                    </div>

                    <article className="ci-positioning">
                      <span>{'// Positioning summary'}</span>
                      <p>{result.summary.positioning}</p>
                    </article>

                    <div className="ci-grid">
                      {result.ideas.map((idea, index) => (
                        <IdeaCard key={index} idea={idea} index={index} />
                      ))}
                    </div>

                    <div className="ci-footer-actions">
                      <button
                        className={`ci-copy-all${copyState === 'copied' ? 'copied' : ''}`}
                        type="button"
                        onClick={handleCopyAll}
                      >
                        {copyState === 'copied' ? 'Copied' : 'Copy all'}
                      </button>
                      <button className="ci-ghost" type="button" onClick={() => window.print()}>
                        Print
                      </button>
                    </div>
                  </>
                )}
              </EmailGate>
            </section>
          )}

          {appState === 'error' && (
            <section className="ci-error">
              <h2>Couldn&apos;t generate ideas</h2>
              <p>{errorMsg}</p>
              <button className="ci-submit" type="button" onClick={handleReset}>
                Try again
              </button>
            </section>
          )}
        </section>

        {appState === 'result' && (
          <section className="ci-result-footer">
            <button type="button" className="ci-submit" onClick={handleReset}>
              Generate again
            </button>
            <button type="button" className="ci-ghost" onClick={handleCopyAll}>
              Copy all
            </button>
            <a
              className="ci-ghost"
              href="https://www.system7.ai/contact"
              target="_blank"
              rel="noreferrer"
            >
              Book a call
            </a>
            <a className="ci-ghost" href="/mini-apps/roi-calculator">
              Open ROI calculator
            </a>
          </section>
        )}

        <HowItWorks
          title={
            <>
              From context to campaigns in <span className="accent">minutes</span>
            </>
          }
          subtitle="Four quick steps from inputs to campaign plan."
          steps={HIW_STEPS}
        />
      </main>

      <Footer />
      <PageScripts />
    </div>
  )
}
