'use client'

import type { RadarResult, Signal } from '@/app/api/mini-apps/outbound-radar/route'
import '../page-styles.css'

export type OutboundRadarInput = { company?: string; domain?: string }
export type OutboundRadarOutput = RadarResult

type Props = {
  input: OutboundRadarInput
  output: OutboundRadarOutput
  /**
   * When true, render only the inner result body (head + scores + outreach
   * angle + signals) without the surrounding `.outbound-radar /
   * .panel-wrap / .panel / .panel-body / .or-state` wrappers or the
   * `.result-footer`. The inline mini-app page provides those itself and
   * keeps its own export buttons. The standalone `/results/[id]` route
   * uses the default (full) render.
   */
  bare?: boolean
  /**
   * Override the timestamp label on the result head. The inline page
   * passes a formatted timestamp like `REPORT · 2026-06-10 · 14:32 UTC`.
   */
  tsLabel?: string
}

const SIGNAL_ICONS: Record<string, string> = {
  hiring: '👥',
  funding: '💰',
  expansion: '🌍',
  tech: '⚙️',
  news: '📡',
  leadership: '🎯',
}

export function intentClass(score: number): string {
  if (score >= 7) return 'high'
  if (score >= 4) return 'medium'
  return 'low'
}

export function intentDelta(score: number): string {
  if (score >= 7) return 'strong buy signal detected'
  if (score >= 4) return 'moderate activity: worth watching'
  return 'low signal: poor timing'
}

export function urgencyDelta(u: string): string {
  if (u === 'high') return 'reach out this week'
  if (u === 'medium') return 'queue for next sprint'
  return 'monitor for 30d'
}

export function buildOutboundRadarPlainText(r: RadarResult): string {
  return [
    `Outbound Trigger Radar — ${r.company} (${r.domain})`,
    '='.repeat(60),
    '',
    `Intent Score  : ${r.intent_score}/10`,
    `Urgency       : ${r.urgency.toUpperCase()}`,
    '',
    '// OUTREACH ANGLE',
    r.outreach_angle,
    `Best persona  : ${r.best_persona}`,
    '',
    '// SIGNALS DETECTED',
    ...r.signals.map((s) => `  [${s.strength.toUpperCase()}] ${s.label}\n  ${s.detail}`),
    '',
    `Tokens: ${(r.tokens_in + r.tokens_out).toLocaleString()} (${r.tokens_in.toLocaleString()} in / ${r.tokens_out.toLocaleString()} out)`,
    'Generated by S7 Labs Outbound Trigger Radar',
  ].join('\n')
}

function SignalCard({ signal }: { signal: Signal }) {
  return (
    <div className={`signal${signal.strength === 'strong' ? 'strong' : ''}`}>
      <div className="signal-icon">{SIGNAL_ICONS[signal.type] ?? '📌'}</div>
      <div className="signal-body">
        <div className="signal-label">{signal.label}</div>
        <div className="signal-detail">{signal.detail}</div>
      </div>
      <span className={`signal-strength ${signal.strength}`}>{signal.strength}</span>
    </div>
  )
}

function ResultBody({
  output,
  tsLabel = 'REPORT',
}: {
  output: OutboundRadarOutput
  tsLabel?: string
}) {
  return (
    <>
      <div className="result-head">
        <span className="title">Radar complete: {output.company}</span>
        <span className="ts-label">{tsLabel}</span>
      </div>

      <div className="score-row">
        <div className={`score-card ${intentClass(output.intent_score)}`}>
          <div className="sc-label">Intent Score</div>
          <div className="sc-value">
            <span className="sc-big">{output.intent_score}</span>
            <span className="sc-small">/10</span>
          </div>
          <div className="sc-delta">{intentDelta(output.intent_score)}</div>
        </div>
        <div className={`score-card ${output.urgency}`}>
          <div className="sc-label">Urgency</div>
          <div className="sc-value">
            <span className="sc-big" style={{ fontSize: '32px', textTransform: 'capitalize' }}>
              {output.urgency}
            </span>
          </div>
          <div className="sc-delta">{urgencyDelta(output.urgency)}</div>
        </div>
        <div className="score-card medium">
          <div className="sc-label">Signals</div>
          <div className="sc-value">
            <span className="sc-big">{output.signals.length}</span>
          </div>
          <div className="sc-delta">
            {output.signals.filter((s) => s.strength === 'strong').length} strong detected
          </div>
        </div>
      </div>

      <div className="angle-block">
        <div className="angle-eyebrow">{'// Outreach angle'}</div>
        <p className="angle-text">{output.outreach_angle}</p>
        <div className="persona-row">
          Best first contact: <strong>{output.best_persona}</strong>
        </div>
      </div>

      <div className="section-header">
        <span>{'// Buy signals detected'}</span>
        <span className="count">{output.signals.length} found</span>
      </div>
      <div className="signals">
        {output.signals.map((s, i) => (
          <SignalCard key={i} signal={s} />
        ))}
      </div>
    </>
  )
}

export function OutboundRadarResult({ input, output, bare = false, tsLabel }: Props) {
  void input
  if (bare) {
    return <ResultBody output={output} tsLabel={tsLabel} />
  }
  return (
    <div className="outbound-radar">
      <div className="panel-wrap">
        <div className="panel">
          <div className="panel-body">
            <section className="or-state active">
              <ResultBody output={output} tsLabel={tsLabel} />

              <div className="result-footer">
                <span className="url-pill">
                  <span>{output.domain}</span>
                </span>
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>
  )
}
