'use client'

import { clsx } from 'clsx'

import type { BrandScore, Provider, ScanFree, ScanGated } from '@/lib/mini-apps/sov-types'
import '../page-styles.css'

export type ShareOfVoiceInput = { your_domain?: string; competitors?: string[] }
export type ShareOfVoiceOutput = {
  free: ScanFree
  gated?: ScanGated | null
}

type Props = {
  input: ShareOfVoiceInput
  output: ShareOfVoiceOutput
  /**
   * When true, render only the inner result body (shareable block, gated
   * sections) without surrounding panel wrappers / corner brackets /
   * result-footer. The inline mini-app page consumes the component in bare
   * mode so its own export buttons remain at page level. The standalone
   * `/results/[id]` route uses the default (full) render.
   */
  bare?: boolean
}

export const PROVIDER_LABELS: Record<Provider, string> = {
  claude: 'Claude',
  chatgpt: 'ChatGPT',
  perplexity: 'Perplexity',
}

const ALL_PROVIDERS: Provider[] = ['claude', 'chatgpt', 'perplexity']

export function buildHeadlineLine(free: ScanFree): string {
  const h = free.headline
  if (h.your_rank === 1) {
    const chaser =
      free.scores.find((s) => !s.is_you && s.rank === 2) ?? free.scores.find((s) => !s.is_you)
    const chaserName = chaser?.name ?? h.top_competitor
    const chaserShare = chaser?.share_of_voice ?? h.top_competitor_share
    return `You lead at ${h.your_share}% of answers. ${chaserName} is chasing at ${chaserShare}%.`
  }
  return `You appear in ${h.your_share}% of answers. ${h.top_competitor} appears in ${h.top_competitor_share}%.`
}

export function buildShareOfVoicePlainText(free: ScanFree, gated: ScanGated | null): string {
  const lines = [
    `AI Share of Voice — ${free.your_brand} (${free.your_domain})`,
    free.category,
    '='.repeat(60),
    '',
    buildHeadlineLine(free),
    '',
    '// SCOREBOARD',
    ...free.scores.map(
      (s) => `${s.rank}. ${s.name}${s.is_you ? ' (you)' : ''}: ${s.share_of_voice}%`
    ),
    '',
    '// BY PROVIDER',
    ...free.providers_used.map((p) => {
      const you = free.scores.find((s) => s.is_you)
      const row = you?.by_provider.find((b) => b.provider === p)
      return `  ${PROVIDER_LABELS[p]}: ${row?.share ?? 0}%`
    }),
  ]
  if (gated) {
    lines.push('', '// QUESTIONS')
    for (const q of gated.questions) {
      lines.push('', q.question)
      for (const row of q.by_provider) {
        lines.push(
          `  [${PROVIDER_LABELS[row.provider]}] mentioned: ${row.brands_mentioned.join(', ') || 'none'}`
        )
        lines.push(`  ${row.answer_excerpt}`)
      }
    }
    lines.push('', '// HOW TO CLOSE THE GAP')
    gated.recommendations.forEach((r, i) => lines.push(`  ${i + 1}. ${r}`))
    lines.push('', `Tokens: ${(gated.tokens_in + gated.tokens_out).toLocaleString()}`)
  }
  lines.push('', 'Generated by S7 Labs AI Share of Voice Scorer')
  return lines.join('\n')
}

function SovScoreCard({
  score,
  totalBrands,
  yourRank,
}: {
  score: BrandScore
  totalBrands: number
  yourRank: number
}) {
  // Bar width is the absolute share-of-voice % (clamped 0–100), so 13% reads as
  // a ~13% bar, not a full one. Non-zero shares get a small floor for visibility.
  const fillPct = score.share_of_voice <= 0 ? 0 : Math.min(100, Math.max(4, score.share_of_voice))
  const isChaser = yourRank === 1 && score.rank === 2
  const cardClass = [
    'sov-score-card',
    score.is_you && 'is-you',
    score.rank === 1 && !score.is_you && 'is-leader',
    isChaser && 'is-chaser',
  ]
    .filter(Boolean)
    .join(' ')

  const metaParts: string[] = []
  if (score.is_you) metaParts.push(`rank ${score.rank} of ${totalBrands}`)
  if (isChaser) metaParts.push('closest rival')
  if (score.rank === 1 && !score.is_you) metaParts.push('leader')

  return (
    <article className={cardClass}>
      <div className="sov-score-top">
        <span className="sov-score-rank">{String(score.rank).padStart(2, '0')}</span>
        <div className="sov-score-info">
          <div className="sov-score-name-row">
            <span className="sov-score-name">{score.name}</span>
            {score.is_you && <span className="sov-score-you">you</span>}
          </div>
          {metaParts.length > 0 && <div className="sov-score-meta">{metaParts.join(' · ')}</div>}
        </div>
        <div className="sov-score-pct-col">
          <span className="sov-score-pct">{score.share_of_voice}</span>
          <span className="sov-score-pct-suffix">%</span>
        </div>
      </div>
      <div className="sov-meter" aria-hidden>
        <div className="sov-meter-fill" style={{ width: `${fillPct}%` }} />
      </div>
    </article>
  )
}

function ProviderCard({ provider, free }: { provider: Provider; free: ScanFree }) {
  const you = free.scores.find((s) => s.is_you)
  const row = you?.by_provider.find((b) => b.provider === provider)
  const available = free.providers_used.includes(provider)

  return (
    <div className={clsx('provider-card', { 'is-unavailable': !available })}>
      <div className="provider-card-label">{PROVIDER_LABELS[provider]}</div>
      {available && row ? (
        <>
          <div className="provider-card-share">{row.share}%</div>
          <div className="provider-card-sub">your share</div>
        </>
      ) : (
        <>
          <div className="provider-card-share">—</div>
          <span className="provider-unavailable-tag">not available</span>
        </>
      )}
    </div>
  )
}

function ResultBody({ free, gated }: { free: ScanFree; gated: ScanGated | null }) {
  const yourBrandName = free.your_brand

  return (
    <>
      <div className="shareable-block">
        <div className="one-liner-block">
          <p className="one-liner-text">&ldquo;{buildHeadlineLine(free)}&rdquo;</p>
          <div className="one-liner-meta">
            <span className="project-name">{free.your_domain}</span>
            <span className="type-pill">{free.category}</span>
          </div>
          <p className="estimate-note">
            Share of voice across {free.providers_used.length} AI provider
            {free.providers_used.length === 1 ? '' : 's'} · {free.questions_count} buying-intent
            questions.
          </p>
        </div>

        <div className="section-header">
          <span>{'// scoreboard'}</span>
          <span>{free.scores.length} brands</span>
        </div>
        <div className="sov-scoreboard">
          {free.scores.map((score) => (
            <SovScoreCard
              key={score.domain}
              score={score}
              totalBrands={free.scores.length}
              yourRank={free.headline.your_rank}
            />
          ))}
        </div>

        <div className="section-header">
          <span>{'// by provider'}</span>
        </div>
        <div className="provider-row">
          {ALL_PROVIDERS.map((p) => (
            <ProviderCard key={p} provider={p} free={free} />
          ))}
        </div>
        <p className="provider-footnote">
          {free.providers_used.length < 3
            ? `Scored across ${free.providers_used.map((p) => PROVIDER_LABELS[p]).join(' and ')} only. Unavailable providers excluded.`
            : 'Your share within each provider’s answers.'}
        </p>
      </div>

      {gated && (
        <>
          <div className="section-header">
            <span>{'// question breakdown'}</span>
          </div>
          {gated.questions.map((q) => (
            <div key={q.question} className="question-block">
              <div className="question-header">{q.question}</div>
              {q.by_provider.map((row) => {
                const hasYou = row.brands_mentioned.some(
                  (b) => b.toLowerCase() === yourBrandName.toLowerCase()
                )
                const hasCompetitor = row.brands_mentioned.some(
                  (b) => b.toLowerCase() !== yourBrandName.toLowerCase()
                )
                return (
                  <div
                    key={`${q.question}-${row.provider}`}
                    className={clsx('mention-row', {
                      'has-you': hasYou,
                      'missing-you': !hasYou,
                      'competitor-ahead': hasCompetitor && !hasYou,
                    })}
                  >
                    <div className="mention-provider">{PROVIDER_LABELS[row.provider]}</div>
                    <div className="mention-brands">
                      {row.brands_mentioned.length > 0 ? (
                        row.brands_mentioned.map((b) => (
                          <span
                            key={b}
                            className={
                              b.toLowerCase() === yourBrandName.toLowerCase()
                                ? 'brand-tag is-you'
                                : 'brand-tag'
                            }
                          >
                            {b}
                          </span>
                        ))
                      ) : (
                        <span className="brand-tag missing">You not mentioned</span>
                      )}
                    </div>
                    <p className="mention-excerpt">{row.answer_excerpt}</p>
                  </div>
                )
              })}
            </div>
          ))}

          <div className="gap-block">
            <div className="gap-eyebrow">{'// how to close the gap'}</div>
            <ol className="gap-list">
              {gated.recommendations.map((item, i) => (
                <li key={i} className="gap-row">
                  <span className="gap-number">{String(i + 1).padStart(2, '0')}</span>
                  <span className="gap-text">{item}</span>
                </li>
              ))}
            </ol>
          </div>
        </>
      )}
    </>
  )
}

export function ShareOfVoiceResult({ input, output, bare = false }: Props) {
  void input
  const { free, gated = null } = output
  if (!free) {
    return <p>No data available for this submission.</p>
  }

  if (bare) {
    return <ResultBody free={free} gated={gated ?? null} />
  }

  return (
    <div className="share-of-voice">
      <div className="panel-wrap panel-wrap-wide">
        <div className="panel">
          <span className="corner tl" />
          <span className="corner tr" />
          <span className="corner bl" />
          <span className="corner br" />
          <div className="panel-body">
            <section className="sov-state active">
              <ResultBody free={free} gated={gated ?? null} />
            </section>
          </div>
        </div>
      </div>
    </div>
  )
}
