'use client'

import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react'
import { clsx } from 'clsx'
import './page-styles.css'

import { Footer } from '@/components/Footer'
import { Header } from '@/components/Header'
import { AuroraBackground } from '@/components/mini-apps/AuroraBackground'
import { HowItWorks, type HowItWorksStep } from '@/components/mini-apps/HowItWorks'
import { EMAIL_REGEX } from '@/lib/leads/disposable'

import type {
  ApiResponse,
  ProfileReviewResult,
  TopAction,
} from '@/app/api/mini-apps/linkedin-profile-reviewer/route'
import { PageScripts } from './PageScripts'

type AppState = 'idle' | 'loading' | 'result' | 'error'
type InputMode = 'url' | 'paste'

const STAGES = [
  {
    num: '01',
    title: 'Collecting profile content',
    logs: ['validating input', 'preparing source'],
  },
  {
    num: '02',
    title: 'Extracting core signals',
    logs: ['headline and about read', 'experience parsed'],
  },
  { num: '03', title: 'Scoring profile sections', logs: ['section scoring', 'consistency checks'] },
  { num: '04', title: 'Ranking top actions', logs: ['prioritizing fixes', 'review packaging'] },
]
const STAGE_MS = 4200

const HOW_IT_WORKS_STEPS: HowItWorksStep[] = [
  {
    title: 'Choose URL or paste mode',
    description:
      'Use a public LinkedIn profile URL, or paste the profile text directly when LinkedIn blocks scraping.',
    icon: (
      <svg
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.6"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <rect x="3" y="4" width="18" height="16" rx="2" />
        <path d="M3 9h18" />
        <path d="M8 14h8" />
      </svg>
    ),
  },
  {
    title: 'We evaluate six profile sections',
    description:
      'Headline, About, Experience, Skills, Recommendations, and Photo/Banner are reviewed with practical feedback.',
    icon: (
      <svg
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.6"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M3 7l9-4 9 4-9 4-9-4z" />
        <path d="M3 12l9 4 9-4" />
        <path d="M3 17l9 4 9-4" />
      </svg>
    ),
  },
  {
    title: 'AI scores profile clarity',
    description:
      'You get one score plus section-level verdicts so you can quickly spot what helps or hurts recruiter and buyer trust.',
    icon: (
      <svg
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.6"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <circle cx="12" cy="12" r="3" />
        <path d="M12 2v3M12 19v3M2 12h3M19 12h3" />
      </svg>
    ),
  },
  {
    title: 'Get five ranked improvements',
    description:
      'Top actions are prioritized by impact so you know exactly what to change first before updating your profile.',
    icon: (
      <svg
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.6"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M9 11l3 3 8-8" />
        <path d="M20 12v6a2 2 0 01-2 2H6a2 2 0 01-2-2V6a2 2 0 012-2h9" />
      </svg>
    ),
  },
]

function fmtTs(d: Date) {
  const pad = (n: number) => String(n).padStart(2, '0')
  return `REVIEW · ${d.getUTCFullYear()}-${pad(d.getUTCMonth() + 1)}-${pad(d.getUTCDate())} · ${pad(d.getUTCHours())}:${pad(d.getUTCMinutes())} UTC`
}

function impactClass(impact: TopAction['impact']) {
  if (impact === 'high') return 'high'
  if (impact === 'medium') return 'mid'
  return 'low'
}

function scoreClass(score: number) {
  if (score >= 80) return 'good'
  if (score >= 60) return 'mid'
  return 'bad'
}

function buildPlainText(result: ProfileReviewResult): string {
  return [
    'LinkedIn Profile Reviewer',
    '='.repeat(60),
    result.sourceUrl ? `Source: ${result.sourceUrl}` : 'Source: pasted profile text',
    `Score: ${result.score}/100`,
    '',
    result.summary,
    '',
    '// SECTION SCORES',
    ...result.sections.map((section) => {
      return `${section.name}: ${section.score}/100\n${section.verdict}\n${section.feedback}`
    }),
    '',
    '// TOP 5 ACTIONS',
    ...result.topActions.map(
      (action) =>
        `${action.rank}. [${action.impact.toUpperCase()}] ${action.action}\n   ${action.rationale}`
    ),
    '',
    `Tokens: ${(result.tokens_in + result.tokens_out).toLocaleString()} (${result.tokens_in.toLocaleString()} in / ${result.tokens_out.toLocaleString()} out)`,
    'Generated by S7 Labs LinkedIn Profile Reviewer',
  ].join('\n')
}

export default function LinkedInProfileReviewerPage() {
  const [appState, setAppState] = useState<AppState>('idle')
  const [mode, setMode] = useState<InputMode>('url')
  const [url, setUrl] = useState('')
  const [profileText, setProfileText] = useState('')
  const [inputError, setInputError] = useState<string | null>(null)
  const [shakeInput, setShakeInput] = useState(0)
  const [email, setEmail] = useState('')
  const [emailError, setEmailError] = useState<string | null>(null)
  const [shakeEmail, setShakeEmail] = useState(0)
  const [errorCode, setErrorCode] = useState<string | null>(null)
  const [errorMsg, setErrorMsg] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const [result, setResult] = useState<ProfileReviewResult | null>(null)
  const [resultTs, setResultTs] = useState('')
  const [copyState, setCopyState] = useState<'idle' | 'done'>('idle')
  const [activeStage, setActiveStage] = useState(-1)
  const [doneStages, setDoneStages] = useState<number[]>([])
  const [stageLogs, setStageLogs] = useState<string[]>(['', '', '', ''])
  const [progressPct, setProgressPct] = useState(0)
  const [loadingPct, setLoadingPct] = useState('0%')
  const [latency, setLatency] = useState('—')
  const [clock, setClock] = useState('—')

  const urlInputRef = useRef<HTMLInputElement | null>(null)
  const textAreaRef = useRef<HTMLTextAreaElement | null>(null)
  const timersRef = useRef<ReturnType<typeof setTimeout>[]>([])
  const rafRef = useRef<number | null>(null)
  const runStartRef = useRef(0)

  useEffect(() => {
    const tick = () => {
      const d = new Date()
      const pad = (n: number) => String(n).padStart(2, '0')
      setClock(`${pad(d.getUTCHours())}:${pad(d.getUTCMinutes())}:${pad(d.getUTCSeconds())}Z`)
    }
    tick()
    const id = setInterval(tick, 1000)
    return () => clearInterval(id)
  }, [])

  useEffect(() => {
    if (appState !== 'idle') return
    const t = setTimeout(() => {
      if (mode === 'url') {
        urlInputRef.current?.focus()
      } else {
        textAreaRef.current?.focus()
      }
    }, 150)
    return () => clearTimeout(t)
  }, [appState, mode])

  const clearTimers = useCallback(() => {
    timersRef.current.forEach((timer) => clearTimeout(timer))
    timersRef.current = []
    if (rafRef.current !== null) {
      cancelAnimationFrame(rafRef.current)
      rafRef.current = null
    }
  }, [])

  useEffect(() => () => clearTimers(), [clearTimers])

  const startLoadingAnimation = useCallback(() => {
    clearTimers()
    setActiveStage(0)
    setDoneStages([])
    setStageLogs(['', '', '', ''])
    setProgressPct(0)
    setLoadingPct('0%')
    setLatency('0.0s')
    runStartRef.current = performance.now()

    const total = STAGES.length * STAGE_MS
    const tick = (now: number) => {
      const pct = Math.min(98, ((now - runStartRef.current) / total) * 100)
      setProgressPct(pct)
      setLoadingPct(`${Math.floor(pct)}%`)
      setLatency(`${((now - runStartRef.current) / 1000).toFixed(1)}s`)
      if (pct < 98) {
        rafRef.current = requestAnimationFrame(tick)
      }
    }
    rafRef.current = requestAnimationFrame(tick)

    STAGES.forEach((stage, index) => {
      timersRef.current.push(
        setTimeout(() => {
          setActiveStage(index)
          setStageLogs((prev) => {
            const next = [...prev]
            next[index] = stage.logs[0] ?? ''
            return next
          })
        }, index * STAGE_MS)
      )
      timersRef.current.push(
        setTimeout(
          () => {
            setDoneStages((prev) => [...prev, index])
            setStageLogs((prev) => {
              const next = [...prev]
              next[index] = stage.logs[stage.logs.length - 1] ?? ''
              return next
            })
          },
          (index + 1) * STAGE_MS
        )
      )
    })
  }, [clearTimers])

  const handleCopy = useCallback(async () => {
    if (!result) return
    const text = buildPlainText(result)
    try {
      await navigator.clipboard.writeText(text)
    } catch {
      const ta = document.createElement('textarea')
      ta.value = text
      ta.style.cssText = 'position:fixed;opacity:0'
      document.body.appendChild(ta)
      ta.select()
      document.execCommand('copy')
      document.body.removeChild(ta)
    }
    setCopyState('done')
    setTimeout(() => setCopyState('idle'), 1800)
  }, [result])

  const resetToInput = useCallback(() => {
    clearTimers()
    setAppState('idle')
    setInputError(null)
    setErrorCode(null)
    setErrorMsg('')
    setSubmitting(false)
    setResult(null)
    setProgressPct(0)
    setLoadingPct('0%')
    setLatency('—')
    setEmailError(null)
  }, [clearTimers])

  const handleSubmit = useCallback(
    async (e: FormEvent) => {
      e.preventDefault()
      if (submitting) return

      const trimmedUrl = url.trim()
      const trimmedText = profileText.trim()
      let valid = true

      if (mode === 'url') {
        if (!trimmedUrl) {
          setInputError('Paste a LinkedIn profile URL to continue.')
          setShakeInput((k) => k + 1)
          valid = false
        }
      } else if (trimmedText.length < 100 || trimmedText.length > 8000) {
        setInputError('Paste between 100 and 8000 characters of profile text.')
        setShakeInput((k) => k + 1)
        valid = false
      }

      const emailClean = email.trim().toLowerCase()
      if (!emailClean) {
        setEmailError('Please enter your work email.')
        setShakeEmail((k) => k + 1)
        valid = false
      } else if (!EMAIL_REGEX.test(emailClean)) {
        setEmailError('Please enter a valid email.')
        setShakeEmail((k) => k + 1)
        valid = false
      }
      if (!valid) return

      setInputError(null)
      setEmailError(null)
      setErrorCode(null)
      setErrorMsg('')
      setSubmitting(true)
      setResult(null)

      let submissionId: string | null = null
      try {
        const leadRes = await fetch('/api/leads/submit', {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({
            email: emailClean,
            miniAppSlug: 'linkedin-profile-reviewer',
            input: {
              mode,
              url: trimmedUrl || undefined,
              profileText: trimmedText || undefined,
            },
          }),
        })
        const leadJson = (await leadRes.json()) as {
          ok: boolean
          submissionId?: string
          error?: string
        }
        if (!leadRes.ok || !leadJson.ok || !leadJson.submissionId) {
          setEmailError(leadJson.error || "Couldn't save your info. Try again.")
          setShakeEmail((k) => k + 1)
          setSubmitting(false)
          return
        }
        submissionId = leadJson.submissionId
      } catch {
        setEmailError("Couldn't save your info. Try again.")
        setShakeEmail((k) => k + 1)
        setSubmitting(false)
        return
      }

      setAppState('loading')
      startLoadingAnimation()

      try {
        const res = await fetch('/api/mini-apps/linkedin-profile-reviewer', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            mode,
            url: trimmedUrl || undefined,
            profileText: trimmedText || undefined,
          }),
        })
        const data = (await res.json()) as ApiResponse

        clearTimers()
        const elapsed = ((performance.now() - runStartRef.current) / 1000).toFixed(1)
        setLatency(`${elapsed}s`)
        setProgressPct(100)
        setLoadingPct('100%')

        if (data.ok) {
          setDoneStages([0, 1, 2, 3])
          setResult(data.data)
          setResultTs(fmtTs(new Date()))
          setAppState('result')

          fetch('/api/leads/complete', {
            method: 'POST',
            headers: { 'content-type': 'application/json' },
            body: JSON.stringify({
              submissionId,
              output: data.data,
              ...(data.cost ? { cost: data.cost } : {}),
            }),
          }).catch((err) => console.error('[linkedin-profile-reviewer] leads/complete', err))
        } else {
          setErrorCode(data.code ?? null)
          setErrorMsg(data.message)
          setAppState('error')
        }
      } catch {
        clearTimers()
        setErrorCode(null)
        setErrorMsg('Network error. Please check your connection and try again.')
        setAppState('error')
      } finally {
        setSubmitting(false)
      }
    },
    [mode, profileText, email, startLoadingAnimation, submitting, url, clearTimers]
  )

  return (
    <div className="linkedin-profile-reviewer">
      <AuroraBackground />
      <Header />

      <main className="shell">
        <section className="hero">
          <span className="eyebrow">LinkedIn Profile Reviewer</span>
          <h1>
            Improve your profile with <span className="accent">ranked actions</span>.
          </h1>
          <p>
            Get a structured review across six sections and five priority fixes so your profile
            reads clearer to prospects, recruiters, and partners.
          </p>
        </section>

        <div className="panel-wrap">
          <div className="panel">
            <span className="corner tl" aria-hidden="true" />
            <span className="corner tr" aria-hidden="true" />
            <span className="corner bl" aria-hidden="true" />
            <span className="corner br" aria-hidden="true" />
            {appState !== 'idle' && (
              <div className="panel-readouts">
                <div className="pr-left">
                  <span className="stat-key">mode</span>
                  <span className="stat-val">{mode}</span>
                </div>
                <div className="pr-right">
                  <span className="stat-key hide-sm">lat</span>
                  <span className="stat-val hide-sm">{latency}</span>
                  <span className="pr-sep hide-sm" />
                  <span className="stat-key">ts</span>
                  <span className="stat-val">{clock}</span>
                </div>
              </div>
            )}

            <div className="panel-body">
              <section className={clsx('lpr-state', { active: appState === 'idle' })}>
                <div className="mode-toggle">
                  <button
                    type="button"
                    className={clsx('mode-btn', { active: mode === 'url' })}
                    onClick={() => {
                      setMode('url')
                      setInputError(null)
                    }}
                  >
                    LinkedIn URL
                  </button>
                  <button
                    type="button"
                    className={clsx('mode-btn', { active: mode === 'paste' })}
                    onClick={() => {
                      setMode('paste')
                      setInputError(null)
                    }}
                  >
                    Paste text
                  </button>
                </div>

                <form className="pd-form" noValidate onSubmit={handleSubmit}>
                  {mode === 'url' ? (
                    <>
                      <div className="idle-label">
                        Profile URL <span className="required-mark">*</span>
                      </div>
                      <div
                        key={`u-${shakeInput}`}
                        className={clsx('pd-input-box', { error: inputError })}
                      >
                        <input
                          id="linkedin-url"
                          ref={urlInputRef}
                          type="url"
                          placeholder="https://www.linkedin.com/in/username"
                          spellCheck={false}
                          value={url}
                          disabled={submitting}
                          onChange={(e) => {
                            setUrl(e.target.value)
                            if (inputError) setInputError(null)
                          }}
                        />
                      </div>
                      <div className={clsx('pd-helper', { error: inputError })}>
                        {inputError ?? 'Only individual profile URLs are supported.'}
                      </div>
                    </>
                  ) : (
                    <>
                      <div className="idle-label">
                        Profile text <span className="required-mark">*</span>
                      </div>
                      <div
                        key={`t-${shakeInput}`}
                        className={clsx('pd-input-box textarea-box', { error: inputError })}
                      >
                        <textarea
                          id="profile-text"
                          ref={textAreaRef}
                          placeholder="Paste headline, about, experience, skills, and recommendations here..."
                          value={profileText}
                          disabled={submitting}
                          onChange={(e) => {
                            setProfileText(e.target.value)
                            if (inputError) setInputError(null)
                          }}
                        />
                      </div>
                      <div className={clsx('pd-helper', { error: inputError })}>
                        {inputError ?? `${profileText.length} chars (100-8000)`}
                      </div>
                    </>
                  )}

                  <div className="idle-label">
                    Work email <span className="required-mark">*</span>
                  </div>
                  <div
                    key={`e-${shakeEmail}`}
                    className={clsx('pd-input-box', { error: emailError })}
                  >
                    <input
                      id="work-email"
                      type="email"
                      inputMode="email"
                      autoComplete="email"
                      placeholder="you@company.com"
                      value={email}
                      disabled={submitting}
                      onChange={(e) => {
                        setEmail(e.target.value)
                        if (emailError) setEmailError(null)
                      }}
                    />
                  </div>
                  <div className={clsx('pd-helper', { error: emailError })}>
                    {emailError ?? 'We send the report to your work email. No spam.'}
                  </div>
                  <div className="pd-submit-row">
                    <button type="submit" className="pd-submit-btn" disabled={submitting}>
                      Review profile
                      <svg
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        strokeWidth="2.4"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      >
                        <path d="M5 12h14" />
                        <path d="M13 5l7 7-7 7" />
                      </svg>
                    </button>
                  </div>
                </form>
              </section>

              <section className={clsx('lpr-state', { active: appState === 'loading' })}>
                <div className="progress-track">
                  <div className="progress-bar" style={{ width: `${progressPct}%` }} />
                </div>
                <div className="loading-header">
                  <span>Analyzing profile</span>
                  <span>{loadingPct}</span>
                </div>
                <div className="stages">
                  {STAGES.map((stage, i) => {
                    const active = activeStage === i && !doneStages.includes(i)
                    const done = doneStages.includes(i)
                    return (
                      <div key={stage.num} className={clsx('stage', { active, done })}>
                        <div className="stage-row">
                          <span>{stage.num}</span>
                          <span>{stage.title}</span>
                        </div>
                        <div className="stage-log">{stageLogs[i]}</div>
                      </div>
                    )
                  })}
                </div>
              </section>

              <section className={clsx('lpr-state', { active: appState === 'result' })}>
                {result && (
                  <>
                    <div className="result-head">
                      <span className="ts">{resultTs}</span>
                      <span className={clsx('score-pill', scoreClass(result.score))}>
                        Score {result.score}/100
                      </span>
                    </div>
                    <p className="result-summary">{result.summary}</p>

                    <div className="section-grid">
                      {result.sections.map((section) => (
                        <article key={section.name} className="section-card">
                          <div className="section-row">
                            <span className="section-name">{section.name}</span>
                            <span className={clsx('section-score', scoreClass(section.score))}>
                              {section.score}
                            </span>
                          </div>
                          <p className="section-verdict">{section.verdict}</p>
                          <p className="section-feedback">{section.feedback}</p>
                        </article>
                      ))}
                    </div>

                    <div className="actions-block">
                      <div className="actions-header">
                        <span>{'// Top 5 actions'}</span>
                        <span className="actions-sub">ranked by impact</span>
                      </div>
                      <div className="actions-list">
                        {result.topActions.map((item) => (
                          <article key={item.rank} className="action-card">
                            <div className="action-row">
                              <span className="action-rank">0{item.rank}</span>
                              <span className={clsx('impact-chip', impactClass(item.impact))}>
                                {item.impact}
                              </span>
                            </div>
                            <h3>{item.action}</h3>
                            <p>{item.rationale}</p>
                          </article>
                        ))}
                      </div>
                    </div>

                    <div className="result-footer">
                      <button type="button" className="ghost-btn" onClick={resetToInput}>
                        Review another
                      </button>
                      <button
                        type="button"
                        className={clsx('ghost-btn', { done: copyState === 'done' })}
                        onClick={handleCopy}
                      >
                        {copyState === 'done' ? 'Copied' : 'Copy review'}
                      </button>
                      <a
                        className="primary-link"
                        href="https://www.system7.ai/contact"
                        target="_blank"
                        rel="noreferrer"
                      >
                        Book a call
                      </a>
                    </div>
                  </>
                )}
              </section>

              <section
                className={clsx('lpr-state', 'error-state', { active: appState === 'error' })}
              >
                <h2>Review failed</h2>
                <p>{errorMsg}</p>
                <div className="error-actions">
                  <button type="button" className="ghost-btn" onClick={resetToInput}>
                    Try again
                  </button>
                  {errorCode === 'SCRAPE_BLOCKED' && (
                    <button
                      type="button"
                      className="primary-btn"
                      onClick={() => {
                        setMode('paste')
                        setAppState('idle')
                        setInputError(null)
                      }}
                    >
                      Switch to paste mode
                    </button>
                  )}
                </div>
              </section>
            </div>
          </div>
        </div>

        <HowItWorks
          title={
            <>
              From profile to <span className="accent">clear next steps</span>
            </>
          }
          subtitle="Four steps from input to a ranked LinkedIn profile improvement plan."
          steps={HOW_IT_WORKS_STEPS}
        />
      </main>

      <Footer />
      <PageScripts />
    </div>
  )
}
