'use client'

import type { ReactNode } from 'react'

import type { FieldIssue, SanityResult } from '@/app/api/mini-apps/crm-sanity/route'
import '../page-styles.css'

export type CrmSanityInput = { record?: string; record_text?: string }
export type CrmSanityOutput = SanityResult

type Tokens = { in: number; out: number }

type Props = {
  input: CrmSanityInput
  output: CrmSanityOutput
  /**
   * When true, render only the inner result body (head + score row + summary
   * + cleaned record + issues + clean fields + duplicate risk block) without
   * the surrounding `.crm-sanity / .panel-wrap / .panel / .panel-body /
   * .cs-state` wrappers or the `.result-footer`. The inline mini-app page
   * provides those itself and keeps its own export buttons + interactive
   * "copy cleaned record" button in the footer / cleaned block, so it
   * consumes the component in bare mode. The standalone `/results/[id]`
   * route uses the default (full) render with a pure cleaned-record block.
   */
  bare?: boolean
  /**
   * Override the `REPORT` label on the result head. The inline mini-app
   * page passes a formatted timestamp like
   * `REPORT · 2026-06-10 · 14:32 UTC`.
   */
  tsLabel?: string
  /**
   * Optional token usage for the footer pill. Only the inline (full) render
   * uses the footer; bare mode ignores this.
   */
  tokens?: Tokens | null
  /**
   * Optional render slot for the cleaned-record block. The inline page
   * passes its own interactive `CleanedRecordBlock` (with a copy button);
   * standalone falls back to a pure block without a copy button.
   */
  cleanedSlot?: ReactNode
}

export const FORMAT_LABEL: Record<string, string> = {
  keyvalue: 'key: value',
  csv: 'CSV',
  json: 'JSON',
  freetext: 'free text',
}

export function scoreClass(score: number): string {
  if (score >= 75) return 'good'
  if (score >= 45) return 'mid'
  return 'bad'
}

export function gradeLabel(grade: string): string {
  const map: Record<string, string> = {
    A: 'excellent',
    B: 'good',
    C: 'needs work',
    D: 'poor',
    F: 'critical',
  }
  return map[grade] ?? ''
}

export function buildCrmSanityPlainText(r: SanityResult): string {
  return [
    `CRM Field Sanity Check`,
    '='.repeat(60),
    '',
    `Record type   : ${r.record_type}`,
    `Quality score : ${r.quality_score}/100 (Grade ${r.grade})`,
    `Duplicate risk: ${r.duplicate_risk.toUpperCase()}`,
    '',
    '// SUMMARY',
    r.summary,
    '',
    `// ISSUES (${r.issues.length})`,
    ...r.issues.map(
      (i) => `  [${i.severity.toUpperCase()}] ${i.field}: ${i.issue}\n  Fix: ${i.fix}`
    ),
    '',
    `// CLEAN FIELDS`,
    r.clean_fields.join(', '),
    '',
    `// DUPLICATE RISK`,
    r.duplicate_reason,
    '',
    `// CLEANED RECORD (${r.input_format})`,
    r.cleaned_record,
    '',
    `Tokens: ${(r.tokens_in + r.tokens_out).toLocaleString()} (${r.tokens_in.toLocaleString()} in / ${r.tokens_out.toLocaleString()} out)`,
    'Generated by S7 Labs CRM Field Sanity Check',
  ].join('\n')
}

export function IssueCard({ issue }: { issue: FieldIssue }) {
  return (
    <div className={`issue-card ${issue.severity}`}>
      <div className="issue-header">
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px', flexWrap: 'wrap' }}>
          <span className="issue-field">{issue.field}</span>
          <span className="issue-value">{issue.value || 'empty'}</span>
        </div>
        <span className={`severity-badge ${issue.severity}`}>{issue.severity}</span>
      </div>
      <p className="issue-text">{issue.issue}</p>
      <div className="issue-fix">
        <span className="fix-label">Fix</span>
        <span className="fix-text">{issue.fix}</span>
      </div>
    </div>
  )
}

function StaticCleanedRecordBlock({ text, format }: { text: string; format: string }) {
  return (
    <div className="cleaned-block">
      <div className="cleaned-head">
        <div className="cleaned-head-left">
          <span className="cleaned-eyebrow">{'// Cleaned record'}</span>
          <span className="cleaned-format-pill">{FORMAT_LABEL[format] ?? format}</span>
        </div>
      </div>
      <pre className="cleaned-pre">{text}</pre>
      <div className="cleaned-foot">
        Drop-in ready. Paste this back into your CRM to apply every fix at once.
      </div>
    </div>
  )
}

function ResultBody({
  output,
  tsLabel = 'REPORT',
  cleanedSlot,
}: {
  output: CrmSanityOutput
  tsLabel?: string
  cleanedSlot?: ReactNode
}) {
  const criticalCount = output.issues.filter((i) => i.severity === 'critical').length
  const warningCount = output.issues.filter((i) => i.severity === 'warning').length
  return (
    <>
      <div className="result-head">
        <span className="title">Sanity check complete: {output.record_type}</span>
        <span className="ts-label">{tsLabel}</span>
      </div>

      <div className="score-row">
        <div className={`score-card ${scoreClass(output.quality_score)}`}>
          <div className="sc-label">Quality Score</div>
          <div className="sc-value">
            <span className="sc-big">{output.quality_score}</span>
            <span className="sc-small">/100</span>
          </div>
          <div className="sc-delta">
            Grade {output.grade}: {gradeLabel(output.grade)}
          </div>
        </div>
        <div
          className={`score-card ${criticalCount > 0 ? 'bad' : warningCount > 0 ? 'mid' : 'good'}`}
        >
          <div className="sc-label">Issues</div>
          <div className="sc-value">
            <span className="sc-big">{output.issues.length}</span>
          </div>
          <div className="sc-delta">
            {criticalCount} critical · {warningCount} warnings
          </div>
        </div>
        <div
          className={`score-card ${output.duplicate_risk === 'high' ? 'bad' : output.duplicate_risk === 'medium' ? 'mid' : 'good'}`}
        >
          <div className="sc-label">Dup Risk</div>
          <div className="sc-value">
            <span className="sc-big" style={{ fontSize: '28px', textTransform: 'capitalize' }}>
              {output.duplicate_risk}
            </span>
          </div>
          <div className="sc-delta">{output.clean_fields.length} clean fields</div>
        </div>
      </div>

      <div className="summary-block">
        <div className="summary-eyebrow">{'// Summary'}</div>
        <p className="summary-text">{output.summary}</p>
      </div>

      {output.cleaned_record &&
        (cleanedSlot ?? (
          <StaticCleanedRecordBlock text={output.cleaned_record} format={output.input_format} />
        ))}

      {output.issues.length > 0 && (
        <>
          <div className="section-header">
            <span>{'// Issues detected'}</span>
            <span>{output.issues.length} total</span>
          </div>
          <div className="issues">
            {output.issues.map((issue, i) => (
              <IssueCard key={i} issue={issue} />
            ))}
          </div>
        </>
      )}

      {output.clean_fields.length > 0 && (
        <>
          <div className="section-header">
            <span>{'// Clean fields'}</span>
          </div>
          <div className="clean-fields">
            {output.clean_fields.map((f) => (
              <span key={f} className="clean-tag">
                {f}
              </span>
            ))}
          </div>
        </>
      )}

      <div className="section-header">
        <span>{'// Duplicate risk'}</span>
      </div>
      <div className={`dup-block dup-${output.duplicate_risk}`}>
        <div className="dup-icon">
          {output.duplicate_risk === 'high'
            ? '⚠️'
            : output.duplicate_risk === 'medium'
              ? '🔍'
              : '✓'}
        </div>
        <div className="dup-body">
          <div className="dup-label">
            Risk level
            <span className={`dup-risk-badge ${output.duplicate_risk}`}>
              {output.duplicate_risk}
            </span>
          </div>
          <p className="dup-reason">{output.duplicate_reason}</p>
        </div>
      </div>
    </>
  )
}

export function CrmSanityResult({
  input,
  output,
  bare = false,
  tsLabel,
  tokens,
  cleanedSlot,
}: Props) {
  void input
  if (bare) {
    return <ResultBody output={output} tsLabel={tsLabel} cleanedSlot={cleanedSlot} />
  }
  const totalTokens = tokens
    ? `${(tokens.in + tokens.out).toLocaleString()} tokens · ${tokens.in.toLocaleString()} in / ${tokens.out.toLocaleString()} out`
    : `${(output.tokens_in + output.tokens_out).toLocaleString()} tokens · ${output.tokens_in.toLocaleString()} in / ${output.tokens_out.toLocaleString()} out`
  return (
    <div className="crm-sanity">
      <div className="panel-wrap">
        <div className="panel">
          <div className="panel-body">
            <section className="cs-state active">
              <div>
                <ResultBody output={output} tsLabel={tsLabel} cleanedSlot={cleanedSlot} />
              </div>
              <div className="result-footer">
                <span className="token-pill">{totalTokens}</span>
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>
  )
}
