'use client'

import type { ReactNode } from 'react'

import type { Hook, HookResult } from '@/app/api/mini-apps/linkedin-hook/route'
import '../page-styles.css'

export type LinkedinHookInput = { post_text: string }
export type LinkedinHookOutput = HookResult

type Tokens = { in: number; out: number }

type Props = {
  input: LinkedinHookInput
  output: LinkedinHookOutput
  /**
   * When true, render only the inner result body (head + trigger block +
   * hooks list) without the surrounding `.linkedin-hook / .panel-wrap /
   * .panel / .panel-body / .lh-state` wrappers or the `.result-footer`.
   * The inline mini-app page provides those itself and keeps its own
   * export buttons in the footer, so it consumes the component in bare
   * mode. The standalone `/results/[id]` route uses the default (full)
   * render.
   */
  bare?: boolean
  /**
   * Override the `REPORT` label on the result head. The inline mini-app
   * page passes a formatted timestamp like
   * `REPORT · 2026-06-10 · 14:32 UTC`.
   */
  tsLabel?: string
  /**
   * Optional token usage for the footer pill. Only the inline (full) render
   * uses the footer; bare mode ignores this.
   */
  tokens?: Tokens | null
  /**
   * Optional render slot for each hook card. The inline page passes its own
   * interactive `HookCard` (with a per-hook copy button); standalone falls
   * back to a pure `<PureHookCard />`.
   */
  renderHook?: (hook: Hook, index: number, isBest: boolean) => ReactNode
}

export const CHANNEL_LABEL: Record<string, string> = {
  'linkedin-dm': 'LinkedIn DM',
  email: 'Email',
  'cold-call': 'Cold Call',
}

export const CHANNEL_CLASS: Record<string, string> = {
  'linkedin-dm': 'channel-li',
  email: 'channel-email',
  'cold-call': 'channel-call',
}

export function buildLinkedinHookPlainText(r: HookResult): string {
  return [
    `LinkedIn Post to Outbound Hook`,
    '='.repeat(60),
    '',
    `Author   : ${r.post_author}`,
    `Trigger  : ${r.trigger}`,
    `Type     : ${r.trigger_type}`,
    `Persona  : ${r.target_persona}`,
    '',
    '// HOOKS',
    ...r.hooks.map((h, i) =>
      [
        `[Hook ${i + 1}${i === r.best_hook_index ? ' — BEST' : ''}] ${h.angle} · ${CHANNEL_LABEL[h.channel] ?? h.channel}`,
        `Opening : ${h.opening_line}`,
        `Follow-up: ${h.follow_up}`,
      ].join('\n')
    ),
    '',
    `Tokens: ${(r.tokens_in + r.tokens_out).toLocaleString()} (${r.tokens_in.toLocaleString()} in / ${r.tokens_out.toLocaleString()} out)`,
    'Generated by S7 Labs LinkedIn Post to Outbound Hook',
  ].join('\n')
}

function PureHookCard({ hook, isBest }: { hook: Hook; isBest: boolean }) {
  const cls = isBest ? 'hook-card best' : 'hook-card'
  return (
    <div className={cls}>
      <div className="hook-card-header">
        <span className="hook-angle">{`// ${hook.angle}`}</span>
        <div className="hook-badges">
          {isBest && <span className="badge best-badge">Best</span>}
          <span className={`badge ${CHANNEL_CLASS[hook.channel] ?? ''}`}>
            {CHANNEL_LABEL[hook.channel] ?? hook.channel}
          </span>
          <span className="badge">{hook.tone}</span>
        </div>
      </div>
      <p className="hook-opening">{hook.opening_line}</p>
      <div className="hook-followup-label">{'// Follow-up'}</div>
      <p className="hook-followup">{hook.follow_up}</p>
    </div>
  )
}

function ResultBody({
  output,
  tsLabel = 'REPORT',
  renderHook,
}: {
  output: LinkedinHookOutput
  tsLabel?: string
  renderHook?: (hook: Hook, index: number, isBest: boolean) => ReactNode
}) {
  return (
    <>
      <div className="result-head">
        <span className="title">Hooks ready: {output.post_author}</span>
        <span className="ts-label">{tsLabel}</span>
      </div>

      <div className="trigger-block">
        <div className="trigger-eyebrow">
          {'// Outbound trigger'}
          <span className="trigger-type-badge">{output.trigger_type}</span>
        </div>
        <p className="trigger-text">{output.trigger}</p>
        <div className="trigger-meta">
          <span>Target: {output.target_persona}</span>
          <span>Summary: {output.post_summary}</span>
        </div>
      </div>

      <div className="section-header">
        <span>{'// Outbound hooks'}</span>
        <span className="count">{output.hooks.length} generated</span>
      </div>
      <div className="hooks">
        {output.hooks.map((h, i) => {
          const isBest = i === output.best_hook_index
          return renderHook ? (
            <div key={i}>{renderHook(h, i, isBest)}</div>
          ) : (
            <PureHookCard key={i} hook={h} isBest={isBest} />
          )
        })}
      </div>
    </>
  )
}

export function LinkedinHookResult({
  input,
  output,
  bare = false,
  tsLabel,
  tokens,
  renderHook,
}: Props) {
  void input
  if (bare) {
    return <ResultBody output={output} tsLabel={tsLabel} renderHook={renderHook} />
  }
  const totalTokens = tokens
    ? `${(tokens.in + tokens.out).toLocaleString()} tokens · ${tokens.in.toLocaleString()} in / ${tokens.out.toLocaleString()} out`
    : `${(output.tokens_in + output.tokens_out).toLocaleString()} tokens · ${output.tokens_in.toLocaleString()} in / ${output.tokens_out.toLocaleString()} out`
  return (
    <div className="linkedin-hook">
      <div className="panel-wrap">
        <div className="panel">
          <div className="panel-body">
            <section className="lh-state active">
              <div>
                <ResultBody output={output} tsLabel={tsLabel} renderHook={renderHook} />
              </div>
              <div className="result-footer">
                <span className="token-pill">{totalTokens}</span>
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>
  )
}
