'use client'

import type { CheckStatus, Grade, ScanFree, ScanGated } from '@/lib/mini-apps/agentic-types'
import '../page-styles.css'
import { AgenticGatedDetail } from './AgenticGatedDetail'

export type AgenticReadinessInput = { url?: string }
export type AgenticReadinessOutput = {
  scanId?: string
  free: ScanFree
  gated?: ScanGated | null
}

type Props = {
  input: AgenticReadinessInput
  output: AgenticReadinessOutput
  /**
   * When true, render only the inner result body (shareable block: one-liner
   * + scores + free blockers) without surrounding panel wrappers /
   * result-footer / GatedBreakdown. The inline mini-app page provides those
   * itself and keeps the gated unlock flow at page level. The standalone
   * `/results/[id]` route uses the default (full) render.
   */
  bare?: boolean
}

export function gradeClass(g: Grade | string): string {
  if (g === 'A' || g === 'B') return 'grade-good'
  if (g === 'C') return 'grade-mid'
  return 'grade-bad'
}

export function statusDotClass(s: CheckStatus | string): string {
  if (s === 'pass') return 'is-pass'
  if (s === 'warn') return 'is-warn'
  return 'is-fail'
}

export function buildAgenticReadinessPlainText(free: ScanFree, gated: ScanGated | null): string {
  const lines = [
    `Agentic Readiness — ${free.site_name}`,
    free.url,
    '='.repeat(60),
    '',
    free.one_liner,
    '',
    `Overall: ${free.overall_score}/100 (${free.overall_grade}) — ${free.readiness_label}`,
    '',
    '// FREE BLOCKERS',
    ...free.free_blockers.map((b) => `  ${b.name}: ${b.finding}`),
    '',
    '// CHECK STATUS',
    ...free.checks_summary.map((c) => `  ${c.name}: ${c.status}`),
  ]
  if (gated) {
    lines.push('', '// FULL CHECKLIST')
    for (const c of gated.checks) {
      lines.push('', `${c.name} — ${c.score}/10 (${c.grade}) [${c.status}]`)
      lines.push(`  ${c.finding}`)
      lines.push(`  Fix: ${c.fix}`)
    }
    lines.push('', '// FIX IN THIS ORDER')
    gated.prioritised_plan.forEach((p) => {
      lines.push(`  ${p.rank}. ${p.action} (${p.effort} effort) — ${p.impact}`)
    })
    lines.push('', '// QUICK WINS', ...gated.quick_wins.map((q) => `  • ${q}`))
    lines.push('', `Tokens: ${(gated.tokens_in + gated.tokens_out).toLocaleString()}`)
  }
  lines.push('', 'Generated by S7 Labs Agentic Readiness Checker')
  return lines.join('\n')
}

function StatusDot({ status }: { status: CheckStatus }) {
  return <span className={`status-dot ${statusDotClass(status)}`} aria-hidden />
}

function ShareableBody({ free }: { free: ScanFree }) {
  return (
    <div className="shareable-block">
      <div className="one-liner-block">
        <p className="one-liner-text">&ldquo;{free.one_liner}&rdquo;</p>
        <div className="one-liner-meta">
          <span className="project-name">{free.site_name}</span>
          <span className="type-pill">{free.readiness_label}</span>
        </div>
        <p className="estimate-note">{free.url}</p>
      </div>

      <div className="score-row">
        <div className={`score-card overall-card ${gradeClass(free.overall_grade)}`}>
          <div className="sc-label">Overall readiness</div>
          <div className="overall-score-row">
            <span className="overall-score-num">{free.overall_score}</span>
            <span className="overall-score-denom">/100</span>
            <span className={`overall-grade ${gradeClass(free.overall_grade)}`}>
              {free.overall_grade}
            </span>
          </div>
          <div className="sc-delta">{free.readiness_label}</div>
        </div>
        <div className="score-card checks-card">
          <div className="sc-label">6 checks</div>
          <ul className="checks-list">
            {free.checks_summary.map((c) => (
              <li key={c.name} className="checks-list-row">
                <StatusDot status={c.status} />
                <span className="checks-list-name">{c.name}</span>
                <span className={`checks-list-status ${statusDotClass(c.status)}`}>{c.status}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      {free.free_blockers.length > 0 && (
        <>
          <div className="section-header">
            <span>{'// biggest blockers'}</span>
          </div>
          <div className="blockers-list">
            {free.free_blockers.map((b) => (
              <div key={b.name} className="blocker-row">
                <div className="blocker-name">{b.name}</div>
                <p className="blocker-finding">{b.finding}</p>
              </div>
            ))}
          </div>
        </>
      )}
    </div>
  )
}

export function AgenticReadinessResult({ input, output, bare = false }: Props) {
  void input
  const { free, gated } = output
  if (!free) {
    return <p>No data available.</p>
  }

  if (bare) {
    return <ShareableBody free={free} />
  }

  return (
    <div className="agentic-readiness">
      <div className="panel-wrap panel-wrap-wide">
        <div className="panel">
          <div className="panel-body">
            <section className="ar-state active">
              <ShareableBody free={free} />
              {/* On /results/<id> the saved output includes the gated detail;
                  render the full checklist + plan, not just the free teaser. */}
              {gated && <AgenticGatedDetail gated={gated} />}
            </section>
          </div>
        </div>
      </div>
    </div>
  )
}
