'use client'

import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react'
import './page-styles.css'
import { Footer } from '@/components/Footer'
import { Header } from '@/components/Header'
import type {
  CheckStatus,
  Grade,
  ReadinessCheck,
  ScanApiResponse,
  ScanFree,
  ScanGated,
  UnlockApiResponse,
} from '@/lib/mini-apps/agentic-types'
import { parseUnlockApiResponse } from '@/lib/mini-apps/agentic-types'
import { PageScripts } from './PageScripts'

type AppState = 'idle' | 'loading' | 'result' | 'error'
type ResultView = 'locked' | 'unlocked'

const STAGES = [
  {
    num: '01',
    title: 'Fetching the site',
    logs: ['requesting URL', 'reading the HTML', 'checking robots.txt'],
  },
  {
    num: '02',
    title: 'Looking for structure',
    logs: ['scanning for schema data', 'checking meta tags', 'testing render'],
  },
  {
    num: '03',
    title: 'Thinking like an agent',
    logs: ['can it read the content', 'can it find the actions', 'can it trust the brand'],
  },
  {
    num: '04',
    title: 'Scoring readiness',
    logs: ['grading each check', 'ranking the blockers', 'verdict ready'],
  },
]
const STAGE_MS = 5000

function stateSection(active: boolean, extra = ''): string {
  return ['ar-state', extra, active ? 'active' : ''].filter(Boolean).join(' ')
}

function fmtTs(d: Date) {
  const p = (n: number) => String(n).padStart(2, '0')
  return `AGENTIC · ${d.getUTCFullYear()}-${p(d.getUTCMonth() + 1)}-${p(d.getUTCDate())} · ${p(d.getUTCHours())}:${p(d.getUTCMinutes())} UTC`
}

function normalizeUrlInput(input: string): string | null {
  const trimmed = input.trim()
  if (!trimmed) return null
  let href = trimmed
  if (!/^https?:\/\//i.test(href)) href = `https://${href}`
  try {
    const parsed = new URL(href)
    if (!parsed.hostname.includes('.')) return null
    return parsed.href
  } catch {
    return null
  }
}

function gradeClass(g: Grade): string {
  if (g === 'A' || g === 'B') return 'grade-good'
  if (g === 'C') return 'grade-mid'
  return 'grade-bad'
}

function statusDotClass(s: CheckStatus): string {
  if (s === 'pass') return 'is-pass'
  if (s === 'warn') return 'is-warn'
  return 'is-fail'
}

function scoreBadgeClass(score: number): string {
  if (score >= 7) return 'score-good'
  if (score >= 4) return 'score-mid'
  return 'score-bad'
}

function buildPlainText(free: ScanFree, gated: ScanGated | null): string {
  const lines = [
    `Agentic Readiness — ${free.site_name}`,
    free.url,
    '='.repeat(60),
    '',
    free.one_liner,
    '',
    `Overall: ${free.overall_score}/100 (${free.overall_grade}) — ${free.readiness_label}`,
    '',
    '// FREE BLOCKERS',
    ...free.free_blockers.map((b) => `  ${b.name}: ${b.finding}`),
    '',
    '// CHECK STATUS',
    ...free.checks_summary.map((c) => `  ${c.name}: ${c.status}`),
  ]
  if (gated) {
    lines.push('', '// FULL CHECKLIST')
    for (const c of gated.checks) {
      lines.push('', `${c.name} — ${c.score}/10 (${c.grade}) [${c.status}]`)
      lines.push(`  ${c.finding}`)
      lines.push(`  Fix: ${c.fix}`)
    }
    lines.push('', '// FIX IN THIS ORDER')
    gated.prioritised_plan.forEach((p) => {
      lines.push(`  ${p.rank}. ${p.action} (${p.effort} effort) — ${p.impact}`)
    })
    lines.push('', '// QUICK WINS', ...gated.quick_wins.map((q) => `  • ${q}`))
    lines.push('', `Tokens: ${(gated.tokens_in + gated.tokens_out).toLocaleString()}`)
  }
  lines.push('', 'Generated by S7 Labs Agentic Readiness Checker')
  return lines.join('\n')
}

function StatusDot({ status }: { status: CheckStatus }) {
  return <span className={`status-dot ${statusDotClass(status)}`} aria-hidden />
}

function CheckCard({ check }: { check: ReadinessCheck }) {
  return (
    <div className={`check-card status-${check.status}`}>
      <div className="check-card-header">
        <span className="check-card-name">{check.name}</span>
        <span className={`score-badge ${scoreBadgeClass(check.score)}`}>{check.score}/10</span>
        <span className={`grade-pill ${gradeClass(check.grade)}`}>{check.grade}</span>
        <span className={`priority-tag is-${check.priority}`}>{check.priority}</span>
      </div>
      <p className="check-finding">{check.finding}</p>
      <div className="issue-fix">
        <span className="fix-label">Fix</span>
        <span className="fix-text">{check.fix}</span>
      </div>
    </div>
  )
}

export default function AgenticReadinessPage() {
  const [appState, setAppState] = useState<AppState>('idle')
  const [resultView, setResultView] = useState<ResultView>('locked')
  const [url, setUrl] = useState('')
  const [urlError, setUrlError] = useState<string | null>(null)
  const [shakeInput, setShakeInput] = useState(0)
  const [submitting, setSubmitting] = useState(false)
  const [scanId, setScanId] = useState<string | null>(null)
  const [free, setFree] = useState<ScanFree | null>(null)
  const [gated, setGated] = useState<ScanGated | null>(null)
  const [errorMsg, setErrorMsg] = useState('')
  const [resultTs, setResultTs] = useState('')
  const [exportState, setExportState] = useState<'idle' | 'copying' | 'png' | 'pdf'>('idle')

  const [unlockEmail, setUnlockEmail] = useState('')
  const [unlockError, setUnlockError] = useState<string | null>(null)
  const [unlocking, setUnlocking] = useState(false)

  const [activeStage, setActiveStage] = useState(-1)
  const [doneStages, setDoneStages] = useState<number[]>([])
  const [stageLogs, setStageLogs] = useState<string[]>(['', '', '', ''])
  const [progressPct, setProgressPct] = useState(0)
  const [loadingPct, setLoadingPct] = useState('0%')
  const [latency, setLatency] = useState('—')
  const [sysState, setSysState] = useState('idle')
  const [clock, setClock] = useState('—')
  const [tokens, setTokens] = useState<{ in: number; out: number } | null>(null)

  const urlInputRef = useRef<HTMLInputElement | null>(null)
  const shareableRef = useRef<HTMLDivElement | null>(null)
  const timersRef = useRef<ReturnType<typeof setTimeout>[]>([])
  const rafRef = useRef<number | null>(null)
  const runStartRef = useRef(0)

  useEffect(() => {
    const tick = () => {
      const d = new Date()
      const p = (n: number) => String(n).padStart(2, '0')
      setClock(`${p(d.getUTCHours())}:${p(d.getUTCMinutes())}:${p(d.getUTCSeconds())}Z`)
    }
    tick()
    const id = setInterval(tick, 1000)
    return () => clearInterval(id)
  }, [])

  useEffect(() => {
    if (appState === 'idle') {
      const t = setTimeout(() => urlInputRef.current?.focus(), 200)
      return () => clearTimeout(t)
    }
  }, [appState])

  const clearTimers = useCallback(() => {
    timersRef.current.forEach((t) => clearTimeout(t))
    timersRef.current = []
    if (rafRef.current !== null) {
      cancelAnimationFrame(rafRef.current)
      rafRef.current = null
    }
  }, [])

  useEffect(() => () => clearTimers(), [clearTimers])

  const startLoadingAnimation = useCallback(
    (host: string) => {
      clearTimers()
      setActiveStage(0)
      setDoneStages([])
      setStageLogs(['', '', '', ''])
      setProgressPct(0)
      setLoadingPct('0%')
      setLatency('0.0s')
      const startTime = performance.now()
      runStartRef.current = startTime
      const totalMs = STAGE_MS * STAGES.length

      const tick = (now: number) => {
        const pct = Math.min(98, ((now - startTime) / totalMs) * 100)
        setProgressPct(pct)
        setLoadingPct(Math.floor(pct) + '%')
        setLatency(((now - startTime) / 1000).toFixed(1) + 's')
        if (pct < 98) rafRef.current = requestAnimationFrame(tick)
      }
      rafRef.current = requestAnimationFrame(tick)

      STAGES.forEach((stage, i) => {
        timersRef.current.push(
          setTimeout(() => {
            setActiveStage(i)
            setStageLogs((prev) => {
              const n = [...prev]
              n[i] = stage.logs[0] ?? ''
              return n
            })
            stage.logs.forEach((log, li) => {
              if (li === 0) return
              timersRef.current.push(
                setTimeout(
                  () => {
                    setStageLogs((prev) => {
                      const n = [...prev]
                      n[i] = log
                      return n
                    })
                  },
                  (li * STAGE_MS) / stage.logs.length
                )
              )
            })
          }, i * STAGE_MS)
        )
        timersRef.current.push(
          setTimeout(
            () => {
              setDoneStages((prev) => [...prev, i])
              setStageLogs((prev) => {
                const n = [...prev]
                n[i] = stage.logs[stage.logs.length - 1] ?? ''
                return n
              })
            },
            (i + 1) * STAGE_MS
          )
        )
      })
      void host
    },
    [clearTimers]
  )

  const handleSubmit = useCallback(
    async (e: FormEvent) => {
      e.preventDefault()
      if (submitting) return

      const normalized = normalizeUrlInput(url)
      if (!normalized) {
        setUrlError('Enter a valid URL.')
        setShakeInput((k) => k + 1)
        return
      }

      setUrlError(null)
      setSubmitting(true)
      setFree(null)
      setGated(null)
      setScanId(null)
      setResultView('locked')
      setErrorMsg('')
      setSysState('running')
      setAppState('loading')
      const host = new URL(normalized).hostname
      startLoadingAnimation(host)

      let data: ScanApiResponse
      try {
        const res = await fetch('/api/mini-apps/agentic-readiness', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ url: normalized }),
        })
        data = (await res.json()) as ScanApiResponse
      } catch {
        clearTimers()
        setErrorMsg('Network error. Please check your connection and try again.')
        setSysState('error')
        setAppState('error')
        setSubmitting(false)
        return
      }

      clearTimers()
      setLatency(((performance.now() - runStartRef.current) / 1000).toFixed(1) + 's')
      setProgressPct(100)
      setLoadingPct('100%')

      if (data.ok) {
        setDoneStages([0, 1, 2, 3])
        await new Promise((r) => setTimeout(r, 400))
        setScanId(data.scanId)
        setFree(data.free)
        setResultTs(fmtTs(new Date()))
        setSysState('complete')
        setAppState('result')
      } else {
        setErrorMsg(data.message)
        setSysState('error')
        setAppState('error')
      }
      setSubmitting(false)
    },
    [url, submitting, startLoadingAnimation, clearTimers]
  )

  const handleUnlock = useCallback(
    async (e: FormEvent) => {
      e.preventDefault()
      if (!scanId || unlocking) return
      const email = unlockEmail.trim().toLowerCase()
      if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(email)) {
        setUnlockError('Enter a valid email.')
        return
      }
      setUnlockError(null)
      setUnlocking(true)

      let data: UnlockApiResponse
      try {
        const res = await fetch('/api/mini-apps/agentic-readiness/unlock', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ scanId, email }),
        })
        data = parseUnlockApiResponse(await res.json())
      } catch {
        setUnlockError('Network error. Please try again.')
        setUnlocking(false)
        return
      }

      if (data.ok) {
        setGated(data.data)
        setTokens({ in: data.data.tokens_in, out: data.data.tokens_out })
        setResultView('unlocked')
      } else {
        setUnlockError(data.message)
      }
      setUnlocking(false)
    },
    [scanId, unlockEmail, unlocking]
  )

  const handleReset = useCallback(() => {
    clearTimers()
    setAppState('idle')
    setResultView('locked')
    setFree(null)
    setGated(null)
    setScanId(null)
    setErrorMsg('')
    setUnlockEmail('')
    setUnlockError(null)
    setSubmitting(false)
    setUnlocking(false)
    setSysState('idle')
    setLatency('—')
    setTokens(null)
  }, [clearTimers])

  const handleCopy = useCallback(async () => {
    if (!free) return
    setExportState('copying')
    try {
      await navigator.clipboard.writeText(buildPlainText(free, gated))
    } catch {
      const ta = document.createElement('textarea')
      ta.value = buildPlainText(free, gated)
      ta.style.cssText = 'position:fixed;opacity:0'
      document.body.appendChild(ta)
      ta.select()
      document.execCommand('copy')
      document.body.removeChild(ta)
    }
    setTimeout(() => setExportState('idle'), 1800)
  }, [free, gated])

  const captureShareable = useCallback(async () => {
    if (!shareableRef.current) return null
    const { default: html2canvas } = await import('html2canvas')
    return html2canvas(shareableRef.current, {
      backgroundColor: '#101014',
      scale: 2,
      useCORS: true,
      logging: false,
    })
  }, [])

  const handleDownloadPng = useCallback(async () => {
    if (!free) return
    setExportState('png')
    try {
      const canvas = await captureShareable()
      if (!canvas) return
      const a = document.createElement('a')
      a.download = `agentic-${free.site_name.replace(/[^a-z0-9]/gi, '-').toLowerCase()}.png`
      a.href = canvas.toDataURL('image/png')
      a.click()
    } catch (err) {
      console.error(err)
    }
    setExportState('idle')
  }, [free, captureShareable])

  const handleDownloadPdf = useCallback(async () => {
    if (!free) return
    setExportState('pdf')
    try {
      const canvas = await captureShareable()
      if (!canvas) return
      const { jsPDF } = await import('jspdf')
      const imgW = 190
      const imgH = (canvas.height / canvas.width) * imgW
      const pdf = new jsPDF({ orientation: imgH > imgW ? 'portrait' : 'landscape', unit: 'mm' })
      pdf.addImage(canvas.toDataURL('image/png'), 'PNG', 10, 10, imgW, imgH)
      pdf.save(`agentic-${free.site_name.replace(/[^a-z0-9]/gi, '-').toLowerCase()}.pdf`)
    } catch (err) {
      console.error(err)
    }
    setExportState('idle')
  }, [free, captureShareable])

  const loadingHost = url
    ? (normalizeUrlInput(url)
        ?.replace(/^https?:\/\//, '')
        .split('/')[0] ?? 'site')
    : 'site'

  return (
    <div className="agentic-readiness">
      <div className="bg-layer bg-aurora">
        <div className="blob3" />
      </div>
      <div className="bg-layer bg-dots" />
      <div className="bg-layer bg-vignette" />
      <div className="bg-layer bg-spotlight" id="ar-spotlight" />
      <div className="bg-layer bg-grain" />

      <Header />

      <main className="shell">
        <section className="hero">
          <span className="eyebrow">Agentic Readiness Checker</span>
          <h1>
            Can an AI agent <span className="accent">actually use your site?</span>
          </h1>
          <p>
            We scrape your site like an agent would — structured data, crawl rules, render
            dependency, and machine-readable actions — then score how ready you are for the agentic
            web.
          </p>
          <div className="meta-tags">
            <span>· 6 readiness checks</span>
            <span>· Biggest blockers free</span>
            <span>· Full checklist by email</span>
          </div>
        </section>

        <div className="panel-wrap panel-wrap-wide">
          <div className="panel">
            <span className="corner tl" />
            <span className="corner tr" />
            <span className="corner bl" />
            <span className="corner br" />

            <div className="panel-readouts">
              <div className="prl">
                <span>
                  <span className="stat-key">sys</span> <span className="stat-val">{sysState}</span>
                </span>
                <span className="pr-sep hide-sm" />
                <span className="hide-sm">
                  <span className="stat-key">eng</span> <span className="stat-val">v1.0</span>
                </span>
              </div>
              <div className="prr">
                {tokens && (
                  <>
                    <span className="hide-sm">
                      <span className="stat-key">tok</span>{' '}
                      <span className="stat-val">{(tokens.in + tokens.out).toLocaleString()}</span>
                    </span>
                    <span className="pr-sep hide-sm" />
                  </>
                )}
                <span className="hide-sm">
                  <span className="stat-key">lat</span> <span className="stat-val">{latency}</span>
                </span>
                <span className="pr-sep hide-sm" />
                <span>
                  <span className="stat-key">ts</span> <span className="stat-val">{clock}</span>
                </span>
              </div>
            </div>

            <div className="panel-body">
              <section className={stateSection(appState === 'idle')}>
                <div className="idle-label">Can an AI agent actually use your site?</div>
                <form noValidate onSubmit={handleSubmit} autoComplete="off">
                  <div className="input-field">
                    <label>Website URL</label>
                    <div key={`u-${shakeInput}`} className={`input-box${urlError ? 'error' : ''}`}>
                      <span className="prompt">$</span>
                      <input
                        ref={urlInputRef}
                        type="text"
                        placeholder="https://yoursite.com"
                        value={url}
                        disabled={submitting}
                        onChange={(e) => {
                          setUrl(e.target.value)
                          if (urlError) setUrlError(null)
                        }}
                      />
                    </div>
                    {urlError && <div className="field-error">{urlError}</div>}
                  </div>
                  <div className="submit-row">
                    <button type="submit" className="submit-btn" disabled={submitting}>
                      <svg
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        strokeWidth="2.2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      >
                        <path d="M12 2a4 4 0 014 4v2" />
                        <rect x="4" y="8" width="16" height="12" rx="2" />
                        <path d="M9 14h.01M15 14h.01" />
                      </svg>
                      Check agent readiness
                    </button>
                  </div>
                </form>
              </section>

              <section className={stateSection(appState === 'loading')}>
                <div className="progress-track">
                  <div className="progress-bar" style={{ width: `${progressPct}%` }} />
                </div>
                <div className="loading-header">
                  <span>
                    Checking <strong>{loadingHost}</strong>
                  </span>
                  <span>{loadingPct}</span>
                </div>
                <div className="stages">
                  {STAGES.map((s, i) => {
                    const isActive = activeStage === i && !doneStages.includes(i)
                    const isDone = doneStages.includes(i)
                    return (
                      <div
                        key={s.num}
                        className={`stage${isActive ? 'active' : ''}${isDone ? 'done' : ''}`}
                      >
                        <div className="stage-num-row">
                          <span>{s.num}</span>
                          <span className="stage-status-icon">
                            <svg viewBox="0 0 12 12" fill="none">
                              <path
                                d="M2 6.5l2.5 2.5L10 3"
                                stroke="currentColor"
                                strokeWidth="2"
                                strokeLinecap="round"
                                strokeLinejoin="round"
                              />
                            </svg>
                          </span>
                        </div>
                        <div className="stage-title">{s.title}</div>
                        <div className="stage-log">{stageLogs[i]}</div>
                      </div>
                    )
                  })}
                </div>
              </section>

              <section className={stateSection(appState === 'result')}>
                {free && (
                  <>
                    <div ref={shareableRef} className="shareable-block">
                      <div className="one-liner-block">
                        <p className="one-liner-text">&ldquo;{free.one_liner}&rdquo;</p>
                        <div className="one-liner-meta">
                          <span className="project-name">{free.site_name}</span>
                          <span className="type-pill">{free.readiness_label}</span>
                        </div>
                        <p className="estimate-note">{free.url}</p>
                      </div>

                      <div className="score-row">
                        <div
                          className={`score-card overall-card ${gradeClass(free.overall_grade)}`}
                        >
                          <div className="sc-label">Overall readiness</div>
                          <div className="overall-score-row">
                            <span className="overall-score-num">{free.overall_score}</span>
                            <span className="overall-score-denom">/100</span>
                            <span className={`overall-grade ${gradeClass(free.overall_grade)}`}>
                              {free.overall_grade}
                            </span>
                          </div>
                          <div className="sc-delta">{free.readiness_label}</div>
                        </div>
                        <div className="score-card checks-card">
                          <div className="sc-label">6 checks</div>
                          <ul className="checks-list">
                            {free.checks_summary.map((c) => (
                              <li key={c.name} className="checks-list-row">
                                <StatusDot status={c.status} />
                                <span className="checks-list-name">{c.name}</span>
                                <span className={`checks-list-status ${statusDotClass(c.status)}`}>
                                  {c.status}
                                </span>
                              </li>
                            ))}
                          </ul>
                        </div>
                      </div>

                      {free.free_blockers.length > 0 && (
                        <>
                          <div className="section-header">
                            <span>{'// biggest blockers'}</span>
                          </div>
                          <div className="blockers-list">
                            {free.free_blockers.map((b) => (
                              <div key={b.name} className="blocker-row">
                                <div className="blocker-name">{b.name}</div>
                                <p className="blocker-finding">{b.finding}</p>
                              </div>
                            ))}
                          </div>
                        </>
                      )}
                    </div>

                    {resultView === 'locked' && (
                      <div className="gate-block">
                        <div className="gate-preview" aria-hidden>
                          <div className="gate-preview-fake">
                            {free.checks_summary.slice(0, 3).map((c) => (
                              <div key={c.name} className="gate-fake-row">
                                {c.name}
                              </div>
                            ))}
                          </div>
                        </div>
                        <div className="gate-card">
                          <h3 className="gate-title">See every blocker and the fix priority</h3>
                          <p className="gate-sub">
                            Get the full 6-point checklist, the specific fix for each issue, and a
                            ranked action plan. We found {free.total_issues} issue
                            {free.total_issues === 1 ? '' : 's'} to fix.
                          </p>
                          <form noValidate onSubmit={handleUnlock} className="gate-form">
                            <div
                              className={`input-box gate-email-box${unlockError ? 'error' : ''}`}
                            >
                              <input
                                type="email"
                                placeholder="you@company.com"
                                value={unlockEmail}
                                disabled={unlocking}
                                onChange={(e) => {
                                  setUnlockEmail(e.target.value)
                                  if (unlockError) setUnlockError(null)
                                }}
                              />
                            </div>
                            {unlockError && <div className="field-error">{unlockError}</div>}
                            <button
                              type="submit"
                              className="submit-btn gate-submit"
                              disabled={unlocking}
                            >
                              {unlocking ? 'Unlocking…' : 'Unlock the full checklist'}
                            </button>
                          </form>
                        </div>
                      </div>
                    )}

                    {resultView === 'unlocked' && gated && (
                      <>
                        {gated.quick_wins.length > 0 && (
                          <div className="quick-wins-row">
                            <span className="quick-wins-label">Fixable today</span>
                            {gated.quick_wins.map((w) => (
                              <span key={w} className="quick-win-pill">
                                {w}
                              </span>
                            ))}
                          </div>
                        )}

                        <div className="section-header">
                          <span>{'// full checklist'}</span>
                          <span>6 checks</span>
                        </div>
                        <div className="check-grid">
                          {gated.checks.map((check) => (
                            <CheckCard key={check.name} check={check} />
                          ))}
                        </div>

                        <div className="plan-block">
                          <div className="plan-eyebrow">{'// fix in this order'}</div>
                          <ol className="plan-list">
                            {gated.prioritised_plan.map((item) => (
                              <li key={item.rank} className="plan-row">
                                <span className="plan-number">
                                  {String(item.rank).padStart(2, '0')}
                                </span>
                                <div className="plan-body">
                                  <div className="plan-action">{item.action}</div>
                                  <div className="plan-meta">
                                    <span>{item.impact}</span>
                                    <span className={`effort-tag is-${item.effort}`}>
                                      {item.effort} effort
                                    </span>
                                  </div>
                                </div>
                              </li>
                            ))}
                          </ol>
                        </div>
                      </>
                    )}

                    <div className="result-footer">
                      <span className="token-pill">
                        {tokens
                          ? `${(tokens.in + tokens.out).toLocaleString()} tokens · ${tokens.in.toLocaleString()} in / ${tokens.out.toLocaleString()} out`
                          : 'Unlock for token usage'}
                      </span>
                      <span className="result-ts hide-sm">{resultTs}</span>
                      <div className="export-actions">
                        <button
                          className={`export-btn${exportState === 'copying' ? 'done' : ''}`}
                          type="button"
                          onClick={handleCopy}
                          disabled={exportState !== 'idle'}
                        >
                          {exportState === 'copying' ? 'Copied' : 'Copy'}
                        </button>
                        <button
                          className={`export-btn${exportState === 'png' ? 'loading' : ''}`}
                          type="button"
                          onClick={handleDownloadPng}
                          disabled={exportState !== 'idle'}
                        >
                          {exportState === 'png' ? '…' : 'PNG'}
                        </button>
                        <button
                          className={`export-btn${exportState === 'pdf' ? 'loading' : ''}`}
                          type="button"
                          onClick={handleDownloadPdf}
                          disabled={exportState !== 'idle'}
                        >
                          {exportState === 'pdf' ? '…' : 'PDF'}
                        </button>
                        <button className="run-again" type="button" onClick={handleReset}>
                          Check another site
                          <svg
                            width="12"
                            height="12"
                            viewBox="0 0 24 24"
                            fill="none"
                            stroke="currentColor"
                            strokeWidth="2.4"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                          >
                            <path d="M5 12h14" />
                            <path d="M13 5l7 7-7 7" />
                          </svg>
                        </button>
                      </div>
                    </div>
                  </>
                )}
              </section>

              <section className={stateSection(appState === 'error', 'error-state')}>
                <div className="err-icon">
                  <svg
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.8"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <circle cx="12" cy="12" r="10" />
                    <line x1="5.5" y1="5.5" x2="18.5" y2="18.5" />
                  </svg>
                </div>
                <h2 className="err-title">Check failed</h2>
                <p className="err-msg">{errorMsg}</p>
                <button className="err-btn" type="button" onClick={handleReset}>
                  Try again
                </button>
              </section>
            </div>
          </div>
        </div>

        <section className="info-strip">
          <div className="dim-card">
            <div className="key">{'// 01 Scrape'}</div>
            <div className="name">Machine-readable signals</div>
            <div className="desc">HTML, schema, robots.txt, and render clues — parsed in code.</div>
          </div>
          <div className="dim-card">
            <div className="key">{'// 02 Score'}</div>
            <div className="name">6 readiness checks</div>
            <div className="desc">Structured data through identity — scored for agent use.</div>
          </div>
          <div className="dim-card">
            <div className="key">{'// 03 Hook'}</div>
            <div className="name">Top blockers free</div>
            <div className="desc">See what stops agents cold before you fix anything.</div>
          </div>
          <div className="dim-card">
            <div className="key">{'// 04 Unlock'}</div>
            <div className="name">Full checklist</div>
            <div className="desc">Every fix, prioritised plan, and quick wins by email.</div>
          </div>
        </section>
      </main>

      <Footer />
      <PageScripts />
    </div>
  )
}
