'use client'

import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react'

import { clsx } from 'clsx'
import './page-styles.css'

import { Footer } from '@/components/Footer'
import { Header } from '@/components/Header'
import { AuroraBackground } from '@/components/mini-apps/AuroraBackground'
import { EmailGate } from '@/components/mini-apps/EmailGate'
import { SubmitOnce } from '@/components/mini-apps/SubmitOnce'

import type {
  ApiResponse,
  DiagnosticResult,
  Improvement,
} from '@/app/api/mini-apps/pricing-diagnostic/route'
import { PageScripts } from './PageScripts'

function buildPlainText(r: DiagnosticResult): string {
  const lines: string[] = [
    `Pricing Page Diagnostic — ${r.url}`,
    '='.repeat(60),
    '',
    `Friction Score  : ${r.friction_score}/10`,
    `Clarity Grade   : ${r.clarity_grade}`,
    `Plan Legibility : ${r.plan_legibility}`,
    '',
    '// WHO THIS ACTUALLY TARGETS',
    r.buyer_inference,
    '',
    '// ISSUES FOUND',
    ...r.flags.map((f) => `  · ${f}`),
    '',
    '// TOP 3 IMPROVEMENTS',
    ...r.improvements.map(
      (imp) => `  ${imp.rank}. [${imp.impact.toUpperCase()}] ${imp.title}\n     ${imp.description}`
    ),
    '',
    `Tokens used: ${(r.tokens_in + r.tokens_out).toLocaleString()} (${r.tokens_in.toLocaleString()} in / ${r.tokens_out.toLocaleString()} out)`,
    `Generated by S7 Labs Pricing Page Diagnostic`,
  ]
  return lines.join('\n')
}

type AppState = 'idle' | 'loading' | 'result' | 'error'

type StageConfig = {
  num: string
  title: string
  logs: string[]
}

const STAGES: StageConfig[] = [
  {
    num: '01',
    title: 'Fetching pricing page',
    logs: ['GET /pricing', '200 OK · loading content', 'dom snapshot stored'],
  },
  {
    num: '02',
    title: 'Parsing plan structure',
    logs: ['walking DOM tree', 'tier nodes found', 'features matched'],
  },
  {
    num: '03',
    title: 'Scoring friction points',
    logs: ['running heuristics', 'signals detected', 'gates analysed'],
  },
  {
    num: '04',
    title: 'Drafting recommendations',
    logs: ['ranking candidates', 'top-3 selected', 'draft complete'],
  },
]

const STAGE_DURATION_MS = 4800

function trimUrl(u: string): string {
  try {
    const url = new URL(u)
    return (url.host + url.pathname).replace(/\/$/, '')
  } catch {
    return u.replace(/^https?:\/\//, '').replace(/\/$/, '')
  }
}

function fmtTs(d: Date): string {
  const pad = (n: number) => String(n).padStart(2, '0')
  return `REPORT · ${d.getUTCFullYear()}-${pad(d.getUTCMonth() + 1)}-${pad(d.getUTCDate())} · ${pad(d.getUTCHours())}:${pad(d.getUTCMinutes())} UTC`
}

function frictionClass(score: number): string {
  if (score <= 3) return 'good'
  if (score <= 6) return 'mid'
  return 'bad'
}

function gradeClass(grade: string): string {
  if (grade.startsWith('A')) return 'good'
  if (grade.startsWith('B')) return 'good'
  if (grade.startsWith('C')) return 'mid'
  return 'bad'
}

function legibilityClass(leg: string): string {
  if (leg === 'Excellent') return 'good'
  if (leg === 'Good') return 'good'
  if (leg === 'Fair') return 'mid'
  return 'bad'
}

function frictionDelta(score: number): string {
  if (score <= 3) return 'low — smooth buyer path'
  if (score <= 6) return 'moderate — some friction'
  return 'high — buyer drop-off likely'
}

function gradeDelta(grade: string): string {
  if (grade.startsWith('A')) return 'clear value communication'
  if (grade.startsWith('B')) return 'mostly clear, minor gaps'
  if (grade.startsWith('C')) return 'mixed signals to first-time visitors'
  return 'confusing — needs rework'
}

function legDelta(leg: string): string {
  if (leg === 'Excellent') return 'tiers and gating are crystal clear'
  if (leg === 'Good') return 'plans readable, minor issues'
  if (leg === 'Fair') return 'tiers parse, gating unclear'
  return 'hard to compare plans'
}

function ImpCard({ item }: { item: Improvement }) {
  return (
    <article className={`imp${item.rank === 1 ? 'top' : ''}`}>
      <div className="rank">0{item.rank}</div>
      <div className="imp-body">
        <h3>{item.title}</h3>
        <p>{item.description}</p>
      </div>
      <span className={`impact ${item.impact}`}>{item.impact}</span>
    </article>
  )
}

export default function PricingDiagnosticPage() {
  const [appState, setAppState] = useState<AppState>('idle')
  const [url, setUrl] = useState('')
  const [urlError, setUrlError] = useState<string | null>(null)
  const [shakeKey, setShakeKey] = useState(0)
  const [submitting, setSubmitting] = useState(false)
  const [result, setResult] = useState<DiagnosticResult | null>(null)
  const [errorMsg, setErrorMsg] = useState('')
  const [resultTs, setResultTs] = useState('')

  // Loading stage animation state
  const [activeStage, setActiveStage] = useState(-1)
  const [doneStages, setDoneStages] = useState<number[]>([])
  const [stageLogs, setStageLogs] = useState<string[]>(['', '', '', ''])
  const [progressPct, setProgressPct] = useState(0)
  const [loadingPct, setLoadingPct] = useState('0%')
  const [latency, setLatency] = useState('—')
  const [sysState, setSysState] = useState('idle')
  const [clock, setClock] = useState('—')
  const [tokens, setTokens] = useState<{ in: number; out: number } | null>(null)

  const [exportState, setExportState] = useState<'idle' | 'copying' | 'png' | 'pdf'>('idle')

  const urlInputRef = useRef<HTMLInputElement | null>(null)
  const resultPanelRef = useRef<HTMLDivElement | null>(null)
  const timersRef = useRef<ReturnType<typeof setTimeout>[]>([])
  const rafRef = useRef<number | null>(null)
  const runStartRef = useRef(0)
  const prefersReducedRef = useRef(false)

  useEffect(() => {
    prefersReducedRef.current = window.matchMedia('(prefers-reduced-motion: reduce)').matches
  }, [])

  // Live clock
  useEffect(() => {
    const tick = () => {
      const d = new Date()
      const pad = (n: number) => String(n).padStart(2, '0')
      setClock(`${pad(d.getUTCHours())}:${pad(d.getUTCMinutes())}:${pad(d.getUTCSeconds())}Z`)
    }
    tick()
    const id = setInterval(tick, 1000)
    return () => clearInterval(id)
  }, [])

  useEffect(() => {
    if (appState === 'idle') {
      const t = setTimeout(() => urlInputRef.current?.focus(), 200)
      return () => clearTimeout(t)
    }
  }, [appState])

  const clearTimers = useCallback(() => {
    timersRef.current.forEach((t) => clearTimeout(t))
    timersRef.current = []
    if (rafRef.current !== null) {
      cancelAnimationFrame(rafRef.current)
      rafRef.current = null
    }
  }, [])

  useEffect(() => () => clearTimers(), [clearTimers])

  const startLoadingAnimation = useCallback(() => {
    clearTimers()
    setActiveStage(0)
    setDoneStages([])
    setStageLogs(['', '', '', ''])
    setProgressPct(0)
    setLoadingPct('0%')
    setLatency('0.0s')

    const totalMs = STAGE_DURATION_MS * STAGES.length
    const startTime = performance.now()
    runStartRef.current = startTime

    if (!prefersReducedRef.current) {
      const tick = (now: number) => {
        const elapsed = now - startTime
        const pct = Math.min(98, (elapsed / totalMs) * 100)
        setProgressPct(pct)
        setLoadingPct(Math.floor(pct) + '%')
        setLatency((elapsed / 1000).toFixed(1) + 's')
        if (pct < 98) {
          rafRef.current = requestAnimationFrame(tick)
        }
      }
      rafRef.current = requestAnimationFrame(tick)
    }

    STAGES.forEach((stage, i) => {
      // Activate stage
      const tActivate = setTimeout(() => {
        setActiveStage(i)
        setStageLogs((prev) => {
          const next = [...prev]
          next[i] = stage.logs[0] ?? ''
          return next
        })
        // Cycle logs while active
        stage.logs.forEach((log, li) => {
          if (li === 0) return
          const tLog = setTimeout(
            () => {
              setStageLogs((prev) => {
                const next = [...prev]
                next[i] = log
                return next
              })
            },
            (li * STAGE_DURATION_MS) / stage.logs.length
          )
          timersRef.current.push(tLog)
        })
      }, i * STAGE_DURATION_MS)
      timersRef.current.push(tActivate)

      // Mark done
      const tDone = setTimeout(
        () => {
          setDoneStages((prev) => [...prev, i])
          setStageLogs((prev) => {
            const next = [...prev]
            next[i] = stage.logs[stage.logs.length - 1] ?? ''
            return next
          })
        },
        (i + 1) * STAGE_DURATION_MS
      )
      timersRef.current.push(tDone)
    })
  }, [clearTimers])

  const handleSubmit = useCallback(
    async (e: FormEvent) => {
      e.preventDefault()
      if (submitting) return
      const trimmed = url.trim()
      if (!trimmed) {
        setUrlError('Please enter a URL.')
        setShakeKey((k) => k + 1)
        return
      }
      if (!/^https?:\/\/.+\..+/.test(trimmed)) {
        setUrlError('Enter a valid URL starting with http:// or https://')
        setShakeKey((k) => k + 1)
        return
      }
      setUrlError(null)
      setSubmitting(true)
      setResult(null)
      setErrorMsg('')
      setSysState('running')
      setAppState('loading')
      startLoadingAnimation()

      let data: ApiResponse
      try {
        const res = await fetch('/api/mini-apps/pricing-diagnostic', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ url: trimmed }),
        })
        data = (await res.json()) as ApiResponse
      } catch {
        clearTimers()
        setErrorMsg('Network error. Please check your connection and try again.')
        setSysState('error')
        setAppState('error')
        setSubmitting(false)
        return
      }

      clearTimers()
      const elapsed = ((performance.now() - runStartRef.current) / 1000).toFixed(1) + 's'
      setLatency(elapsed)
      setProgressPct(100)
      setLoadingPct('100%')

      if (data.ok) {
        setActiveStage(STAGES.length - 1)
        setDoneStages([0, 1, 2, 3])
        await new Promise((r) => setTimeout(r, 400))
        setResult(data.data)
        setTokens({ in: data.data.tokens_in, out: data.data.tokens_out })
        setResultTs(fmtTs(new Date()))
        setSysState('complete')
        setAppState('result')
      } else {
        setErrorMsg(data.message)
        setSysState('error')
        setAppState('error')
      }
      setSubmitting(false)
    },
    [url, submitting, startLoadingAnimation, clearTimers]
  )

  const handleReset = useCallback(() => {
    clearTimers()
    setAppState('idle')
    setResult(null)
    setErrorMsg('')
    setUrlError(null)
    setSubmitting(false)
    setSysState('idle')
    setLatency('—')
    setProgressPct(0)
    setTokens(null)
  }, [clearTimers])

  const handleCopy = useCallback(async () => {
    if (!result) return
    setExportState('copying')
    try {
      await navigator.clipboard.writeText(buildPlainText(result))
    } catch {
      // fallback: textarea trick
      const ta = document.createElement('textarea')
      ta.value = buildPlainText(result)
      ta.style.position = 'fixed'
      ta.style.opacity = '0'
      document.body.appendChild(ta)
      ta.select()
      document.execCommand('copy')
      document.body.removeChild(ta)
    }
    setTimeout(() => setExportState('idle'), 1800)
  }, [result])

  const handleDownloadPng = useCallback(async () => {
    if (!resultPanelRef.current || !result) return
    setExportState('png')
    try {
      const { default: html2canvas } = await import('html2canvas')
      const canvas = await html2canvas(resultPanelRef.current, {
        backgroundColor: '#101014',
        scale: 2,
        useCORS: true,
        logging: false,
      })
      const link = document.createElement('a')
      link.download = `pricing-diagnostic-${trimUrl(result.url).replace(/[^a-z0-9]/gi, '-')}.png`
      link.href = canvas.toDataURL('image/png')
      link.click()
    } catch (e) {
      console.error(e)
    }
    setExportState('idle')
  }, [result])

  const handleDownloadPdf = useCallback(async () => {
    if (!resultPanelRef.current || !result) return
    setExportState('pdf')
    try {
      const { default: html2canvas } = await import('html2canvas')
      const { jsPDF } = await import('jspdf')
      const canvas = await html2canvas(resultPanelRef.current, {
        backgroundColor: '#101014',
        scale: 2,
        useCORS: true,
        logging: false,
      })
      const imgW = 190
      const imgH = (canvas.height / canvas.width) * imgW
      const pdf = new jsPDF({ orientation: imgH > imgW ? 'portrait' : 'landscape', unit: 'mm' })
      pdf.addImage(canvas.toDataURL('image/png'), 'PNG', 10, 10, imgW, imgH)
      pdf.save(`pricing-diagnostic-${trimUrl(result.url).replace(/[^a-z0-9]/gi, '-')}.pdf`)
    } catch (e) {
      console.error(e)
    }
    setExportState('idle')
  }, [result])

  const loadingHost = url ? trimUrl(url).split('/')[0] : 'target'

  return (
    <div className="pricing-diag">
      <AuroraBackground />

      <Header />

      <main className="shell">
        {/* Hero */}
        <section className="hero">
          <span className="eyebrow">Pricing Page Diagnostic</span>
          <h1>
            See what your pricing page <span className="accent">actually says</span> to buyers.
          </h1>
          <p>
            Drop in any URL — yours or a competitor&apos;s. We scrape it, parse the plan structure,
            and return an AI teardown of where it&apos;s leaking trust.
          </p>
        </section>

        {/* Panel */}
        <div className="panel-wrap">
          <div className="panel">
            {/* Panel readouts bar — only during run/result for technical credibility */}
            {appState !== 'idle' && (
              <div className="panel-readouts">
                <div className="prl">
                  <span>
                    <span className="stat-key">sys</span>{' '}
                    <span className="stat-val">{sysState}</span>
                  </span>
                  <span className="pr-sep hide-sm" />
                  <span className="hide-sm">
                    <span className="stat-key">eng</span> <span className="stat-val">v1.0</span>
                  </span>
                </div>
                <div className="prr">
                  {tokens && (
                    <>
                      <span className="hide-sm">
                        <span className="stat-key">tok</span>{' '}
                        <span className="stat-val">
                          {(tokens.in + tokens.out).toLocaleString()}
                        </span>
                      </span>
                      <span className="pr-sep hide-sm" />
                    </>
                  )}
                  <span className="hide-sm">
                    <span className="stat-key">lat</span>{' '}
                    <span className="stat-val">{latency}</span>
                  </span>
                  <span className="pr-sep hide-sm" />
                  <span>
                    <span className="stat-key">ts</span> <span className="stat-val">{clock}</span>
                  </span>
                </div>
              </div>
            )}

            <div className="panel-body">
              {/* IDLE */}
              <section className={`pd-state${appState === 'idle' ? 'active' : ''}`}>
                <div className="idle-label">Input target URL</div>
                <form
                  key={shakeKey}
                  className={`url-input${urlError ? 'error' : ''}`}
                  noValidate
                  onSubmit={handleSubmit}
                  autoComplete="off"
                >
                  <input
                    ref={urlInputRef}
                    type="text"
                    placeholder="https://your-product.com/pricing"
                    spellCheck={false}
                    value={url}
                    disabled={submitting}
                    onChange={(e) => {
                      setUrl(e.target.value)
                      if (urlError) setUrlError(null)
                    }}
                  />
                  <button type="submit" aria-label="Run diagnostic" disabled={submitting}>
                    <svg
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    >
                      <path d="M5 12h14" />
                      <path d="M13 5l7 7-7 7" />
                    </svg>
                  </button>
                </form>
                <div className={`helper${urlError ? 'error' : ''}`}>
                  <span>{urlError ?? "Paste your own pricing page or a competitor's"}</span>
                  <span className="examples">
                    <span
                      className="chip-example"
                      onClick={() => setUrl('https://linear.app/pricing')}
                    >
                      linear.app
                    </span>
                    <span
                      className="chip-example"
                      onClick={() => setUrl('https://vercel.com/pricing')}
                    >
                      vercel.com
                    </span>
                  </span>
                </div>
              </section>

              {/* LOADING */}
              <section className={`pd-state${appState === 'loading' ? 'active' : ''}`}>
                <div className="progress-track">
                  <div className="progress-bar" style={{ width: `${progressPct}%` }} />
                </div>
                <div className="loading-header">
                  <span>
                    Analysing <strong>{loadingHost}</strong>
                  </span>
                  <span>{loadingPct}</span>
                </div>
                <div className="stages">
                  {STAGES.map((s, i) => {
                    const isActive = activeStage === i && !doneStages.includes(i)
                    const isDone = doneStages.includes(i)
                    return (
                      <div
                        key={s.num}
                        className={clsx('stage', { active: isActive, done: isDone })}
                      >
                        <div className="stage-num-row">
                          <span>{s.num}</span>
                          <span className="stage-status-icon">
                            <svg viewBox="0 0 12 12" fill="none">
                              <path
                                d="M2 6.5l2.5 2.5L10 3"
                                stroke="currentColor"
                                strokeWidth="2"
                                strokeLinecap="round"
                                strokeLinejoin="round"
                              />
                            </svg>
                          </span>
                        </div>
                        <div className="stage-title">{s.title}</div>
                        <div className="stage-log">{stageLogs[i]}</div>
                      </div>
                    )
                  })}
                </div>
              </section>

              {/* RESULT */}
              <section className={`pd-state${appState === 'result' ? 'active' : ''}`}>
                {result && (
                  <EmailGate
                    miniAppSlug="pricing-diagnostic"
                    pattern="upfront"
                    initialInput={{ url: result.url }}
                  >
                    {({ submitToApi }) => (
                      <>
                        <SubmitOnce
                          submit={submitToApi}
                          input={{ url: result.url }}
                          output={result}
                        />
                        <div ref={resultPanelRef}>
                          <div className="result-head">
                            <span className="title">Diagnostic complete</span>
                            <span className="ts-label">{resultTs}</span>
                          </div>

                          <div className="score-row">
                            <div className={`score-card ${frictionClass(result.friction_score)}`}>
                              <div className="sc-label">Friction Score</div>
                              <div className="sc-value">
                                <span className="sc-big">{result.friction_score}</span>
                                <span className="sc-small">/10</span>
                              </div>
                              <div className="sc-delta">{frictionDelta(result.friction_score)}</div>
                            </div>
                            <div className={`score-card ${gradeClass(result.clarity_grade)}`}>
                              <div className="sc-label">Clarity Grade</div>
                              <div className="sc-value">
                                <span className="sc-big">{result.clarity_grade}</span>
                              </div>
                              <div className="sc-delta">{gradeDelta(result.clarity_grade)}</div>
                            </div>
                            <div
                              className={`score-card ${legibilityClass(result.plan_legibility)}`}
                            >
                              <div className="sc-label">Plan Legibility</div>
                              <div className="sc-value">
                                <span className="sc-big" style={{ fontSize: '28px' }}>
                                  {result.plan_legibility}
                                </span>
                              </div>
                              <div className="sc-delta">{legDelta(result.plan_legibility)}</div>
                            </div>
                          </div>

                          <div className="buyer-block">
                            <div className="buyer-eyebrow">{'// Who this actually targets'}</div>
                            <p className="buyer-text">{result.buyer_inference}</p>
                          </div>

                          {result.flags.length > 0 && (
                            <>
                              <div className="section-header">
                                <span>{'// Issues found'}</span>
                                <span className="count">{result.flags.length} flagged</span>
                              </div>
                              <div className="flags">
                                {result.flags.map((f, i) => (
                                  <span key={i} className="flag">
                                    {f}
                                  </span>
                                ))}
                              </div>
                            </>
                          )}

                          <div className="section-header">
                            <span>{'// Top 3 improvements'}</span>
                            <span className="count">ranked by impact</span>
                          </div>
                          <div className="improvements">
                            {result.improvements.map((item) => (
                              <ImpCard key={item.rank} item={item} />
                            ))}
                          </div>
                        </div>
                        {/* end resultPanelRef */}

                        <div className="result-footer">
                          <span className="url-pill">
                            <span>{trimUrl(result.url)}</span>
                          </span>
                          <div className="export-actions">
                            <button
                              className={`export-btn${exportState === 'copying' ? 'done' : ''}`}
                              type="button"
                              onClick={handleCopy}
                              disabled={exportState !== 'idle'}
                              title="Copy as text"
                            >
                              {exportState === 'copying' ? (
                                <>
                                  <svg
                                    width="12"
                                    height="12"
                                    viewBox="0 0 24 24"
                                    fill="none"
                                    stroke="currentColor"
                                    strokeWidth="2.5"
                                    strokeLinecap="round"
                                    strokeLinejoin="round"
                                  >
                                    <path d="M20 6L9 17l-5-5" />
                                  </svg>
                                  Copied
                                </>
                              ) : (
                                <>
                                  <svg
                                    width="12"
                                    height="12"
                                    viewBox="0 0 24 24"
                                    fill="none"
                                    stroke="currentColor"
                                    strokeWidth="2"
                                    strokeLinecap="round"
                                    strokeLinejoin="round"
                                  >
                                    <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
                                    <path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1" />
                                  </svg>
                                  Copy
                                </>
                              )}
                            </button>
                            <button
                              className={`export-btn${exportState === 'png' ? 'loading' : ''}`}
                              type="button"
                              onClick={handleDownloadPng}
                              disabled={exportState !== 'idle'}
                              title="Download as PNG"
                            >
                              <svg
                                width="12"
                                height="12"
                                viewBox="0 0 24 24"
                                fill="none"
                                stroke="currentColor"
                                strokeWidth="2"
                                strokeLinecap="round"
                                strokeLinejoin="round"
                              >
                                <rect x="3" y="3" width="18" height="18" rx="2" />
                                <circle cx="8.5" cy="8.5" r="1.5" />
                                <path d="M21 15l-5-5L5 21" />
                              </svg>
                              {exportState === 'png' ? '…' : 'PNG'}
                            </button>
                            <button
                              className={`export-btn${exportState === 'pdf' ? 'loading' : ''}`}
                              type="button"
                              onClick={handleDownloadPdf}
                              disabled={exportState !== 'idle'}
                              title="Download as PDF"
                            >
                              <svg
                                width="12"
                                height="12"
                                viewBox="0 0 24 24"
                                fill="none"
                                stroke="currentColor"
                                strokeWidth="2"
                                strokeLinecap="round"
                                strokeLinejoin="round"
                              >
                                <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z" />
                                <path d="M14 2v6h6" />
                                <path d="M12 18v-6M9 15l3 3 3-3" />
                              </svg>
                              {exportState === 'pdf' ? '…' : 'PDF'}
                            </button>
                            <button className="run-again" type="button" onClick={handleReset}>
                              Run another
                              <svg
                                width="12"
                                height="12"
                                viewBox="0 0 24 24"
                                fill="none"
                                stroke="currentColor"
                                strokeWidth="2.4"
                                strokeLinecap="round"
                                strokeLinejoin="round"
                              >
                                <path d="M5 12h14" />
                                <path d="M13 5l7 7-7 7" />
                              </svg>
                            </button>
                          </div>
                        </div>
                      </>
                    )}
                  </EmailGate>
                )}
              </section>

              {/* ERROR */}
              <section className={`pd-state error-state${appState === 'error' ? 'active' : ''}`}>
                <div className="err-icon">
                  <svg
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.8"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <circle cx="12" cy="12" r="10" />
                    <line x1="5.5" y1="5.5" x2="18.5" y2="18.5" />
                  </svg>
                </div>
                <h2 className="err-title">Analysis failed</h2>
                <p className="err-msg">{errorMsg}</p>
                <button className="err-btn" type="button" onClick={handleReset}>
                  Try again
                </button>
              </section>
            </div>
          </div>
        </div>

        {/* How it works */}
        <section className="how-it-works">
          <div className="hiw-head">
            <span className="hiw-eyebrow">How it works</span>
            <h2>
              From URL to teardown in <span className="accent">under a minute</span>
            </h2>
            <p>No login, no install. Four steps from paste to ranked fixes.</p>
          </div>

          <ol className="hiw-steps">
            <li className="hiw-step" data-side="left">
              <div className="hiw-rail">
                <span className="hiw-dot" />
              </div>
              <div className="hiw-card">
                <span className="hiw-step-label">Step 01</span>
                <div className="hiw-card-row">
                  <div className="hiw-icon" aria-hidden>
                    <svg
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="1.6"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    >
                      <rect x="3" y="5" width="18" height="14" rx="2" />
                      <path d="M3 9h18" />
                      <path d="M7 13h8" />
                    </svg>
                  </div>
                  <div className="hiw-text">
                    <h3>Paste your pricing page URL</h3>
                    <p>
                      Yours, a competitor&apos;s, or any public pricing page you want to benchmark.
                    </p>
                  </div>
                </div>
              </div>
            </li>

            <li className="hiw-step" data-side="right">
              <div className="hiw-rail">
                <span className="hiw-dot" />
              </div>
              <div className="hiw-card">
                <span className="hiw-step-label">Step 02</span>
                <div className="hiw-card-row">
                  <div className="hiw-icon" aria-hidden>
                    <svg
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="1.6"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    >
                      <path d="M3 7l9-4 9 4-9 4-9-4z" />
                      <path d="M3 12l9 4 9-4" />
                      <path d="M3 17l9 4 9-4" />
                    </svg>
                  </div>
                  <div className="hiw-text">
                    <h3>We scrape and parse the page</h3>
                    <p>Plan tiers, CTAs, gates, copy, and trust signals — extracted in seconds.</p>
                  </div>
                </div>
              </div>
            </li>

            <li className="hiw-step" data-side="left">
              <div className="hiw-rail">
                <span className="hiw-dot" />
              </div>
              <div className="hiw-card">
                <span className="hiw-step-label">Step 03</span>
                <div className="hiw-card-row">
                  <div className="hiw-icon" aria-hidden>
                    <svg
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="1.6"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    >
                      <circle cx="12" cy="12" r="3" />
                      <path d="M12 2v3M12 19v3M2 12h3M19 12h3M4.9 4.9l2.1 2.1M17 17l2.1 2.1M4.9 19.1L7 17M17 7l2.1-2.1" />
                    </svg>
                  </div>
                  <div className="hiw-text">
                    <h3>AI evaluates four conversion dimensions</h3>
                    <p>
                      Structure, friction, copy, and signal — scored against what actually converts.
                    </p>
                  </div>
                </div>
              </div>
            </li>

            <li className="hiw-step" data-side="right">
              <div className="hiw-rail">
                <span className="hiw-dot" />
              </div>
              <div className="hiw-card">
                <span className="hiw-step-label">Step 04</span>
                <div className="hiw-card-row">
                  <div className="hiw-icon" aria-hidden>
                    <svg
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="1.6"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    >
                      <path d="M9 11l3 3 8-8" />
                      <path d="M20 12v6a2 2 0 01-2 2H6a2 2 0 01-2-2V6a2 2 0 012-2h9" />
                    </svg>
                  </div>
                  <div className="hiw-text">
                    <h3>Get your scores and the 3 quickest fixes</h3>
                    <p>
                      Friction Score, Clarity Grade, Plan Legibility — plus top improvements ranked
                      by impact.
                    </p>
                  </div>
                </div>
              </div>
            </li>
          </ol>
        </section>
      </main>

      <Footer />
      <PageScripts />
    </div>
  )
}
