/**
 * One canonical builder for the plain text produced by a mini-app's "Copy"
 * button.
 *
 * Every app used to hand-roll its own `'='.repeat(60)` title rule, `// SECTION`
 * eyebrows, and `  · ` bullet prefixes (see `buildPricingDiagnosticPlainText`,
 * `buildJobBriefPlainText`, `buildCrmSanityPlainText`, etc.). Collecting the
 * format here keeps copied output consistent across all 23 apps and matching
 * the branded PNG / PDF export frame.
 *
 * Format (matches the existing dominant style):
 *   - Title line: `${appName} — ${subject}` (or just `appName` if no subject).
 *     The em dash is allowed here because a title is not prose. NEVER use an
 *     em dash in section body text (the guide bans em dashes in user-facing
 *     prose).
 *   - A `'='.repeat(60)` rule, then a blank line.
 *   - Each section: an optional `// HEADING` eyebrow (uppercased), then the
 *     rendered body, with a blank line between sections.
 *       - kv:       aligned `label : value`, labels padded to the longest.
 *       - bullets:  `  · item`
 *       - numbered: `  1. item`
 *       - prose:    word-wrapped paragraph (~72 cols).
 *   - Footer: a blank line, then `Generated by S7 Labs · s7labs.ai/${slug}`.
 */

export type CopySection =
  | { kind: 'kv'; rows: Array<{ label: string; value: string }> }
  | { kind: 'bullets'; items: string[] }
  | { kind: 'numbered'; items: string[] }
  | { kind: 'prose'; text: string }

export type CopyDoc = {
  /** Display name of the app, e.g. 'Pricing Page Diagnostic'. */
  appName: string
  /** What was analyzed (url / company / record). Omitted from the title if absent. */
  subject?: string
  /** App slug, used in the footer link, e.g. 'pricing-diagnostic'. */
  slug: string
  /** Ordered sections; each may carry an optional heading. */
  sections: Array<{ heading?: string } & CopySection>
}

const RULE_WIDTH = 60
const WRAP_WIDTH = 72

/** Word-wrap a paragraph to `width` columns, preserving existing line breaks. */
function wrapProse(text: string, width: number): string[] {
  const out: string[] = []
  for (const rawLine of text.split('\n')) {
    const words = rawLine.split(/\s+/).filter(Boolean)
    if (words.length === 0) {
      out.push('')
      continue
    }
    let line = ''
    for (const word of words) {
      if (line.length === 0) {
        line = word
      } else if (line.length + 1 + word.length <= width) {
        line += ' ' + word
      } else {
        out.push(line)
        line = word
      }
    }
    if (line.length > 0) out.push(line)
  }
  return out
}

/** Render one section body to its lines (no heading, no trailing blank). */
function renderSection(section: { heading?: string } & CopySection): string[] {
  switch (section.kind) {
    case 'kv': {
      const labelWidth = section.rows.reduce((max, row) => Math.max(max, row.label.length), 0)
      return section.rows.map((row) => `${row.label.padEnd(labelWidth)} : ${row.value}`)
    }
    case 'bullets':
      return section.items.map((item) => `  · ${item}`)
    case 'numbered':
      return section.items.map((item, i) => `  ${i + 1}. ${item}`)
    case 'prose':
      return wrapProse(section.text, WRAP_WIDTH)
  }
}

/**
 * Build the canonical plain-text copy output for a mini-app result.
 *
 * @example
 * buildCopyText({
 *   appName: 'Pricing Page Diagnostic',
 *   subject: 'acme.com/pricing',
 *   slug: 'pricing-diagnostic',
 *   sections: [
 *     {
 *       kind: 'kv',
 *       rows: [
 *         { label: 'Friction Score', value: '7/10' },
 *         { label: 'Clarity Grade', value: 'B' },
 *       ],
 *     },
 *     { heading: 'Issues found', kind: 'bullets', items: ['No annual toggle'] },
 *   ],
 * })
 * // Pricing Page Diagnostic — acme.com/pricing
 * // ============================================================
 * //
 * // Friction Score : 7/10
 * // Clarity Grade  : B
 * //
 * // // ISSUES FOUND
 * //   · No annual toggle
 * //
 * // Generated by S7 Labs · s7labs.ai/pricing-diagnostic
 */
export function buildCopyText(doc: CopyDoc): string {
  const lines: string[] = []

  const title = doc.subject ? `${doc.appName} — ${doc.subject}` : doc.appName
  lines.push(title)
  lines.push('='.repeat(RULE_WIDTH))
  lines.push('')

  for (const section of doc.sections) {
    if (section.heading) lines.push(`// ${section.heading.toUpperCase()}`)
    lines.push(...renderSection(section))
    lines.push('')
  }

  lines.push(`Generated by S7 Labs · s7labs.ai/${doc.slug}`)

  return lines.join('\n')
}
