'use client'

import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react'
import { clsx } from 'clsx'
import './page-styles.css'
import { Footer } from '@/components/Footer'
import { Header } from '@/components/Header'
import { AuroraBackground } from '@/components/mini-apps/AuroraBackground'
import { HowItWorks, type HowItWorksStep } from '@/components/mini-apps/HowItWorks'
import { InlineConsentField } from '@/components/mini-apps/InlineConsentField'
import { EMAIL_REGEX } from '@/lib/leads/disposable'
import type { ApiResponse, RadarResult, Signal } from '@/app/api/mini-apps/outbound-radar/route'
import { PageScripts } from './PageScripts'

type AppState = 'idle' | 'loading' | 'result' | 'error'

const RADAR_STEPS: HowItWorksStep[] = [
  {
    title: 'Enter a company name and domain',
    description:
      'That is the entire setup. No API keys, no integrations. Just the company you want to outbound to.',
    icon: (
      <svg
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.6"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <rect x="3" y="5" width="18" height="14" rx="2" />
        <path d="M3 9h18" />
        <path d="M7 13h8" />
      </svg>
    ),
  },
  {
    title: 'We scan the homepage, about, and careers',
    description:
      'Real-time scrape of the surfaces that reveal hiring plans, tech stack, expansion, and recent news.',
    icon: (
      <svg
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.6"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M3 7l9-4 9 4-9 4-9-4z" />
        <path d="M3 12l9 4 9-4" />
        <path d="M3 17l9 4 9-4" />
      </svg>
    ),
  },
  {
    title: 'AI detects buy signals across categories',
    description:
      'Hiring, expansion, tech changes, funding, leadership moves, each ranked by strength and recency.',
    icon: (
      <svg
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.6"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <circle cx="12" cy="12" r="3" />
        <path d="M12 2v3M12 19v3M2 12h3M19 12h3M4.9 4.9l2.1 2.1M17 17l2.1 2.1M4.9 19.1L7 17M17 7l2.1-2.1" />
      </svg>
    ),
  },
  {
    title: 'Get your intent score, urgency, and outreach angle',
    description:
      'A 0–10 intent score, urgency level, the persona to target, and a tailored opener, ready to send.',
    icon: (
      <svg
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.6"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M9 11l3 3 8-8" />
        <path d="M20 12v6a2 2 0 01-2 2H6a2 2 0 01-2-2V6a2 2 0 012-2h9" />
      </svg>
    ),
  },
]

const STAGES = [
  {
    num: '01',
    title: 'Scanning homepage',
    logs: ['GET /', '200 OK · reading content', 'homepage parsed'],
  },
  {
    num: '02',
    title: 'Scraping /about & /careers',
    logs: ['GET /about', 'GET /careers', 'hiring signals extracted'],
  },
  {
    num: '03',
    title: 'Detecting buy signals',
    logs: ['analysing patterns', 'scoring intent signals', 'signals ranked'],
  },
  {
    num: '04',
    title: 'Drafting outreach angle',
    logs: ['profiling buyer persona', 'writing angle', 'brief complete'],
  },
]
const STAGE_MS = 5000

const SIGNAL_ICONS: Record<string, string> = {
  hiring: '👥',
  funding: '💰',
  expansion: '🌍',
  tech: '⚙️',
  news: '📡',
  leadership: '🎯',
}

function fmtTs(d: Date) {
  const p = (n: number) => String(n).padStart(2, '0')
  return `REPORT · ${d.getUTCFullYear()}-${p(d.getUTCMonth() + 1)}-${p(d.getUTCDate())} · ${p(d.getUTCHours())}:${p(d.getUTCMinutes())} UTC`
}

function intentClass(score: number): string {
  if (score >= 7) return 'high'
  if (score >= 4) return 'medium'
  return 'low'
}
function intentDelta(score: number): string {
  if (score >= 7) return 'strong buy signal detected'
  if (score >= 4) return 'moderate activity: worth watching'
  return 'low signal: poor timing'
}
function urgencyDelta(u: string): string {
  if (u === 'high') return 'reach out this week'
  if (u === 'medium') return 'queue for next sprint'
  return 'monitor for 30d'
}

function buildPlainText(r: RadarResult): string {
  return [
    `Outbound Trigger Radar — ${r.company} (${r.domain})`,
    '='.repeat(60),
    '',
    `Intent Score  : ${r.intent_score}/10`,
    `Urgency       : ${r.urgency.toUpperCase()}`,
    '',
    '// OUTREACH ANGLE',
    r.outreach_angle,
    `Best persona  : ${r.best_persona}`,
    '',
    '// SIGNALS DETECTED',
    ...r.signals.map((s) => `  [${s.strength.toUpperCase()}] ${s.label}\n  ${s.detail}`),
    '',
    `Tokens: ${(r.tokens_in + r.tokens_out).toLocaleString()} (${r.tokens_in.toLocaleString()} in / ${r.tokens_out.toLocaleString()} out)`,
    'Generated by S7 Labs Outbound Trigger Radar',
  ].join('\n')
}

function SignalCard({ signal }: { signal: Signal }) {
  return (
    <div className={`signal${signal.strength === 'strong' ? 'strong' : ''}`}>
      <div className="signal-icon">{SIGNAL_ICONS[signal.type] ?? '📌'}</div>
      <div className="signal-body">
        <div className="signal-label">{signal.label}</div>
        <div className="signal-detail">{signal.detail}</div>
      </div>
      <span className={`signal-strength ${signal.strength}`}>{signal.strength}</span>
    </div>
  )
}

export default function OutboundRadarPage() {
  const [appState, setAppState] = useState<AppState>('idle')
  const [company, setCompany] = useState('')
  const [domain, setDomain] = useState('')
  const [companyError, setCompanyError] = useState<string | null>(null)
  const [domainError, setDomainError] = useState<string | null>(null)
  const [shakeCompany, setShakeCompany] = useState(0)
  const [shakeDomain, setShakeDomain] = useState(0)
  const [email, setEmail] = useState('')
  const [emailError, setEmailError] = useState<string | null>(null)
  const [marketingConsent, setMarketingConsent] = useState(false)
  const [shakeEmail, setShakeEmail] = useState(0)
  const [submitting, setSubmitting] = useState(false)
  const [result, setResult] = useState<RadarResult | null>(null)
  const [errorMsg, setErrorMsg] = useState('')
  const [resultTs, setResultTs] = useState('')
  const [exportState, setExportState] = useState<'idle' | 'copying' | 'png' | 'pdf'>('idle')

  const [activeStage, setActiveStage] = useState(-1)
  const [doneStages, setDoneStages] = useState<number[]>([])
  const [stageLogs, setStageLogs] = useState<string[]>(['', '', '', ''])
  const [progressPct, setProgressPct] = useState(0)
  const [loadingPct, setLoadingPct] = useState('0%')
  const [latency, setLatency] = useState('—')
  const [sysState, setSysState] = useState('idle')
  const [clock, setClock] = useState('—')
  const [tokens, setTokens] = useState<{ in: number; out: number } | null>(null)

  const companyInputRef = useRef<HTMLInputElement | null>(null)
  const resultPanelRef = useRef<HTMLDivElement | null>(null)
  const timersRef = useRef<ReturnType<typeof setTimeout>[]>([])
  const rafRef = useRef<number | null>(null)
  const runStartRef = useRef(0)

  useEffect(() => {
    const tick = () => {
      const d = new Date()
      const p = (n: number) => String(n).padStart(2, '0')
      setClock(`${p(d.getUTCHours())}:${p(d.getUTCMinutes())}:${p(d.getUTCSeconds())}Z`)
    }
    tick()
    const id = setInterval(tick, 1000)
    return () => clearInterval(id)
  }, [])

  useEffect(() => {
    if (appState === 'idle') {
      const t = setTimeout(() => companyInputRef.current?.focus(), 200)
      return () => clearTimeout(t)
    }
  }, [appState])

  const clearTimers = useCallback(() => {
    timersRef.current.forEach((t) => clearTimeout(t))
    timersRef.current = []
    if (rafRef.current !== null) {
      cancelAnimationFrame(rafRef.current)
      rafRef.current = null
    }
  }, [])

  useEffect(() => () => clearTimers(), [clearTimers])

  const startLoadingAnimation = useCallback(() => {
    clearTimers()
    setActiveStage(0)
    setDoneStages([])
    setStageLogs(['', '', '', ''])
    setProgressPct(0)
    setLoadingPct('0%')
    setLatency('0.0s')
    const startTime = performance.now()
    runStartRef.current = startTime
    const totalMs = STAGE_MS * STAGES.length

    const tick = (now: number) => {
      const pct = Math.min(98, ((now - startTime) / totalMs) * 100)
      setProgressPct(pct)
      setLoadingPct(Math.floor(pct) + '%')
      setLatency(((now - startTime) / 1000).toFixed(1) + 's')
      if (pct < 98) rafRef.current = requestAnimationFrame(tick)
    }
    rafRef.current = requestAnimationFrame(tick)

    STAGES.forEach((stage, i) => {
      timersRef.current.push(
        setTimeout(() => {
          setActiveStage(i)
          setStageLogs((prev) => {
            const n = [...prev]
            n[i] = stage.logs[0] ?? ''
            return n
          })
          stage.logs.forEach((log, li) => {
            if (li === 0) return
            timersRef.current.push(
              setTimeout(
                () => {
                  setStageLogs((prev) => {
                    const n = [...prev]
                    n[i] = log
                    return n
                  })
                },
                (li * STAGE_MS) / stage.logs.length
              )
            )
          })
        }, i * STAGE_MS)
      )

      timersRef.current.push(
        setTimeout(
          () => {
            setDoneStages((prev) => [...prev, i])
            setStageLogs((prev) => {
              const n = [...prev]
              n[i] = stage.logs[stage.logs.length - 1] ?? ''
              return n
            })
          },
          (i + 1) * STAGE_MS
        )
      )
    })
  }, [clearTimers])

  const handleSubmit = useCallback(
    async (e: FormEvent) => {
      e.preventDefault()
      if (submitting) return
      let valid = true
      if (!company.trim()) {
        setCompanyError('Company name is required.')
        setShakeCompany((k) => k + 1)
        valid = false
      }
      const domainClean = domain
        .trim()
        .replace(/^https?:\/\//, '')
        .replace(/\/.*$/, '')
      if (!domainClean || !/^([a-z0-9-]+\.)+[a-z]{2,}/i.test(domainClean)) {
        setDomainError('Enter a valid domain, e.g. acme.com')
        setShakeDomain((k) => k + 1)
        valid = false
      }
      const emailClean = email.trim().toLowerCase()
      if (!emailClean) {
        setEmailError('Please enter your work email.')
        setShakeEmail((k) => k + 1)
        valid = false
      } else if (!EMAIL_REGEX.test(emailClean)) {
        setEmailError('Please enter a valid email.')
        setShakeEmail((k) => k + 1)
        valid = false
      }
      if (!valid) return

      setCompanyError(null)
      setDomainError(null)
      setEmailError(null)
      setSubmitting(true)
      setResult(null)
      setErrorMsg('')

      // Save the lead first. If validation fails server-side (disposable or
      // free-provider email), bail BEFORE the Anthropic call.
      let submissionId: string | null = null
      try {
        const res = await fetch('/api/leads/submit', {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({
            email: emailClean,
            miniAppSlug: 'outbound-trigger-radar',
            marketingConsent,
            input: { company: company.trim(), domain: domainClean },
          }),
        })
        const json = (await res.json()) as {
          ok: boolean
          submissionId?: string
          error?: string
        }
        if (!res.ok || !json.ok || !json.submissionId) {
          setEmailError(json.error || "Couldn't save your info. Try again.")
          setShakeEmail((k) => k + 1)
          setSubmitting(false)
          return
        }
        submissionId = json.submissionId
      } catch {
        setEmailError("Couldn't save your info. Try again.")
        setShakeEmail((k) => k + 1)
        setSubmitting(false)
        return
      }

      setSysState('running')
      setAppState('loading')
      startLoadingAnimation()

      let data: ApiResponse
      try {
        const res = await fetch('/api/mini-apps/outbound-radar', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ company: company.trim(), domain: domainClean }),
        })
        data = (await res.json()) as ApiResponse
      } catch {
        clearTimers()
        setErrorMsg('Network error. Please check your connection and try again.')
        setSysState('error')
        setAppState('error')
        setSubmitting(false)
        return
      }

      clearTimers()
      const elapsed = ((performance.now() - runStartRef.current) / 1000).toFixed(1) + 's'
      setLatency(elapsed)
      setProgressPct(100)
      setLoadingPct('100%')

      if (data.ok) {
        setDoneStages([0, 1, 2, 3])
        await new Promise((r) => setTimeout(r, 400))
        setResult(data.data)
        setTokens({ in: data.data.tokens_in, out: data.data.tokens_out })
        setResultTs(fmtTs(new Date()))
        setSysState('complete')
        setAppState('result')

        fetch('/api/leads/complete', {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({
            submissionId,
            output: data.data,
            ...(data.cost ? { cost: data.cost } : {}),
          }),
        }).catch((err) => console.error('[outbound-radar] leads/complete', err))
      } else {
        setErrorMsg(data.message)
        setSysState('error')
        setAppState('error')
        fetch('/api/leads/complete', {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({
            submissionId,
            status: 'failed',
            errorMessage: data.message?.slice(0, 500),
          }),
        }).catch((err) => console.error('[outbound-radar] leads/complete fail', err))
      }
      setSubmitting(false)
    },
    [company, domain, email, marketingConsent, submitting, startLoadingAnimation, clearTimers]
  )

  const handleReset = useCallback(() => {
    clearTimers()
    setAppState('idle')
    setResult(null)
    setErrorMsg('')
    setCompanyError(null)
    setDomainError(null)
    setEmailError(null)
    setSubmitting(false)
    setSysState('idle')
    setLatency('—')
    setProgressPct(0)
    setTokens(null)
  }, [clearTimers])

  const handleCopy = useCallback(async () => {
    if (!result) return
    setExportState('copying')
    try {
      await navigator.clipboard.writeText(buildPlainText(result))
    } catch {
      const ta = document.createElement('textarea')
      ta.value = buildPlainText(result)
      ta.style.cssText = 'position:fixed;opacity:0'
      document.body.appendChild(ta)
      ta.select()
      document.execCommand('copy')
      document.body.removeChild(ta)
    }
    setTimeout(() => setExportState('idle'), 1800)
  }, [result])

  const handleDownloadPng = useCallback(async () => {
    if (!resultPanelRef.current || !result) return
    setExportState('png')
    try {
      const { default: html2canvas } = await import('html2canvas')
      const canvas = await html2canvas(resultPanelRef.current, {
        backgroundColor: '#101014',
        scale: 2,
        useCORS: true,
        logging: false,
      })
      const a = document.createElement('a')
      a.download = `radar-${result.domain.replace(/[^a-z0-9]/gi, '-')}.png`
      a.href = canvas.toDataURL('image/png')
      a.click()
    } catch (e) {
      console.error(e)
    }
    setExportState('idle')
  }, [result])

  const handleDownloadPdf = useCallback(async () => {
    if (!resultPanelRef.current || !result) return
    setExportState('pdf')
    try {
      const { default: html2canvas } = await import('html2canvas')
      const { jsPDF } = await import('jspdf')
      const canvas = await html2canvas(resultPanelRef.current, {
        backgroundColor: '#101014',
        scale: 2,
        useCORS: true,
        logging: false,
      })
      const imgW = 190
      const imgH = (canvas.height / canvas.width) * imgW
      const pdf = new jsPDF({ orientation: imgH > imgW ? 'portrait' : 'landscape', unit: 'mm' })
      pdf.addImage(canvas.toDataURL('image/png'), 'PNG', 10, 10, imgW, imgH)
      pdf.save(`radar-${result.domain.replace(/[^a-z0-9]/gi, '-')}.pdf`)
    } catch (e) {
      console.error(e)
    }
    setExportState('idle')
  }, [result])

  const loadingTarget = domain ? domain.replace(/^https?:\/\//, '').replace(/\/.*$/, '') : 'target'

  return (
    <div className="outbound-radar">
      <AuroraBackground />

      <Header />

      <main className="shell">
        <section className="hero">
          <span className="eyebrow">Outbound Trigger Radar</span>
          <h1>
            Know exactly <span className="accent">when to reach out</span> and why.
          </h1>
          <p>
            Enter a company name and domain. We scan their site for buying signals (hiring sprees,
            new products, expansions) and turn them into a scored outreach brief.
          </p>
        </section>

        <div className="panel-wrap">
          <div className="panel">
            {appState !== 'idle' && (
              <div className="panel-readouts">
                <div className="prl">
                  <span>
                    <span className="stat-key">sys</span>{' '}
                    <span className="stat-val">{sysState}</span>
                  </span>
                  <span className="pr-sep hide-sm" />
                  <span className="hide-sm">
                    <span className="stat-key">eng</span> <span className="stat-val">v1.0</span>
                  </span>
                </div>
                <div className="prr">
                  {tokens && (
                    <>
                      <span className="hide-sm">
                        <span className="stat-key">tok</span>{' '}
                        <span className="stat-val">
                          {(tokens.in + tokens.out).toLocaleString()}
                        </span>
                      </span>
                      <span className="pr-sep hide-sm" />
                    </>
                  )}
                  <span className="hide-sm">
                    <span className="stat-key">lat</span>{' '}
                    <span className="stat-val">{latency}</span>
                  </span>
                  <span className="pr-sep hide-sm" />
                  <span>
                    <span className="stat-key">ts</span> <span className="stat-val">{clock}</span>
                  </span>
                </div>
              </div>
            )}

            <div className="panel-body">
              {/* IDLE */}
              <section className={clsx('or-state', { active: appState === 'idle' })}>
                <div className="idle-label">Target account</div>
                <form noValidate onSubmit={handleSubmit} autoComplete="off">
                  <div className="input-grid">
                    <div className="input-field">
                      <label>Company name</label>
                      <div
                        key={`c-${shakeCompany}`}
                        className={clsx('input-box', { error: companyError })}
                      >
                        <input
                          ref={companyInputRef}
                          type="text"
                          placeholder="Acme Corp"
                          value={company}
                          disabled={submitting}
                          onChange={(e) => {
                            setCompany(e.target.value)
                            if (companyError) setCompanyError(null)
                          }}
                        />
                      </div>
                      {companyError && <div className="field-error">{companyError}</div>}
                    </div>
                    <div className="input-field">
                      <label>Domain</label>
                      <div
                        key={`d-${shakeDomain}`}
                        className={clsx('input-box', { error: domainError })}
                      >
                        <input
                          type="text"
                          placeholder="acme.com"
                          value={domain}
                          disabled={submitting}
                          onChange={(e) => {
                            setDomain(e.target.value)
                            if (domainError) setDomainError(null)
                          }}
                        />
                      </div>
                      {domainError && <div className="field-error">{domainError}</div>}
                    </div>
                  </div>
                  <div className="input-field" style={{ marginTop: 14 }}>
                    <label>
                      Work email <span style={{ color: 'var(--error, #ff5c7a)' }}>*</span>
                    </label>
                    <div
                      key={`e-${shakeEmail}`}
                      className={clsx('input-box', { error: emailError })}
                    >
                      <input
                        type="email"
                        inputMode="email"
                        autoComplete="email"
                        placeholder="you@company.com"
                        value={email}
                        disabled={submitting}
                        onChange={(e) => {
                          setEmail(e.target.value)
                          if (emailError) setEmailError(null)
                        }}
                      />
                    </div>
                    {emailError && <div className="field-error">{emailError}</div>}
                  </div>
                  <InlineConsentField
                    checked={marketingConsent}
                    disabled={submitting}
                    onChange={setMarketingConsent}
                  />
                  <div className="submit-row">
                    <button type="submit" className="submit-btn" disabled={submitting}>
                      <svg
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        strokeWidth="2.2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      >
                        <circle cx="11" cy="11" r="8" />
                        <path d="M21 21l-4.35-4.35" />
                      </svg>
                      Run radar scan
                    </button>
                  </div>
                </form>
              </section>

              {/* LOADING */}
              <section className={clsx('or-state', { active: appState === 'loading' })}>
                <div className="progress-track">
                  <div className="progress-bar" style={{ width: `${progressPct}%` }} />
                </div>
                <div className="loading-header">
                  <span>
                    Scanning <strong>{loadingTarget}</strong>
                  </span>
                  <span>{loadingPct}</span>
                </div>
                <div className="stages">
                  {STAGES.map((s, i) => {
                    const isActive = activeStage === i && !doneStages.includes(i)
                    const isDone = doneStages.includes(i)
                    return (
                      <div
                        key={s.num}
                        className={clsx('stage', { active: isActive, done: isDone })}
                      >
                        <div className="stage-num-row">
                          <span>{s.num}</span>
                          <span className="stage-status-icon">
                            <svg viewBox="0 0 12 12" fill="none">
                              <path
                                d="M2 6.5l2.5 2.5L10 3"
                                stroke="currentColor"
                                strokeWidth="2"
                                strokeLinecap="round"
                                strokeLinejoin="round"
                              />
                            </svg>
                          </span>
                        </div>
                        <div className="stage-title">{s.title}</div>
                        <div className="stage-log">{stageLogs[i]}</div>
                      </div>
                    )
                  })}
                </div>
              </section>

              {/* RESULT */}
              <section className={clsx('or-state', { active: appState === 'result' })}>
                {result && (
                  <>
                    <div ref={resultPanelRef}>
                      <div className="result-head">
                        <span className="title">Radar complete: {result.company}</span>
                        <span className="ts-label">{resultTs}</span>
                      </div>

                      <div className="score-row">
                        <div className={`score-card ${intentClass(result.intent_score)}`}>
                          <div className="sc-label">Intent Score</div>
                          <div className="sc-value">
                            <span className="sc-big">{result.intent_score}</span>
                            <span className="sc-small">/10</span>
                          </div>
                          <div className="sc-delta">{intentDelta(result.intent_score)}</div>
                        </div>
                        <div className={`score-card ${result.urgency}`}>
                          <div className="sc-label">Urgency</div>
                          <div className="sc-value">
                            <span
                              className="sc-big"
                              style={{ fontSize: '32px', textTransform: 'capitalize' }}
                            >
                              {result.urgency}
                            </span>
                          </div>
                          <div className="sc-delta">{urgencyDelta(result.urgency)}</div>
                        </div>
                        <div className="score-card medium">
                          <div className="sc-label">Signals</div>
                          <div className="sc-value">
                            <span className="sc-big">{result.signals.length}</span>
                          </div>
                          <div className="sc-delta">
                            {result.signals.filter((s) => s.strength === 'strong').length} strong
                            detected
                          </div>
                        </div>
                      </div>

                      <div className="angle-block">
                        <div className="angle-eyebrow">{'// Outreach angle'}</div>
                        <p className="angle-text">{result.outreach_angle}</p>
                        <div className="persona-row">
                          Best first contact: <strong>{result.best_persona}</strong>
                        </div>
                      </div>

                      <div className="section-header">
                        <span>{'// Buy signals detected'}</span>
                        <span className="count">{result.signals.length} found</span>
                      </div>
                      <div className="signals">
                        {result.signals.map((s, i) => (
                          <SignalCard key={i} signal={s} />
                        ))}
                      </div>
                    </div>

                    <div className="result-footer">
                      <span className="url-pill">
                        <span>{result.domain}</span>
                      </span>
                      <div className="export-actions">
                        <button
                          className={`export-btn${exportState === 'copying' ? 'done' : ''}`}
                          type="button"
                          onClick={handleCopy}
                          disabled={exportState !== 'idle'}
                        >
                          {exportState === 'copying' ? (
                            <>
                              <svg
                                width="12"
                                height="12"
                                viewBox="0 0 24 24"
                                fill="none"
                                stroke="currentColor"
                                strokeWidth="2.5"
                                strokeLinecap="round"
                                strokeLinejoin="round"
                              >
                                <path d="M20 6L9 17l-5-5" />
                              </svg>
                              Copied
                            </>
                          ) : (
                            <>
                              <svg
                                width="12"
                                height="12"
                                viewBox="0 0 24 24"
                                fill="none"
                                stroke="currentColor"
                                strokeWidth="2"
                                strokeLinecap="round"
                                strokeLinejoin="round"
                              >
                                <rect x="9" y="9" width="13" height="13" rx="2" />
                                <path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1" />
                              </svg>
                              Copy
                            </>
                          )}
                        </button>
                        <button
                          className={`export-btn${exportState === 'png' ? 'loading' : ''}`}
                          type="button"
                          onClick={handleDownloadPng}
                          disabled={exportState !== 'idle'}
                        >
                          <svg
                            width="12"
                            height="12"
                            viewBox="0 0 24 24"
                            fill="none"
                            stroke="currentColor"
                            strokeWidth="2"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                          >
                            <rect x="3" y="3" width="18" height="18" rx="2" />
                            <circle cx="8.5" cy="8.5" r="1.5" />
                            <path d="M21 15l-5-5L5 21" />
                          </svg>
                          {exportState === 'png' ? '…' : 'PNG'}
                        </button>
                        <button
                          className={`export-btn${exportState === 'pdf' ? 'loading' : ''}`}
                          type="button"
                          onClick={handleDownloadPdf}
                          disabled={exportState !== 'idle'}
                        >
                          <svg
                            width="12"
                            height="12"
                            viewBox="0 0 24 24"
                            fill="none"
                            stroke="currentColor"
                            strokeWidth="2"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                          >
                            <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z" />
                            <path d="M14 2v6h6" />
                            <path d="M12 18v-6M9 15l3 3 3-3" />
                          </svg>
                          {exportState === 'pdf' ? '…' : 'PDF'}
                        </button>
                        <button className="run-again" type="button" onClick={handleReset}>
                          Scan another
                          <svg
                            width="12"
                            height="12"
                            viewBox="0 0 24 24"
                            fill="none"
                            stroke="currentColor"
                            strokeWidth="2.4"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                          >
                            <path d="M5 12h14" />
                            <path d="M13 5l7 7-7 7" />
                          </svg>
                        </button>
                      </div>
                    </div>
                  </>
                )}
              </section>

              {/* ERROR */}
              <section
                className={clsx('or-state', 'error-state', { active: appState === 'error' })}
              >
                <div className="err-icon">
                  <svg
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.8"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <circle cx="12" cy="12" r="10" />
                    <line x1="5.5" y1="5.5" x2="18.5" y2="18.5" />
                  </svg>
                </div>
                <h2 className="err-title">Scan failed</h2>
                <p className="err-msg">{errorMsg}</p>
                <button className="err-btn" type="button" onClick={handleReset}>
                  Try again
                </button>
              </section>
            </div>
          </div>
        </div>

        <HowItWorks
          title={
            <>
              From company name to <span className="accent">ranked buy signals</span>
            </>
          }
          subtitle="No login, no install. Four steps from input to a ready-to-send outreach angle."
          steps={RADAR_STEPS}
        />
      </main>

      <Footer />
      <PageScripts />
    </div>
  )
}
