'use client'

import type { ReactNode } from 'react'
import type {
  BlueprintResult,
  BlueprintStep,
  ToolOption,
} from '@/app/api/mini-apps/automation-blueprint/route'
import '../page-styles.css'

export type AutomationBlueprintInput = { process?: string; process_description?: string }
export type AutomationBlueprintOutput = BlueprintResult

type Props = {
  input: AutomationBlueprintInput
  output: AutomationBlueprintOutput
  /**
   * When true, render only the inner result body without the surrounding
   * `.automation-blueprint / .panel-wrap / .panel / .panel-body / .ab-state`
   * wrappers or the `.result-footer`. The inline mini-app page provides
   * those itself, plus the interactive BlueprintDiagram, config-section,
   * and export buttons. The standalone `/results/[id]` route uses the
   * default (full) render with pure fallbacks.
   */
  bare?: boolean
  /**
   * Optional render slot for the live Mermaid diagram. The inline page
   * passes a `<BlueprintDiagram />` here so the rendered SVG (and any
   * fallback to a plain `<pre>`) stays at page level alongside the
   * `setDiagramFailed` state. When omitted (standalone), the body falls
   * back to a `<pre>` of the raw mermaid source if present.
   */
  diagramSlot?: ReactNode
  /**
   * Optional render slot for the starter-config block. The inline page
   * passes an interactive collapsible with a copy button; standalone
   * falls back to a static `<pre>` block.
   */
  configSlot?: ReactNode
}

export function fitBadgeClass(score: number): string {
  if (score >= 7) return 'high'
  if (score >= 4) return 'mid'
  return 'low'
}

export function difficultyClass(d: string): string {
  if (d === 'Beginner') return 'is-beginner'
  if (d === 'Advanced') return 'is-advanced'
  return 'is-intermediate'
}

export function prettyConfigJson(raw: string): string {
  try {
    return JSON.stringify(JSON.parse(raw), null, 2)
  } catch {
    return raw
  }
}

export function buildAutomationBlueprintPlainText(r: BlueprintResult): string {
  return [
    `Automation Blueprint — ${r.process_name}`,
    '='.repeat(60),
    '',
    r.one_liner,
    '',
    `Time saved (est.): ${r.current_state.time_saved_per_week}/week · ${r.current_state.time_saved_per_year}/year`,
    `Manual steps: ${r.current_state.steps_count} · ${r.current_state.frequency} · ${r.current_state.time_per_run}/run`,
    `Difficulty: ${r.difficulty} (${r.difficulty_score}/10)`,
    `Recommended: ${r.recommended_tool}`,
    '',
    '// STEPS',
    ...r.steps.map(
      (s) =>
        `${String(s.step).padStart(2, '0')}. ${s.title} [${s.tool}] ${s.automatable ? 'Auto' : 'Manual'}\n   ${s.description}`
    ),
    '',
    '// MERMAID',
    r.mermaid,
    '',
    '// GOTCHAS',
    ...r.gotchas.map((g, i) => `  ${i + 1}. ${g}`),
    '',
    `Tokens: ${(r.tokens_in + r.tokens_out).toLocaleString()}`,
    'Generated by S7 Labs Automation Blueprint',
  ].join('\n')
}

function StatMini({
  label,
  value,
  valueClass,
}: {
  label: string
  value: string
  valueClass?: string
}) {
  return (
    <div className="stat-mini">
      <span className="stat-label">{label}</span>
      <span className={`stat-value${valueClass ? ` ${valueClass}` : ''}`}>{value}</span>
    </div>
  )
}

function StepCard({ step }: { step: BlueprintStep }) {
  return (
    <div className="step-card">
      <div className="step-card-header">
        <span className="step-number">{String(step.step).padStart(2, '0')}</span>
        <span className="step-title">{step.title}</span>
        <span className="tool-badge">{step.tool}</span>
      </div>
      <p className="step-description">{step.description}</p>
      <span className={step.automatable ? 'auto-tag' : 'manual-tag'}>
        {step.automatable ? 'Auto' : 'Manual'}
      </span>
    </div>
  )
}

function ToolCard({ tool, recommended }: { tool: ToolOption; recommended: boolean }) {
  return (
    <div className={`tool-card${recommended ? 'is-recommended' : ''}`}>
      {recommended && <span className="recommended-pill">Recommended</span>}
      <div className="tool-card-header">
        <span className="tool-name">{tool.name}</span>
        <span className={`fit-badge ${fitBadgeClass(tool.fit_score)}`}>{tool.fit_score}/10</span>
      </div>
      <p className="tool-why">{tool.why}</p>
      <p className="tool-best-for">{tool.best_for}</p>
      <p className="tool-pricing">{tool.pricing_note}</p>
    </div>
  )
}

function StaticConfigBlock({ output }: { output: BlueprintResult }) {
  return (
    <div className="config-section">
      <div className="config-toggle" aria-expanded>
        <span>{'// starter config'}</span>
        <span className="config-platform">{output.starter_config.platform}</span>
      </div>
      <div className="config-block">
        <div className="config-block-header">
          <span className="config-hint">Scaffold only. Not import-ready</span>
        </div>
        <pre className="config-code">
          <code>{prettyConfigJson(output.starter_config.json)}</code>
        </pre>
        <p className="config-note">{output.starter_config.note}</p>
      </div>
    </div>
  )
}

function StaticDiagramBlock({ output }: { output: BlueprintResult }) {
  if (!output.mermaid) return null
  return (
    <>
      <div className="section-header">
        <span>{'// The blueprint'}</span>
      </div>
      <div className="blueprint-panel">
        <pre className="config-code">
          <code>{output.mermaid}</code>
        </pre>
      </div>
    </>
  )
}

function ResultBody({
  output,
  diagramSlot,
  configSlot,
}: {
  output: AutomationBlueprintOutput
  diagramSlot?: ReactNode
  configSlot?: ReactNode
}) {
  return (
    <>
      <div className="one-liner-block">
        <p className="one-liner-text">&ldquo;{output.one_liner}&rdquo;</p>
        <div className="one-liner-meta">
          <span className="process-name">{output.process_name}</span>
          <span className="freq-pill">{output.current_state.frequency}</span>
        </div>
        <p className="estimate-note">Time saved figures are estimates, not guarantees.</p>
      </div>

      <div className="stats-row">
        <div className="score-card time-saved-card">
          <div className="sc-label">Time saved (est.)</div>
          <div className="sc-value">
            <span className="sc-big">{output.current_state.time_saved_per_week}</span>
          </div>
          <div className="sc-delta">{output.current_state.time_saved_per_year}/year</div>
        </div>
        <div className="score-card glance-card">
          <div className="sc-label">At a glance</div>
          <div className="stat-grid">
            <StatMini label="Manual steps" value={String(output.current_state.steps_count)} />
            <StatMini label="Frequency" value={output.current_state.frequency} />
            <StatMini
              label="Difficulty"
              value={output.difficulty}
              valueClass={`difficulty-badge ${difficultyClass(output.difficulty)}`}
            />
            <StatMini label="Recommended" value={output.recommended_tool} />
          </div>
        </div>
      </div>

      {diagramSlot ?? <StaticDiagramBlock output={output} />}

      <div className="section-header">
        <span>{'// Step breakdown'}</span>
        <span>{output.steps.length} steps</span>
      </div>
      <div className="step-grid">
        {output.steps.map((step) => (
          <StepCard key={step.step} step={step} />
        ))}
      </div>

      <div className="section-header">
        <span>{'// Tool options'}</span>
      </div>
      <div className="tool-row">
        {output.tool_options.map((tool) => (
          <ToolCard
            key={tool.name}
            tool={tool}
            recommended={tool.name === output.recommended_tool}
          />
        ))}
      </div>

      {configSlot ?? <StaticConfigBlock output={output} />}

      <div className="gotchas-block">
        <div className="gotchas-eyebrow">{'// watch out for these'}</div>
        <ol className="gotchas-list">
          {output.gotchas.map((g, i) => (
            <li key={i} className="gotcha-row">
              <span className="gotcha-number">{String(i + 1).padStart(2, '0')}</span>
              <span className="gotcha-text">{g}</span>
            </li>
          ))}
        </ol>
      </div>
    </>
  )
}

export function AutomationBlueprintResult({
  input,
  output,
  bare = false,
  diagramSlot,
  configSlot,
}: Props) {
  void input
  if (bare) {
    return <ResultBody output={output} diagramSlot={diagramSlot} configSlot={configSlot} />
  }
  return (
    <div className="automation-blueprint">
      <div className="panel-wrap panel-wrap-wide">
        <div className="panel">
          <span className="corner tl" />
          <span className="corner tr" />
          <span className="corner bl" />
          <span className="corner br" />
          <div className="panel-body">
            <section className="ab-state active">
              <ResultBody output={output} diagramSlot={diagramSlot} configSlot={configSlot} />
            </section>
          </div>
        </div>
      </div>
    </div>
  )
}
