'use client'

import type { DiagnosticResult, Improvement } from '@/app/api/mini-apps/pricing-diagnostic/route'
import '../page-styles.css'

export type PricingDiagnosticInput = { url: string }
export type PricingDiagnosticOutput = DiagnosticResult

type Props = {
  input: PricingDiagnosticInput
  output: PricingDiagnosticOutput
  /**
   * When true, render only the inner result body (head + scores + buyer +
   * flags + improvements) without the surrounding `.pricing-diag /
   * .panel-wrap / .panel / .panel-body / .pd-state.active` wrappers or the
   * `.result-footer`. The inline mini-app page provides those itself and
   * needs to keep its own export buttons in the footer, so it consumes the
   * component in bare mode. The standalone `/results/[id]` route uses the
   * default (full) render.
   */
  bare?: boolean
  /**
   * Override the `REPORT` label on the result head. The inline mini-app
   * page passes a formatted timestamp like
   * `REPORT · 2026-06-10 · 14:32 UTC`.
   */
  tsLabel?: string
}

export function trimUrl(u: string): string {
  try {
    const url = new URL(u)
    return (url.host + url.pathname).replace(/\/$/, '')
  } catch {
    return u.replace(/^https?:\/\//, '').replace(/\/$/, '')
  }
}

export function buildPricingDiagnosticPlainText(r: DiagnosticResult): string {
  const lines: string[] = [
    `Pricing Page Diagnostic for ${r.url}`,
    '='.repeat(60),
    '',
    `Friction Score  : ${r.friction_score}/10`,
    `Clarity Grade   : ${r.clarity_grade}`,
    `Plan Legibility : ${r.plan_legibility}`,
    '',
    '// WHO THIS ACTUALLY TARGETS',
    r.buyer_inference,
    '',
    '// ISSUES FOUND',
    ...r.flags.map((f) => `  · ${f}`),
    '',
    '// TOP 3 IMPROVEMENTS',
    ...r.improvements.map(
      (imp) => `  ${imp.rank}. [${imp.impact.toUpperCase()}] ${imp.title}\n     ${imp.description}`
    ),
    '',
    `Tokens used: ${(r.tokens_in + r.tokens_out).toLocaleString()} (${r.tokens_in.toLocaleString()} in / ${r.tokens_out.toLocaleString()} out)`,
    `Generated by S7 Labs Pricing Page Diagnostic`,
  ]
  return lines.join('\n')
}

function frictionClass(score: number): string {
  if (score <= 3) return 'good'
  if (score <= 6) return 'mid'
  return 'bad'
}

function gradeClass(grade: string): string {
  if (grade.startsWith('A')) return 'good'
  if (grade.startsWith('B')) return 'good'
  if (grade.startsWith('C')) return 'mid'
  return 'bad'
}

function legibilityClass(leg: string): string {
  if (leg === 'Excellent') return 'good'
  if (leg === 'Good') return 'good'
  if (leg === 'Fair') return 'mid'
  return 'bad'
}

function frictionDelta(score: number): string {
  if (score <= 3) return 'low: smooth buyer path'
  if (score <= 6) return 'moderate: some friction'
  return 'high: buyer drop-off likely'
}

function gradeDelta(grade: string): string {
  if (grade.startsWith('A')) return 'clear value communication'
  if (grade.startsWith('B')) return 'mostly clear, minor gaps'
  if (grade.startsWith('C')) return 'mixed signals to first-time visitors'
  return 'confusing: needs rework'
}

function legDelta(leg: string): string {
  if (leg === 'Excellent') return 'tiers and gating are crystal clear'
  if (leg === 'Good') return 'plans readable, minor issues'
  if (leg === 'Fair') return 'tiers parse, gating unclear'
  return 'hard to compare plans'
}

function ImpCard({ item }: { item: Improvement }) {
  return (
    <article className={`imp${item.rank === 1 ? 'top' : ''}`}>
      <div className="rank">0{item.rank}</div>
      <div className="imp-body">
        <h3>{item.title}</h3>
        <p>{item.description}</p>
      </div>
      <span className={`impact ${item.impact}`}>{item.impact}</span>
    </article>
  )
}

function ResultBody({
  output,
  tsLabel = 'REPORT',
}: {
  output: PricingDiagnosticOutput
  tsLabel?: string
}) {
  return (
    <>
      <div className="result-head">
        <span className="title">Diagnostic complete</span>
        <span className="ts-label">{tsLabel}</span>
      </div>

      <div className="score-row">
        <div className={`score-card ${frictionClass(output.friction_score)}`}>
          <div className="sc-label">Friction Score</div>
          <div className="sc-value">
            <span className="sc-big">{output.friction_score}</span>
            <span className="sc-small">/10</span>
          </div>
          <div className="sc-delta">{frictionDelta(output.friction_score)}</div>
        </div>
        <div className={`score-card ${gradeClass(output.clarity_grade)}`}>
          <div className="sc-label">Clarity Grade</div>
          <div className="sc-value">
            <span className="sc-big">{output.clarity_grade}</span>
          </div>
          <div className="sc-delta">{gradeDelta(output.clarity_grade)}</div>
        </div>
        <div className={`score-card ${legibilityClass(output.plan_legibility)}`}>
          <div className="sc-label">Plan Legibility</div>
          <div className="sc-value">
            <span className="sc-big" style={{ fontSize: '28px' }}>
              {output.plan_legibility}
            </span>
          </div>
          <div className="sc-delta">{legDelta(output.plan_legibility)}</div>
        </div>
      </div>

      <div className="buyer-block">
        <div className="buyer-eyebrow">{'// Who this actually targets'}</div>
        <p className="buyer-text">{output.buyer_inference}</p>
      </div>

      {output.flags.length > 0 && (
        <>
          <div className="section-header">
            <span>{'// Issues found'}</span>
            <span className="count">{output.flags.length} flagged</span>
          </div>
          <div className="flags">
            {output.flags.map((f, i) => (
              <span key={i} className="flag">
                {f}
              </span>
            ))}
          </div>
        </>
      )}

      <div className="section-header">
        <span>{'// Top 3 improvements'}</span>
        <span className="count">ranked by impact</span>
      </div>
      <div className="improvements">
        {output.improvements.map((item) => (
          <ImpCard key={item.rank} item={item} />
        ))}
      </div>
    </>
  )
}

export function PricingDiagnosticResult({ input, output, bare = false, tsLabel }: Props) {
  const url = output.url ?? input.url
  if (bare) {
    return <ResultBody output={output} tsLabel={tsLabel} />
  }
  return (
    <div className="pricing-diag">
      <div className="panel-wrap">
        <div className="panel">
          <div className="panel-body">
            <section className="pd-state active">
              <div>
                <ResultBody output={output} tsLabel={tsLabel} />
              </div>

              <div className="result-footer">
                <span className="url-pill">
                  <span>{trimUrl(url)}</span>
                </span>
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>
  )
}
