'use client'

import type { BriefResult, Signal } from '@/app/api/mini-apps/job-brief/route'
import '../page-styles.css'

export type JobBriefInput = { url?: string; text?: string }
export type JobBriefOutput = BriefResult

type Tokens = { in: number; out: number }

type Props = {
  input: JobBriefInput
  output: JobBriefOutput
  /**
   * When true, render only the inner result body (head + summary + angle +
   * tag clouds + signals) without the surrounding `.job-brief / .panel-wrap /
   * .panel / .panel-body / .jb-state` wrappers or the `.result-footer`. The
   * inline mini-app page provides those itself and keeps its own export
   * buttons in the footer, so it consumes the component in bare mode. The
   * standalone `/results/[id]` route uses the default (full) render.
   */
  bare?: boolean
  /**
   * Override the `BRIEF` label on the result head. The inline mini-app page
   * passes a formatted timestamp like `BRIEF · 2026-06-10 · 14:32 UTC`.
   */
  tsLabel?: string
  /**
   * Optional token usage for the footer pill. Only the inline (full) render
   * uses the footer; bare mode ignores this.
   */
  tokens?: Tokens | null
}

export const SIGNAL_ICONS: Record<string, string> = {
  priority: '🎯',
  pain: '⚡',
  tech: '⚙️',
  budget: '💰',
  team: '👥',
  timing: '🕐',
}

export const SENIORITY_LABEL: Record<string, string> = {
  ic: 'Individual Contributor',
  lead: 'Tech Lead',
  manager: 'Manager',
  director: 'Director',
  vp: 'VP',
  'c-suite': 'C-Suite',
}

export function buildJobBriefPlainText(r: BriefResult): string {
  return [
    `Job Posting to Sales Brief — ${r.company}`,
    '='.repeat(60),
    '',
    `Role      : ${r.role}`,
    `Department: ${r.department} · ${SENIORITY_LABEL[r.seniority] ?? r.seniority}`,
    `Urgency   : ${r.urgency.toUpperCase()}`,
    '',
    '// EXECUTIVE SUMMARY',
    r.summary,
    '',
    '// BEST SALES ANGLE',
    r.best_angle,
    `Ideal contact: ${r.ideal_contact}`,
    '',
    '// TECH STACK',
    r.tech_stack.join(', '),
    '',
    '// PAIN POINTS',
    ...r.pain_points.map((p) => `  · ${p}`),
    '',
    '// BUDGET INDICATORS',
    ...r.budget_indicators.map((b) => `  · ${b}`),
    '',
    '// SIGNALS',
    ...r.signals.map((s) => `  [${s.category.toUpperCase()}] ${s.label}\n  ${s.detail}`),
    '',
    `Tokens: ${(r.tokens_in + r.tokens_out).toLocaleString()} (${r.tokens_in.toLocaleString()} in / ${r.tokens_out.toLocaleString()} out)`,
    'Generated by S7 Labs Job Posting to Sales Brief',
  ].join('\n')
}

export function SignalCard({ signal }: { signal: Signal }) {
  return (
    <div className="signal">
      <div className="signal-icon">{SIGNAL_ICONS[signal.category] ?? '📌'}</div>
      <div className="signal-body">
        <div className="signal-label">{signal.label}</div>
        <div className="signal-detail">{signal.detail}</div>
      </div>
      <span className={`signal-cat ${signal.category}`}>{signal.category}</span>
    </div>
  )
}

function ResultBody({ output, tsLabel = 'BRIEF' }: { output: JobBriefOutput; tsLabel?: string }) {
  return (
    <>
      <div className="result-head">
        <span className="title">Brief ready: {output.company}</span>
        <span className="ts-label">{tsLabel}</span>
      </div>

      <div className="summary-block">
        <div className="summary-eyebrow">
          {'// Executive summary'}
          <div className="role-badges">
            <span className={`badge urgency-${output.urgency}`}>{output.urgency} urgency</span>
            <span className="badge dept">{output.department}</span>
            <span className="badge">{SENIORITY_LABEL[output.seniority] ?? output.seniority}</span>
          </div>
        </div>
        <p className="summary-text">{output.summary}</p>
      </div>

      <div className="angle-block">
        <div className="angle-eyebrow">{'// Best sales angle'}</div>
        <p className="angle-text">{output.best_angle}</p>
        <div className="contact-row">
          Ideal first contact: <strong>{output.ideal_contact}</strong>
        </div>
      </div>

      {output.tech_stack.length > 0 && (
        <>
          <div className="section-header">
            <span>{'// Tech stack'}</span>
            <span>{output.tech_stack.length} tools</span>
          </div>
          <div className="tag-cloud">
            {output.tech_stack.map((t) => (
              <span key={t} className="tag tech">
                {t}
              </span>
            ))}
          </div>
        </>
      )}

      {output.pain_points.length > 0 && (
        <>
          <div className="section-header">
            <span>{'// Implied pain points'}</span>
          </div>
          <div className="tag-cloud">
            {output.pain_points.map((p) => (
              <span key={p} className="tag pain">
                {p}
              </span>
            ))}
          </div>
        </>
      )}

      {output.budget_indicators.length > 0 && (
        <>
          <div className="section-header">
            <span>{'// Budget indicators'}</span>
          </div>
          <div className="tag-cloud" style={{ marginBottom: '20px' }}>
            {output.budget_indicators.map((b) => (
              <span key={b} className="tag budget">
                {b}
              </span>
            ))}
          </div>
        </>
      )}

      <div className="section-header">
        <span>{'// Sales signals'}</span>
        <span>{output.signals.length} found</span>
      </div>
      <div className="signals">
        {output.signals.map((s, i) => (
          <SignalCard key={i} signal={s} />
        ))}
      </div>
    </>
  )
}

export function JobBriefResult({ input, output, bare = false, tsLabel, tokens }: Props) {
  void input
  if (bare) {
    return <ResultBody output={output} tsLabel={tsLabel} />
  }
  const totalTokens = tokens
    ? `${(tokens.in + tokens.out).toLocaleString()} tokens · ${tokens.in.toLocaleString()} in / ${tokens.out.toLocaleString()} out`
    : `${(output.tokens_in + output.tokens_out).toLocaleString()} tokens · ${output.tokens_in.toLocaleString()} in / ${output.tokens_out.toLocaleString()} out`
  return (
    <div className="job-brief">
      <div className="panel-wrap">
        <div className="panel">
          <div className="panel-body">
            <section className="jb-state active">
              <div>
                <ResultBody output={output} tsLabel={tsLabel} />
              </div>
              <div className="result-footer">
                <span className="token-pill">{totalTokens}</span>
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>
  )
}
