'use client'

import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react'
import { clsx } from 'clsx'
import './page-styles.css'
import { Footer } from '@/components/Footer'
import { Header } from '@/components/Header'
import { AuroraBackground } from '@/components/mini-apps/AuroraBackground'
import { EmailGate } from '@/components/mini-apps/EmailGate'
import { HowItWorks, type HowItWorksStep } from '@/components/mini-apps/HowItWorks'
import { SubmitOnce } from '@/components/mini-apps/SubmitOnce'
import type { ApiResponse, Hook, HookResult } from '@/app/api/mini-apps/linkedin-hook/route'
import { PageScripts } from './PageScripts'

type AppState = 'idle' | 'loading' | 'result' | 'error'

const HOOK_STEPS: HowItWorksStep[] = [
  {
    title: 'Paste a LinkedIn post',
    description:
      'Any public post — yours, your prospect’s, or a thought-leader you want to bring into your outreach.',
    icon: (
      <svg
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.6"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <rect x="3" y="3" width="18" height="18" rx="2" />
        <path d="M8 11v6M8 7h.01M12 17v-4M16 17v-3a2 2 0 10-4 0" />
      </svg>
    ),
  },
  {
    title: 'We extract the trigger, author, and signals',
    description:
      'Opinion, news, pain, or achievement — the specific moment in the post that creates an opening for outreach.',
    icon: (
      <svg
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.6"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M3 7l9-4 9 4-9 4-9-4z" />
        <path d="M3 12l9 4 9-4" />
        <path d="M3 17l9 4 9-4" />
      </svg>
    ),
  },
  {
    title: 'AI generates personalized outbound hooks',
    description:
      'Each hook uses a different tone and channel — LinkedIn DM, email, or cold call — mapped to the buyer persona.',
    icon: (
      <svg
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.6"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <circle cx="12" cy="12" r="3" />
        <path d="M12 2v3M12 19v3M2 12h3M19 12h3M4.9 4.9l2.1 2.1M17 17l2.1 2.1M4.9 19.1L7 17M17 7l2.1-2.1" />
      </svg>
    ),
  },
  {
    title: 'Get hooks ranked by reply likelihood',
    description:
      'The hook most likely to land is flagged first so you can send it without second-guessing.',
    icon: (
      <svg
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.6"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M9 11l3 3 8-8" />
        <path d="M20 12v6a2 2 0 01-2 2H6a2 2 0 01-2-2V6a2 2 0 012-2h9" />
      </svg>
    ),
  },
]

const STAGES = [
  {
    num: '01',
    title: 'Reading the post',
    logs: ['parsing text', 'extracting context', 'content ready'],
  },
  {
    num: '02',
    title: 'Identifying trigger',
    logs: ['scanning for signals', 'classifying intent', 'trigger found'],
  },
  {
    num: '03',
    title: 'Profiling persona',
    logs: ['mapping buyer role', 'scoring fit', 'persona locked'],
  },
  {
    num: '04',
    title: 'Writing hooks',
    logs: ['drafting angles', 'crafting openers', 'hooks ready'],
  },
]
const STAGE_MS = 4000

const CHANNEL_LABEL: Record<string, string> = {
  'linkedin-dm': 'LinkedIn DM',
  email: 'Email',
  'cold-call': 'Cold Call',
}
const CHANNEL_CLASS: Record<string, string> = {
  'linkedin-dm': 'channel-li',
  email: 'channel-email',
  'cold-call': 'channel-call',
}

function fmtTs(d: Date) {
  const p = (n: number) => String(n).padStart(2, '0')
  return `REPORT · ${d.getUTCFullYear()}-${p(d.getUTCMonth() + 1)}-${p(d.getUTCDate())} · ${p(d.getUTCHours())}:${p(d.getUTCMinutes())} UTC`
}

function buildPlainText(r: HookResult): string {
  return [
    `LinkedIn Post to Outbound Hook`,
    '='.repeat(60),
    '',
    `Author   : ${r.post_author}`,
    `Trigger  : ${r.trigger}`,
    `Type     : ${r.trigger_type}`,
    `Persona  : ${r.target_persona}`,
    '',
    '// HOOKS',
    ...r.hooks.map((h, i) =>
      [
        `[Hook ${i + 1}${i === r.best_hook_index ? ' — BEST' : ''}] ${h.angle} · ${CHANNEL_LABEL[h.channel] ?? h.channel}`,
        `Opening : ${h.opening_line}`,
        `Follow-up: ${h.follow_up}`,
      ].join('\n')
    ),
    '',
    `Tokens: ${(r.tokens_in + r.tokens_out).toLocaleString()} (${r.tokens_in.toLocaleString()} in / ${r.tokens_out.toLocaleString()} out)`,
    'Generated by S7 Labs LinkedIn Post to Outbound Hook',
  ].join('\n')
}

function HookCard({ hook, isBest }: { hook: Hook; isBest: boolean }) {
  const [copied, setCopied] = useState(false)

  const handleCopy = useCallback(async () => {
    const text = `${hook.opening_line}\n\n${hook.follow_up}`
    try {
      await navigator.clipboard.writeText(text)
    } catch {
      const ta = document.createElement('textarea')
      ta.value = text
      ta.style.cssText = 'position:fixed;opacity:0'
      document.body.appendChild(ta)
      ta.select()
      document.execCommand('copy')
      document.body.removeChild(ta)
    }
    setCopied(true)
    setTimeout(() => setCopied(false), 1800)
  }, [hook])

  return (
    <div className={`hook-card${isBest ? 'best' : ''}`}>
      <div className="hook-card-header">
        <span className="hook-angle">{`// ${hook.angle}`}</span>
        <div className="hook-badges">
          {isBest && <span className="badge best-badge">Best</span>}
          <span className={`badge ${CHANNEL_CLASS[hook.channel] ?? ''}`}>
            {CHANNEL_LABEL[hook.channel] ?? hook.channel}
          </span>
          <span className="badge">{hook.tone}</span>
        </div>
      </div>
      <button
        type="button"
        className={`hook-copy-btn${copied ? 'copied' : ''}`}
        onClick={handleCopy}
        aria-label="Copy hook"
      >
        {copied ? (
          <>
            <svg
              width="10"
              height="10"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2.5"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path d="M20 6L9 17l-5-5" />
            </svg>
            Copied
          </>
        ) : (
          <>
            <svg
              width="10"
              height="10"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <rect x="9" y="9" width="13" height="13" rx="2" />
              <path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1" />
            </svg>
            Copy
          </>
        )}
      </button>
      <p className="hook-opening">{hook.opening_line}</p>
      <div className="hook-followup-label">{'// Follow-up'}</div>
      <p className="hook-followup">{hook.follow_up}</p>
    </div>
  )
}

export default function LinkedInHookPage() {
  const [appState, setAppState] = useState<AppState>('idle')
  const [postText, setPostText] = useState('')
  const [postError, setPostError] = useState<string | null>(null)
  const [shakePost, setShakePost] = useState(0)
  const [submitting, setSubmitting] = useState(false)
  const [result, setResult] = useState<HookResult | null>(null)
  const [errorMsg, setErrorMsg] = useState('')
  const [resultTs, setResultTs] = useState('')
  const [exportState, setExportState] = useState<'idle' | 'copying' | 'png' | 'pdf'>('idle')
  const [tokens, setTokens] = useState<{ in: number; out: number } | null>(null)
  const [cost, setCost] = useState<{
    model: string
    inputTokens: number
    outputTokens: number
    costUsd: number
  } | null>(null)

  const [activeStage, setActiveStage] = useState(-1)
  const [doneStages, setDoneStages] = useState<number[]>([])
  const [stageLogs, setStageLogs] = useState<string[]>(['', '', '', ''])
  const [progressPct, setProgressPct] = useState(0)
  const [loadingPct, setLoadingPct] = useState('0%')
  const [latency, setLatency] = useState('—')
  const [sysState, setSysState] = useState('idle')
  const [clock, setClock] = useState('—')

  const textareaRef = useRef<HTMLTextAreaElement | null>(null)
  const resultPanelRef = useRef<HTMLDivElement | null>(null)
  const timersRef = useRef<ReturnType<typeof setTimeout>[]>([])
  const rafRef = useRef<number | null>(null)
  const runStartRef = useRef(0)

  useEffect(() => {
    const tick = () => {
      const d = new Date()
      const p = (n: number) => String(n).padStart(2, '0')
      setClock(`${p(d.getUTCHours())}:${p(d.getUTCMinutes())}:${p(d.getUTCSeconds())}Z`)
    }
    tick()
    const id = setInterval(tick, 1000)
    return () => clearInterval(id)
  }, [])

  useEffect(() => {
    if (appState === 'idle') {
      const t = setTimeout(() => textareaRef.current?.focus(), 200)
      return () => clearTimeout(t)
    }
  }, [appState])

  const clearTimers = useCallback(() => {
    timersRef.current.forEach((t) => clearTimeout(t))
    timersRef.current = []
    if (rafRef.current !== null) {
      cancelAnimationFrame(rafRef.current)
      rafRef.current = null
    }
  }, [])

  useEffect(() => () => clearTimers(), [clearTimers])

  const startLoadingAnimation = useCallback(() => {
    clearTimers()
    setActiveStage(0)
    setDoneStages([])
    setStageLogs(['', '', '', ''])
    setProgressPct(0)
    setLoadingPct('0%')
    setLatency('0.0s')
    const startTime = performance.now()
    runStartRef.current = startTime
    const totalMs = STAGE_MS * STAGES.length

    const tick = (now: number) => {
      const pct = Math.min(98, ((now - startTime) / totalMs) * 100)
      setProgressPct(pct)
      setLoadingPct(Math.floor(pct) + '%')
      setLatency(((now - startTime) / 1000).toFixed(1) + 's')
      if (pct < 98) rafRef.current = requestAnimationFrame(tick)
    }
    rafRef.current = requestAnimationFrame(tick)

    STAGES.forEach((stage, i) => {
      timersRef.current.push(
        setTimeout(() => {
          setActiveStage(i)
          setStageLogs((prev) => {
            const n = [...prev]
            n[i] = stage.logs[0] ?? ''
            return n
          })
          stage.logs.forEach((log, li) => {
            if (li === 0) return
            timersRef.current.push(
              setTimeout(
                () => {
                  setStageLogs((prev) => {
                    const n = [...prev]
                    n[i] = log
                    return n
                  })
                },
                (li * STAGE_MS) / stage.logs.length
              )
            )
          })
        }, i * STAGE_MS)
      )
      timersRef.current.push(
        setTimeout(
          () => {
            setDoneStages((prev) => [...prev, i])
            setStageLogs((prev) => {
              const n = [...prev]
              n[i] = stage.logs[stage.logs.length - 1] ?? ''
              return n
            })
          },
          (i + 1) * STAGE_MS
        )
      )
    })
  }, [clearTimers])

  const handleSubmit = useCallback(
    async (e: FormEvent) => {
      e.preventDefault()
      if (submitting) return

      if (!postText.trim() || postText.trim().length < 30) {
        setPostError('Paste the full LinkedIn post text (at least 30 characters).')
        setShakePost((k) => k + 1)
        return
      }

      setPostError(null)
      setSubmitting(true)
      setResult(null)
      setErrorMsg('')
      setSysState('running')
      setAppState('loading')
      startLoadingAnimation()

      let data: ApiResponse
      try {
        const res = await fetch('/api/mini-apps/linkedin-hook', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ post_text: postText.trim() }),
        })
        data = (await res.json()) as ApiResponse
      } catch {
        clearTimers()
        setErrorMsg('Network error. Please check your connection and try again.')
        setSysState('error')
        setAppState('error')
        setSubmitting(false)
        return
      }

      clearTimers()
      const elapsed = ((performance.now() - runStartRef.current) / 1000).toFixed(1) + 's'
      setLatency(elapsed)
      setProgressPct(100)
      setLoadingPct('100%')

      if (data.ok) {
        setDoneStages([0, 1, 2, 3])
        await new Promise((r) => setTimeout(r, 400))
        setResult(data.data)
        setTokens({ in: data.data.tokens_in, out: data.data.tokens_out })
        if (data.cost) setCost(data.cost)
        setResultTs(fmtTs(new Date()))
        setSysState('complete')
        setAppState('result')
      } else {
        setErrorMsg(data.message)
        setSysState('error')
        setAppState('error')
      }
      setSubmitting(false)
    },
    [postText, submitting, startLoadingAnimation, clearTimers]
  )

  const handleReset = useCallback(() => {
    clearTimers()
    setAppState('idle')
    setResult(null)
    setErrorMsg('')
    setPostError(null)
    setSubmitting(false)
    setSysState('idle')
    setLatency('—')
    setProgressPct(0)
    setTokens(null)
    setCost(null)
  }, [clearTimers])

  const handleCopyAll = useCallback(async () => {
    if (!result) return
    setExportState('copying')
    try {
      await navigator.clipboard.writeText(buildPlainText(result))
    } catch {
      const ta = document.createElement('textarea')
      ta.value = buildPlainText(result)
      ta.style.cssText = 'position:fixed;opacity:0'
      document.body.appendChild(ta)
      ta.select()
      document.execCommand('copy')
      document.body.removeChild(ta)
    }
    setTimeout(() => setExportState('idle'), 1800)
  }, [result])

  const handleDownloadPng = useCallback(async () => {
    if (!resultPanelRef.current || !result) return
    setExportState('png')
    try {
      const { default: html2canvas } = await import('html2canvas')
      const canvas = await html2canvas(resultPanelRef.current, {
        backgroundColor: '#101014',
        scale: 2,
        useCORS: true,
        logging: false,
      })
      const a = document.createElement('a')
      a.download = `linkedin-hook-${result.post_author.replace(/[^a-z0-9]/gi, '-').toLowerCase()}.png`
      a.href = canvas.toDataURL('image/png')
      a.click()
    } catch (e) {
      console.error(e)
    }
    setExportState('idle')
  }, [result])

  const handleDownloadPdf = useCallback(async () => {
    if (!resultPanelRef.current || !result) return
    setExportState('pdf')
    try {
      const { default: html2canvas } = await import('html2canvas')
      const { jsPDF } = await import('jspdf')
      const canvas = await html2canvas(resultPanelRef.current, {
        backgroundColor: '#101014',
        scale: 2,
        useCORS: true,
        logging: false,
      })
      const imgW = 190
      const imgH = (canvas.height / canvas.width) * imgW
      const pdf = new jsPDF({
        orientation: imgH > imgW ? 'portrait' : 'landscape',
        unit: 'mm',
      })
      pdf.addImage(canvas.toDataURL('image/png'), 'PNG', 10, 10, imgW, imgH)
      pdf.save(`linkedin-hook-${result.post_author.replace(/[^a-z0-9]/gi, '-').toLowerCase()}.pdf`)
    } catch (e) {
      console.error(e)
    }
    setExportState('idle')
  }, [result])

  return (
    <div className="linkedin-hook">
      <AuroraBackground />

      <Header />

      <main className="shell">
        <section className="hero">
          <span className="eyebrow">LinkedIn Post to Outbound Hook</span>
          <h1>
            Turn any post into a <span className="accent">personalised opener.</span>
          </h1>
          <p>
            Paste a LinkedIn post. We detect the trigger, profile the persona, and write three
            ready-to-send hooks — each with a different angle and channel.
          </p>
        </section>

        <div className="panel-wrap">
          <div className="panel">
            {appState !== 'idle' && (
              <div className="panel-readouts">
                <div className="prl">
                  <span>
                    <span className="stat-key">sys</span>{' '}
                    <span className="stat-val">{sysState}</span>
                  </span>
                  <span className="pr-sep hide-sm" />
                  <span className="hide-sm">
                    <span className="stat-key">eng</span> <span className="stat-val">v1.0</span>
                  </span>
                </div>
                <div className="prr">
                  {tokens && (
                    <>
                      <span className="hide-sm">
                        <span className="stat-key">tok</span>{' '}
                        <span className="stat-val">
                          {(tokens.in + tokens.out).toLocaleString()}
                        </span>
                      </span>
                      <span className="pr-sep hide-sm" />
                    </>
                  )}
                  <span className="hide-sm">
                    <span className="stat-key">lat</span>{' '}
                    <span className="stat-val">{latency}</span>
                  </span>
                  <span className="pr-sep hide-sm" />
                  <span>
                    <span className="stat-key">ts</span> <span className="stat-val">{clock}</span>
                  </span>
                </div>
              </div>
            )}

            <div className="panel-body">
              {/* IDLE */}
              <section className={`lh-state${appState === 'idle' ? 'active' : ''}`}>
                <div className="idle-label">LinkedIn post text</div>
                <form noValidate onSubmit={handleSubmit} autoComplete="off">
                  <div className="textarea-field">
                    <label>Paste the full post</label>
                    <div
                      key={`p-${shakePost}`}
                      className={clsx('textarea-box', { error: postError })}
                    >
                      <textarea
                        ref={textareaRef}
                        placeholder={`Just raised our Series A...\nHiring 10 engineers in Q3...\nWhy I stopped using spreadsheets for sales...`}
                        value={postText}
                        disabled={submitting}
                        onChange={(e) => {
                          setPostText(e.target.value)
                          if (postError) setPostError(null)
                        }}
                      />
                    </div>
                    {postError && <div className="field-error">{postError}</div>}
                    <div className="char-count">{postText.length} chars</div>
                  </div>
                  <div className="submit-row">
                    <button type="submit" className="submit-btn" disabled={submitting}>
                      <svg
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        strokeWidth="2.2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      >
                        <path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z" />
                      </svg>
                      Generate hooks
                    </button>
                  </div>
                </form>
              </section>

              {/* LOADING */}
              <section className={`lh-state${appState === 'loading' ? 'active' : ''}`}>
                <div className="progress-track">
                  <div className="progress-bar" style={{ width: `${progressPct}%` }} />
                </div>
                <div className="loading-header">
                  <span>Analysing post</span>
                  <span>{loadingPct}</span>
                </div>
                <div className="stages">
                  {STAGES.map((s, i) => {
                    const isActive = activeStage === i && !doneStages.includes(i)
                    const isDone = doneStages.includes(i)
                    return (
                      <div
                        key={s.num}
                        className={clsx('stage', { active: isActive, done: isDone })}
                      >
                        <div className="stage-num-row">
                          <span>{s.num}</span>
                          <span className="stage-status-icon">
                            <svg viewBox="0 0 12 12" fill="none">
                              <path
                                d="M2 6.5l2.5 2.5L10 3"
                                stroke="currentColor"
                                strokeWidth="2"
                                strokeLinecap="round"
                                strokeLinejoin="round"
                              />
                            </svg>
                          </span>
                        </div>
                        <div className="stage-title">{s.title}</div>
                        <div className="stage-log">{stageLogs[i]}</div>
                      </div>
                    )
                  })}
                </div>
              </section>

              {/* RESULT */}
              <section className={`lh-state${appState === 'result' ? 'active' : ''}`}>
                {result && (
                  <EmailGate
                    miniAppSlug="linkedin-post-outbound-hook"
                    pattern="upfront"
                    initialInput={{ post_text: postText.trim() }}
                  >
                    {({ submitToApi }) => (
                      <>
                        <SubmitOnce
                          submit={submitToApi}
                          input={{ post_text: postText.trim() }}
                          output={result}
                          cost={cost ?? undefined}
                        />
                        <div ref={resultPanelRef}>
                          <div className="result-head">
                            <span className="title">Hooks ready — {result.post_author}</span>
                            <span className="ts-label">{resultTs}</span>
                          </div>

                          <div className="trigger-block">
                            <div className="trigger-eyebrow">
                              {'// Outbound trigger'}
                              <span className="trigger-type-badge">{result.trigger_type}</span>
                            </div>
                            <p className="trigger-text">{result.trigger}</p>
                            <div className="trigger-meta">
                              <span>Target: {result.target_persona}</span>
                              <span>Summary: {result.post_summary}</span>
                            </div>
                          </div>

                          <div className="section-header">
                            <span>{'// Outbound hooks'}</span>
                            <span className="count">{result.hooks.length} generated</span>
                          </div>
                          <div className="hooks">
                            {result.hooks.map((h, i) => (
                              <HookCard key={i} hook={h} isBest={i === result.best_hook_index} />
                            ))}
                          </div>
                        </div>

                        <div className="result-footer">
                          <span className="token-pill">
                            {tokens
                              ? `${(tokens.in + tokens.out).toLocaleString()} tokens · ${tokens.in.toLocaleString()} in / ${tokens.out.toLocaleString()} out`
                              : ''}
                          </span>
                          <div className="export-actions">
                            <button
                              className={`export-btn${exportState === 'copying' ? 'done' : ''}`}
                              type="button"
                              onClick={handleCopyAll}
                              disabled={exportState !== 'idle'}
                            >
                              {exportState === 'copying' ? (
                                <>
                                  <svg
                                    width="12"
                                    height="12"
                                    viewBox="0 0 24 24"
                                    fill="none"
                                    stroke="currentColor"
                                    strokeWidth="2.5"
                                    strokeLinecap="round"
                                    strokeLinejoin="round"
                                  >
                                    <path d="M20 6L9 17l-5-5" />
                                  </svg>
                                  Copied
                                </>
                              ) : (
                                <>
                                  <svg
                                    width="12"
                                    height="12"
                                    viewBox="0 0 24 24"
                                    fill="none"
                                    stroke="currentColor"
                                    strokeWidth="2"
                                    strokeLinecap="round"
                                    strokeLinejoin="round"
                                  >
                                    <rect x="9" y="9" width="13" height="13" rx="2" />
                                    <path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1" />
                                  </svg>
                                  Copy all
                                </>
                              )}
                            </button>
                            <button
                              className={`export-btn${exportState === 'png' ? 'loading' : ''}`}
                              type="button"
                              onClick={handleDownloadPng}
                              disabled={exportState !== 'idle'}
                            >
                              <svg
                                width="12"
                                height="12"
                                viewBox="0 0 24 24"
                                fill="none"
                                stroke="currentColor"
                                strokeWidth="2"
                                strokeLinecap="round"
                                strokeLinejoin="round"
                              >
                                <rect x="3" y="3" width="18" height="18" rx="2" />
                                <circle cx="8.5" cy="8.5" r="1.5" />
                                <path d="M21 15l-5-5L5 21" />
                              </svg>
                              {exportState === 'png' ? '…' : 'PNG'}
                            </button>
                            <button
                              className={`export-btn${exportState === 'pdf' ? 'loading' : ''}`}
                              type="button"
                              onClick={handleDownloadPdf}
                              disabled={exportState !== 'idle'}
                            >
                              <svg
                                width="12"
                                height="12"
                                viewBox="0 0 24 24"
                                fill="none"
                                stroke="currentColor"
                                strokeWidth="2"
                                strokeLinecap="round"
                                strokeLinejoin="round"
                              >
                                <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z" />
                                <path d="M14 2v6h6" />
                                <path d="M12 18v-6M9 15l3 3 3-3" />
                              </svg>
                              {exportState === 'pdf' ? '…' : 'PDF'}
                            </button>
                            <button className="run-again" type="button" onClick={handleReset}>
                              New post
                              <svg
                                width="12"
                                height="12"
                                viewBox="0 0 24 24"
                                fill="none"
                                stroke="currentColor"
                                strokeWidth="2.4"
                                strokeLinecap="round"
                                strokeLinejoin="round"
                              >
                                <path d="M5 12h14" />
                                <path d="M13 5l7 7-7 7" />
                              </svg>
                            </button>
                          </div>
                        </div>
                      </>
                    )}
                  </EmailGate>
                )}
              </section>

              {/* ERROR */}
              <section className={`lh-state error-state${appState === 'error' ? 'active' : ''}`}>
                <div className="err-icon">
                  <svg
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.8"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <circle cx="12" cy="12" r="10" />
                    <line x1="5.5" y1="5.5" x2="18.5" y2="18.5" />
                  </svg>
                </div>
                <h2 className="err-title">Analysis failed</h2>
                <p className="err-msg">{errorMsg}</p>
                <button className="err-btn" type="button" onClick={handleReset}>
                  Try again
                </button>
              </section>
            </div>
          </div>
        </div>

        <HowItWorks
          title={
            <>
              From a single post to <span className="accent">ranked hooks</span>
            </>
          }
          subtitle="No login, no install. Four steps from paste to a ready-to-send opener."
          steps={HOOK_STEPS}
        />
      </main>

      <Footer />
      <PageScripts />
    </div>
  )
}
