import type { FindPeopleResult, Person } from './types'

const STUB_PEOPLE: Person[] = [
  {
    fullName: 'Alex Rivera',
    title: 'VP of Engineering',
    department: 'Engineering',
    seniority: 'VP',
    linkedinUrl: 'https://linkedin.com/in/alex-rivera-demo',
    photoUrl: null,
    location: 'San Francisco, CA',
  },
  {
    fullName: 'Priya Sharma',
    title: 'Director of Sales',
    department: 'Sales',
    seniority: 'Director',
    linkedinUrl: 'https://linkedin.com/in/priya-sharma-demo',
    photoUrl: null,
    location: 'New York, NY',
  },
  {
    fullName: 'Marcus Chen',
    title: 'Chief Marketing Officer',
    department: 'Marketing',
    seniority: 'C-suite',
    linkedinUrl: 'https://linkedin.com/in/marcus-chen-demo',
    photoUrl: null,
    location: 'San Francisco, CA',
  },
  {
    fullName: 'Sofia Martinez',
    title: 'Senior Product Manager',
    department: 'Product',
    seniority: 'Manager',
    linkedinUrl: 'https://linkedin.com/in/sofia-martinez-demo',
    photoUrl: null,
    location: 'Austin, TX',
  },
  {
    fullName: 'James Okafor',
    title: 'Staff Software Engineer',
    department: 'Engineering',
    seniority: 'Individual',
    linkedinUrl: 'https://linkedin.com/in/james-okafor-demo',
    photoUrl: null,
    location: 'Remote',
  },
  {
    fullName: 'Yuki Tanaka',
    title: 'Head of Customer Success',
    department: 'Operations',
    seniority: 'Director',
    linkedinUrl: 'https://linkedin.com/in/yuki-tanaka-demo',
    photoUrl: null,
    location: 'Tokyo, JP',
  },
  {
    fullName: 'Olivia Bennett',
    title: 'CFO',
    department: 'Operations',
    seniority: 'C-suite',
    linkedinUrl: 'https://linkedin.com/in/olivia-bennett-demo',
    photoUrl: null,
    location: 'San Francisco, CA',
  },
  {
    fullName: 'Diego Fernandez',
    title: 'Account Executive',
    department: 'Sales',
    seniority: 'Individual',
    linkedinUrl: 'https://linkedin.com/in/diego-fernandez-demo',
    photoUrl: null,
    location: 'Mexico City, MX',
  },
  {
    fullName: 'Hannah Goldberg',
    title: 'VP of Marketing',
    department: 'Marketing',
    seniority: 'VP',
    linkedinUrl: 'https://linkedin.com/in/hannah-goldberg-demo',
    photoUrl: null,
    location: 'Los Angeles, CA',
  },
  {
    fullName: 'Rajesh Kumar',
    title: 'Engineering Manager',
    department: 'Engineering',
    seniority: 'Manager',
    linkedinUrl: 'https://linkedin.com/in/rajesh-kumar-demo',
    photoUrl: null,
    location: 'Bangalore, IN',
  },
  {
    fullName: 'Emma Schmidt',
    title: 'Product Designer',
    department: 'Product',
    seniority: 'Individual',
    linkedinUrl: 'https://linkedin.com/in/emma-schmidt-demo',
    photoUrl: null,
    location: 'Berlin, DE',
  },
  {
    fullName: 'Tyrone Williams',
    title: 'Sales Development Rep',
    department: 'Sales',
    seniority: 'Individual',
    linkedinUrl: 'https://linkedin.com/in/tyrone-williams-demo',
    photoUrl: null,
    location: 'Chicago, IL',
  },
  {
    fullName: 'Aisha Khan',
    title: 'Director of Product',
    department: 'Product',
    seniority: 'Director',
    linkedinUrl: 'https://linkedin.com/in/aisha-khan-demo',
    photoUrl: null,
    location: 'London, UK',
  },
  {
    fullName: 'Nathan Park',
    title: 'CEO',
    department: null,
    seniority: 'C-suite',
    linkedinUrl: 'https://linkedin.com/in/nathan-park-demo',
    photoUrl: null,
    location: 'San Francisco, CA',
  },
  {
    fullName: 'Beatrice Müller',
    title: 'Marketing Manager',
    department: 'Marketing',
    seniority: 'Manager',
    linkedinUrl: 'https://linkedin.com/in/beatrice-muller-demo',
    photoUrl: null,
    location: 'Amsterdam, NL',
  },
  {
    fullName: 'Kwame Asante',
    title: 'Senior Backend Engineer',
    department: 'Engineering',
    seniority: 'Individual',
    linkedinUrl: 'https://linkedin.com/in/kwame-asante-demo',
    photoUrl: null,
    location: 'Toronto, CA',
  },
  {
    fullName: 'Mira Patel',
    title: 'VP of Operations',
    department: 'Operations',
    seniority: 'VP',
    linkedinUrl: 'https://linkedin.com/in/mira-patel-demo',
    photoUrl: null,
    location: 'New York, NY',
  },
  {
    fullName: 'Lucas Pereira',
    title: 'Sales Manager',
    department: 'Sales',
    seniority: 'Manager',
    linkedinUrl: 'https://linkedin.com/in/lucas-pereira-demo',
    photoUrl: null,
    location: 'São Paulo, BR',
  },
  {
    fullName: 'Chloe Dubois',
    title: 'Content Strategist',
    department: 'Marketing',
    seniority: 'Individual',
    linkedinUrl: 'https://linkedin.com/in/chloe-dubois-demo',
    photoUrl: null,
    location: 'Paris, FR',
  },
  {
    fullName: 'Adesh Singh',
    title: 'Director of Engineering',
    department: 'Engineering',
    seniority: 'Director',
    linkedinUrl: 'https://linkedin.com/in/adesh-singh-demo',
    photoUrl: null,
    location: 'Remote',
  },
  {
    fullName: 'Naomi Carter',
    title: 'People Operations Lead',
    department: 'Operations',
    seniority: 'Manager',
    linkedinUrl: 'https://linkedin.com/in/naomi-carter-demo',
    photoUrl: null,
    location: 'Seattle, WA',
  },
  {
    fullName: 'Erik Larsson',
    title: 'Solutions Engineer',
    department: 'Engineering',
    seniority: 'Individual',
    linkedinUrl: 'https://linkedin.com/in/erik-larsson-demo',
    photoUrl: null,
    location: 'Stockholm, SE',
  },
  {
    fullName: 'Zara Ahmed',
    title: 'Senior Product Manager',
    department: 'Product',
    seniority: 'Manager',
    linkedinUrl: 'https://linkedin.com/in/zara-ahmed-demo',
    photoUrl: null,
    location: 'Dubai, AE',
  },
  {
    fullName: 'Hiroshi Yamamoto',
    title: 'CTO',
    department: 'Engineering',
    seniority: 'C-suite',
    linkedinUrl: 'https://linkedin.com/in/hiroshi-yamamoto-demo',
    photoUrl: null,
    location: 'San Francisco, CA',
  },
  {
    fullName: 'Maya Robinson',
    title: 'Customer Success Manager',
    department: 'Operations',
    seniority: 'Manager',
    linkedinUrl: 'https://linkedin.com/in/maya-robinson-demo',
    photoUrl: null,
    location: 'Boston, MA',
  },
]

export function buildStubResponse(companyInput: string, isDomain: boolean): FindPeopleResult {
  const companyName = isDomain
    ? companyInput.replace(/\..*$/, '').replace(/^./, (c) => c.toUpperCase())
    : companyInput
  const companyDomain = isDomain
    ? companyInput.toLowerCase()
    : `${companyInput.toLowerCase().replace(/[^a-z0-9]/g, '')}.com`
  return {
    companyName: `${companyName} (demo)`,
    companyDomain,
    totalEmployees: 247,
    people: STUB_PEOPLE,
  }
}
